[package]
name = "fm-io"
description = "FreeMat-rs file I/O, MAT-file support, FFT and regex builtins"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]

[lints]
workspace = true
