[package]
name = "fm-linalg"
description = "FreeMat-rs linear algebra (faer-backed)"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
fm-core = { version = "0.0.0", path = "../fm-core" }
faer.workspace = true
ndarray.workspace = true
num-complex.workspace = true

[lints]
workspace = true
