//! Migrated help docs for the `array` section (help-system P7).
//! GENERATED by `cargo xtask migrate-place` — do not edit by hand.

fm_doc::register_section! {
    id: "array",
    title: "Array Generation and Manipulations",
    summary: "Generate, reshape, and manipulate numeric arrays.",
}

fm_doc::register_doc! {
    name: "arrayfun",
    aliases: [],
    section: "array",
    summary: "Apply a Function To Elements of an Array",
    body: r#"
## Usage
The `arrayfun` function is used to apply a function handle
to each element of an input array (or arrays), and to collect
the outputs into an array.  The general syntax for its use is

```text
   y = arrayfun(fun, x)
```
where `x` is an N-dimensional array.  In this case, each
element of the output `y_i` is defined as `fun(x_i)`.  You can
also supply multiple arguments to `arrayfun`, provided all of the
arguments are the same size

```text
   y = arrayfun(fun, x, z,...)
```
in which case each output `y_i = fun(x_i,z_i,...)`.

If the function returns multiple outputs, then `arrayfun` can be
called with multiple outputs, in which case each output goes to
a separate array output

```text
   [y1,y2,...] = arrayfun(fun, x, z, ...)
```
The assumption is that the output types for each call to `fun` is
the same across the inputs.

Finally, some hints can be provided to `arrayfun` using the syntax

```text
   [y1,y2,...] = arrayfun(fun, x, z, ..., 'param', value, 'param', value)
```
where `param` and `value` take on the following possible values:
- `'UniformOutput'` - if the `value` is `true` then each output of `fun`
   must be a scalar, and the outputs are concatenated into an array the same size
   as the input arrays.  If the `value` is `false` then the outputs are encapsulated
   into a cell array, with each entry in the cell array containing the call to
   `fun(x_i,z_i,...)`.

- `'ErrorHandler'` - in this case `value` is a function handle that gets called
  when `fun` throws an error.  If `'ErrorHandler'` is not specified, then `arrayfun`
  allows the error to propogate (i.e., and exception is thrown).
"#,
}

fm_doc::register_doc! {
    name: "assign",
    aliases: [],
    section: "array",
    summary: "Making assignments",
    body: r#"
## Usage
FreeMat assignments take a number of different forms, depending
on the type of the variable you want to make an assignment to.
For numerical arrays and strings, the form of an assignment
is either

```text
  a(ndx) = val
```
where `ndx` is a set of vector indexing coordinates.  This means
that the values `ndx` takes reference the elements of `a` in column
order.  So, if, for example `a` is an `N x M` matrix, the first column
has vector indices `1,2,...,N`, and the second column has indices
`N+1,N+2,...,2N`, and so on.  Alternately, you can use multi-dimensional
indexing to make an assignment:

```text
  a(ndx_1,ndx_2,..,ndx_m) = val
```
where each indexing expression `ndx_i` corresponds to the `i-th` dimension
of `a`.  In both cases, (vector or multi-dimensional indexing), the
right hand side `val` must either be a scalar, an empty matrix, or of the
same size as the indices.  If `val` is an empty matrix, the assignment acts
like a delete.  Note that the type of `a` may be modified by the assignment.
So, for example, assigning a `double` value to an element of a `float`
array `a` will cause the array `a` to become `double`.

For cell arrays, the above forms of assignment will still work, but only
if `val` is also a cell array.  If you want to assign the contents of
a cell in a cell array, you must use one of the two following forms, either

```text
  a{ndx} = val
```
or

```text
  a{ndx_1,ndx_2,...,ndx_m} = val
```
which will modify the contents of the cell.
"#,
}

fm_doc::register_doc! {
    name: "cell",
    aliases: [],
    section: "array",
    summary: "Cell Array of Empty Matrices",
    body: r#"
## Usage
Creates a cell array of empty matrix entres.  Two seperate
syntaxes are possible.  The first syntax specifies the array
dimensions as a sequence of scalar dimensions:

```text
   y = cell(d1,d2,...,dn).
```
The resulting array has the given dimensions, and is filled with
all zeros.  The type of `y` is `cell`, a cell array.

The second syntax specifies the array dimensions as a vector,
where each element in the vector specifies a dimension length:

```text
   y = cell([d1,d2,...,dn]).
```
This syntax is more convenient for calling `zeros` using a
variable for the argument.  In both cases, specifying only one
dimension results in a square matrix output.

## Example
The following examples demonstrate generation of some zero arrays
using the first form.

```fm-exec
cell(2,3,2)
cell(1,3)
```

The same expressions, using the second form.

```fm-exec
cell([2,6])
cell([1,3])
```
"#,
}

fm_doc::register_doc! {
    name: "cellfun",
    aliases: [],
    section: "array",
    summary: "Appy a Function To Elements of a Cell Array",
    body: r#"
## Usage
The `cellfun` function is used to apply a function handle
(or anonymous function) to each element of a cell array and to
collect the outputs into an array.  The general syntax for its
use is

```text
   y = cellfun(fun, x)
```
where `x` is an N-dimensional array.  In this case, each
element of the output `y_i` is defined as `fun(x{i})`.  You can
also supply multiple arguments to `cellfun`, provided all of the
arguments are the same size

```text
   y = cellfun(fun, x, z, ...)
```
in which case each output `y_i` is defined as `fun(x{i},z{i},...)`.
Note that unlike `arrayfun`, the `cellfun` function will allow for
different types (if there are overloaded versions of the function
`fun`) for each element.

If the function returns multiple outputs, then `arrayfun` can be
called with multiple outputs, in which case each output goes to
a separate array output

```text
   [y1,y2,...] = cellfun(fun, x, z, ...)
```
The assumption is that the output types for each call to `fun` is
the same across the inputs.

Finally, some hints can be provided to `cellfun` using the syntax

```text
   [y1,y2,...] = cellfun(fun, x, z, ..., 'param', value, 'param', value)
```
where `param` and `value` take on the following possible values:
- `'UniformOutput'` - if the `value` is `true` then each output of `fun`
   must be a scalar, and the outputs are concatenated into an array the same size
   as the input arrays.  If the `value` is `false` then the outputs are encapsulated
   into a cell array, with each entry in the cell array containing the call to
   `fun(x_i,z_i,...)`.

- `'ErrorHandler'` - in this case `value` is a function handle that gets called
  when `fun` throws an error.  If `'ErrorHandler'` is not specified, then `arrayfun`
  allows the error to propogate (i.e., and exception is thrown).
"#,
}

fm_doc::register_doc! {
    name: "circshift",
    aliases: [],
    section: "array",
    summary: "Circularly Shift an Array",
    body: r#"
## Usage
Applies a circular shift along each dimension of a given array.  The
syntax for its use is

```text
   y = circshift(x,shiftvec)
```
where `x` is an n-dimensional array, and `shiftvec` is a vector of
integers, each of which specify how much to shift `x` along the
corresponding dimension.

## Example
The following examples show some uses of `circshift` on N-dimensional
arrays.

```fm-exec
x = int32(rand(4,5)*10)
circshift(x,[1,0])
circshift(x,[0,-1])
circshift(x,[2,2])
x = int32(rand(4,5,3)*10)
circshift(x,[1,0,0])
circshift(x,[0,-1,0])
circshift(x,[0,0,-1])
circshift(x,[2,-3,1])
```
"#,
}

fm_doc::register_doc! {
    name: "cond",
    aliases: [],
    section: "array",
    summary: "Condition Number of a Matrix",
    body: r#"
## Usage
Calculates the condition number of a matrix.  To compute the
2-norm condition number of a matrix (ratio of largest to smallest
singular values), use the syntax

```text
   y = cond(A)
```
where A is a matrix.  If you want to compute the condition number
in a different norm (e.g., the 1-norm), use the second syntax

```text
   y = cond(A,p)
```
where `p` is the norm to use when computing the condition number.
The following choices of `p` are supported
- `p = 1` returns the 1-norm, or the max column sum of A

- `p = 2` returns the 2-norm (largest singular value of A)

- `p = inf` returns the infinity norm, or the max row sum of A

- `p = 'fro'` returns the Frobenius-norm (vector Euclidean norm, or RMS value)

## Function Internals
The condition number is defined as

$$
  \frac{\|A\|_p}{\|A^{-1}\|_p}
$$
This equation is precisely how the condition number is computed for
the case `p ~= 2`.  For the `p=2` case, the condition number can
be computed much more efficiently using the ratio of the largest and
smallest singular values.

## Example
The condition number of this matrix is large

```fm-exec
A = [1,1;0,1e-15]
cond(A)
cond(A,1)
```

You can also (for the case `p=1` use `rcond` to calculate an estimate
of the condition number

```fm-exec
1/rcond(A)
```
"#,
}

fm_doc::register_doc! {
    name: "det",
    aliases: [],
    section: "array",
    summary: "Determinant of a Matrix",
    body: r#"
## Usage
Calculates the determinant of a matrix.  Note that for all but
very small problems, the determinant is not particularly useful.
The condition number `cond` gives a more reasonable estimate as
to the suitability of a matrix for inversion than comparing `det(A)`
to zero.  In any case, the syntax for its use is

```text
  y = det(A)
```
where A is a square matrix.

## Function Internals
The determinant is calculated via the `LU` decomposition.  Note that
the determinant of a product of matrices is the product of the
determinants.  Then, we have that

$$
  L U = P A
$$
where `L` is lower triangular with 1s on the main diagonal, `U` is
upper triangular, and `P` is a row-permutation matrix.  Taking the
determinant of both sides yields

$$
 |L U| = |L| |U| = |U| = |P A| = |P| |A|
$$
where we have used the fact that the determinant of `L` is 1.  The
determinant of `P` (which is a row exchange matrix) is either 1 or
-1.

## Example
Here we assemble a random matrix and compute its determinant

```fm-exec
A = rand(5);
det(A)
```

Then, we exchange two rows of `A` to demonstrate how the determinant
changes sign (but the magnitude is the same)

```fm-exec
B = A([2,1,3,4,5],:);
det(B)
```
"#,
}

fm_doc::register_doc! {
    name: "diag",
    aliases: [],
    section: "array",
    summary: "Diagonal Matrix Construction/Extraction",
    body: r#"
## Usage
The `diag` function is used to either construct a
diagonal matrix from a vector, or return the diagonal
elements of a matrix as a vector.  The general syntax
for its use is

```text
  y = diag(x,n)
```
If `x` is a matrix, then `y` returns the `n`-th
diagonal.  If `n` is omitted, it is assumed to be
zero.  Conversely, if `x` is a vector, then `y`
is a matrix with `x` set to the `n`-th diagonal.

## Examples
Here is an example of `diag` being used to extract
a diagonal from a matrix.

```fm-exec
A = int32(10*rand(4,5))
diag(A)
diag(A,1)
```

Here is an example of the second form of `diag`, being
used to construct a diagonal matrix.

```fm-exec
x = int32(10*rand(1,3))
diag(x)
diag(x,-1)
```
"#,
}

fm_doc::register_doc! {
    name: "expm",
    aliases: [],
    section: "array",
    summary: "Matrix Exponential",
    body: r#"
## Usage
Calculates `e^A` for a square, full rank matrix `A`.  The
syntax for its use is

```text
   y = expm(A)
```
Internally, `expm` is mapped to a simple `e^A` expression (which
in turn uses the eigenvalue expansion of `A` to compute the
exponential).

## Example
An example of `expm`

```fm
A = [1 1 0; 0 0 2; 0 0 -1]
expm(A)
```
"#,
}

fm_doc::register_doc! {
    name: "eye",
    aliases: [],
    section: "array",
    summary: "Identity Matrix",
    body: r#"
## Usage
Creates an identity matrix of the specified size.  The syntax for
its use is

```text
   y = eye(n)
```
where `n` is the size of the identity matrix.  The type of the
output matrix is `float`.

## Example
The following example demonstrates the identity matrix.

```fm-exec
eye(3)
```
"#,
}

fm_doc::register_doc! {
    name: "find",
    aliases: [],
    section: "array",
    summary: "Find Non-zero Elements of An Array",
    body: r#"
## Usage
Returns a vector that contains the indicies of all non-zero elements
in an array.  The usage is

```text
   y = find(x)
```
The indices returned are generalized column indices, meaning that if
the array `x` is of size `[d1,d2,...,dn]`, and the
element `x(i1,i2,...,in)` is nonzero, then `y`
will contain the integer

$$
   i_1 + (i_2-1) d_1 + (i_3-1) d_1 d_2 + \dots
$$
The second syntax for the `find` command is

```text
   [r,c] = find(x)
```
which returns the row and column index of the nonzero entries of `x`.
The third syntax for the `find` command also returns the values

```text
   [r,c,v] = find(x).
```
Note that if the argument is a row vector, then the returned vectors
are also row vectors. This form is particularly useful for converting
sparse matrices into IJV form.

The `find` command also supports some additional arguments.  Each of the
above forms can be combined with an integer indicating how many results
to return:

```text
   y = find(x,k)
```
where `k` is the maximum number of results to return.  This form will return
the first `k` results.  You can also specify an optional flag indicating
whether to take the first or last `k` values:

```text
   y = find(x,k,'first')
   y = find(x,k,'last')
```
in the case of the `'last'` argument, the last `k` values are returned.

## Example
Some simple examples of its usage, and some common uses of `find` in FreeMat programs.

```fm-exec
a = [1,2,5,2,4];
find(a==2)
```

Here is an example of using find to replace elements of `A` that are `0` with the number `5`.

```fm-exec
A = [1,0,3;0,2,1;3,0,0]
n = find(A==0)
A(n) = 5
```

Incidentally, a better way to achieve the same concept is:

```fm-exec
A = [1,0,3;0,2,1;3,0,0]
A(A==0) = 5
```

Now, we can also return the indices as row and column indices using the two argument
form of `find`:

```fm-exec
A = [1,0,3;0,2,1;3,0,0]
[r,c] = find(A)
```

Or the three argument form of `find`, which returns the value also:

```fm-exec
[r,c,v] = find(A)
```
"#,
}

fm_doc::register_doc! {
    name: "flipdim",
    aliases: [],
    section: "array",
    summary: "Reverse a Matrix Along a Given Dimension",
    body: r#"
## Usage
Reverses an array along the given dimension.  The syntax for its use is

```text
   y = flipdim(x,n)
```
where `x` is matrix, and `n` is the dimension to reverse.

## Example
The following examples show some uses of `flipdim` on N-dimensional
arrays.

```fm-exec
x = int32(rand(4,5,3)*10)
flipdim(x,1)
flipdim(x,2)
flipdim(x,3)
```
"#,
}

fm_doc::register_doc! {
    name: "fliplr",
    aliases: [],
    section: "array",
    summary: "Reverse the Columns of a Matrix",
    body: r#"
## Usage
Reverses the columns of a matrix.  The syntax for its use is

```text
   y = fliplr(x)
```
where `x` is matrix.  If `x` is an N-dimensional array then
the second dimension is reversed.

## Example
The following example shows `fliplr` applied to a 2D matrix.

```fm-exec
x = int32(rand(4)*10)
fliplr(x)
```

For a 3D array, note how the columns in each slice are flipped.

```fm-exec
x = int32(rand(4,4,3)*10)
fliplr(x)
```
"#,
}

fm_doc::register_doc! {
    name: "flipud",
    aliases: [],
    section: "array",
    summary: "Reverse the Columns of a Matrix",
    body: r#"
## Usage
Reverses the rows of a matrix.  The syntax for its use is

```text
   y = flipud(x)
```
where `x` is matrix.  If `x` is an N-dimensional array then
the first dimension is reversed.

## Example
The following example shows `flipud` applied to a 2D matrix.

```fm-exec
x = int32(rand(4)*10)
flipud(x)
```

For a 3D array, note how the rows in each slice are flipped.

```fm-exec
x = int32(rand(4,4,3)*10)
flipud(x)
```
"#,
}

fm_doc::register_doc! {
    name: "ipermute",
    aliases: [],
    section: "array",
    summary: "Array Inverse Permutation Function",
    body: r#"
## Usage
The `ipermute` function rearranges the contents of an array according
to the inverse of the specified permutation vector.  The syntax for
its use is

```text
   y = ipermute(x,p)
```
where `p` is a permutation vector - i.e., a vector containing the
integers `1...ndims(x)` each occuring exactly once.  The resulting
array `y` contains the same data as the array `x`, but ordered
according to the inverse of the given permutation.  This function and
the `permute` function are inverses of each other.

## Example
First we create a large multi-dimensional array, then permute it
 and then inverse permute it, to retrieve the original array:

```fm-exec
A = randn(13,5,7,2);
size(A)
B = permute(A,[3,4,2,1]);
size(B)
C = ipermute(B,[3,4,2,1]);
size(C)
any(A~=C)
```
"#,
}

fm_doc::register_doc! {
    name: "isfloat",
    aliases: [],
    section: "array",
    summary: "Test for Floating Point Array",
    body: r#"
## Usage
The syntax for `isfloat` is

```text
   x = isfloat(y)
```
and it returns a logical 1 if the argument is a floating
point array (i.e., a `single` or `double`), and a logical
0 otherwise.
"#,
}

fm_doc::register_doc! {
    name: "isinteger",
    aliases: [],
    section: "array",
    summary: "Test for Integer Array",
    body: r#"
## Usage
The syntax for `isinteger` is

```text
  x = isinteger(y)
```
and it returns a logical 1 if the argument is an integer.
The decision of whether the argument is an integer or not
is made based on the class of `y`, not on its value.
"#,
}

fm_doc::register_doc! {
    name: "linspace",
    aliases: [],
    section: "array",
    summary: "Linearly Spaced Vector",
    body: r#"
## Usage
Generates a row vector with the specified number of elements, with
entries uniformly spaced between two specified endpoints.  The syntax
for its use is either

```text
   y = linspace(a,b,count)
```
or, for a default `count = 100`,

```text
   y = linspace(a,b);
```

## Examples
Here is a simple example of using `linspace`

```fm-exec
x = linspace(0,1,5)
```
"#,
}

fm_doc::register_doc! {
    name: "logspace",
    aliases: [],
    section: "array",
    summary: "Logarithmically Spaced Vector",
    body: r#"
## Usage
Generates a row vector with the specified number number of elements,
with entries logarithmically spaced between two specified endpoints.
The syntax for its use is either

```text
    y = logspace(a,b,count)
```
 or, for a default `count = 50`,

```text
    y = logspace(a,b)
```
 A third special use is when

```text
    y = logspace(a,pi)
```
where it generates points between `10^a` and `pi`

Contributed by Paulo Xavier Candeias under GPL.

## Example
Here is an example of the use of `logspace`

```fm-exec
logspace(1,2,3)
```
"#,
}

fm_doc::register_doc! {
    name: "meshgrid",
    aliases: [],
    section: "array",
    summary: "Generate Grid Mesh For Plots",
    body: r#"
## Usage
The `meshgrid` function generates arrays that can be used for the
generation of surface plots.  The syntax is one of

```text
  [X,Y] = meshgrid(x)
  [X,Y] = meshgrid(x,y)
  [X,Y,Z] = meshgrid(x,y,z)
```
where `x,y,z` are vectors, and `X,Y,Z` are matrices.  In the first
case `[X,Y] = meshgrid(x)`, the rows of `X` and the columns of `Y`
contain copies of the vector `x`.  In the second case
`[X,Y] = meshgrid(x,y)`, the rows of `X` contain copies of `x`, and
the columns of `Y` contain copies of `y`.  In the third case, each
input is copied along the row, column or slice direction of the
corresponding output variable.

## Example
In the first example:

```fm-exec
[X,Y] = meshgrid(-2:.4:2)
```

Next, we use different vectors for `X` and for `Y`:

```fm-exec
[X,Y] = meshgrid([1,2,3,4],[6,7,8])
```
"#,
}

fm_doc::register_doc! {
    name: "nan",
    aliases: [],
    section: "array",
    summary: "Not-a-Number Constant",
    body: r#"
## Usage
Returns a value that represents ``not-a-number'' for both 32 and 64-bit
floating point values.  This constant is meant to represent the result of
arithmetic operations whose output cannot be meaningfully defined (like
zero divided by zero).  There are several forms for the `NaN` function.
The first form returns a double precision `NaN`.

```text
   y = nan
```
The next form takes a class name that can be either `'double'`

```text
   y = nan('double')
```
or `'single'`:

```text
   y = nan('single')
```
With a single parameter it generates a square matrix of `nan`s.

```text
   y = nan(n)
```
Alternatively, you can specify the dimensions of the array via

```text
   y = nan(m,n,p,...)
```
or

```text
   y = nan([m,n,p,...])
```
Finally, you can add a classname of either `'single'` or `'double'`.

## Example
The following examples demonstrate a few calculations with the not-a-number constant.

```fm-exec
nan*0
nan-nan
```

Note that `NaN`s are preserved under type conversion to floating point types (i.e., `float`, `double`, `complex` and `dcomplex` types), but not integer  types.

```fm-exec
uint32(nan)
complex(nan)
```
"#,
}

fm_doc::register_doc! {
    name: "ndgrid",
    aliases: [],
    section: "array",
    summary: "Generate N-Dimensional Grid",
    body: r#"
## Usage
Generates N-dimensional grids, each of which is constant in all but
one dimension.  The syntax for its use is either

```text
   [y1, y2, ..., ym] = ndgrid(x1, x2, ..., xn)
```
where `m <= n` or

```text
   [y1, y2, ..., ym] = ndgrid(x1)
```
which is equivalent to the first form, with `x1=x2=...=xn`.  Each
output `yi` is an `n`-dimensional array, with values such that

$$
y_i(d_1,\ldots,d_{i-1},d_{i},d_{i+1},\ldots,d_m) = x_i(d_{i})
$$
`ndgrid` is useful for evaluating multivariate functionals over a
range of arguments.  It is a generalization of `meshgrid`, except
that `meshgrid` transposes the dimensions corresponding to the
first two arguments to better fit graphical applications.

## Example
Here is a simple `ndgrid` example

```fm-exec
[a,b] = ndgrid(1:2,3:5)
[a,b,c] = ndgrid(1:2,3:5,0:1)
```

Here we use the second form

```fm-exec
[a,b,c] = ndgrid(1:3)
```
"#,
}

fm_doc::register_doc! {
    name: "nonzeros",
    aliases: [],
    section: "array",
    summary: "Retrieve Nonzero Matrix Entries",
    body: r#"
## Usage
Returns a dense column vector containing the nonzero elements
of the argument matrix.  The syntax for its use is

```text
   y = nonzeros(x)
```
where `x` is the argument array.  The argument matrix may
be sparse as well as dense.

## Example
Here is an example of using `nonzeros` on a sparse matrix.

```fm-exec
a = rand(8); a(a>0.2) = 0;
A = sparse(a)
nonzeros(A)
```
"#,
}

fm_doc::register_doc! {
    name: "norm",
    aliases: [],
    section: "array",
    summary: "Norm Calculation",
    body: r#"
## Usage
Calculates the norm of a matrix.  There are two ways to
use the `norm` function.  The general syntax is

```text
   y = norm(A,p)
```
where `A` is the matrix to analyze, and `p` is the
type norm to compute.  The following choices of `p`
are supported
- `p = 1` returns the 1-norm, or the max column sum of A

- `p = 2` returns the 2-norm (largest singular value of A)

- `p = inf` returns the infinity norm, or the max row sum of A

- `p = 'fro'` returns the Frobenius-norm (vector Euclidean norm, or RMS value)

For a vector, the regular norm calculations are performed:
- `1 <= p < inf` returns `sum(abs(A).^p)^(1/p)`

- `p` unspecified returns `norm(A,2)`

- `p = inf` returns max(abs(A))

- `p = -inf` returns min(abs(A))

## Examples
Here are the various norms calculated for a sample matrix

```fm-exec
A = float(rand(3,4))
norm(A,1)
norm(A,2)
norm(A,inf)
norm(A,'fro')
```

Next, we calculate some vector norms.

```fm-exec
A = float(rand(4,1))
norm(A,1)
norm(A,2)
norm(A,7)
norm(A,inf)
norm(A,-inf)
```
"#,
}

fm_doc::register_doc! {
    name: "num2str",
    aliases: [],
    section: "array",
    summary: "Convert Numbers To Strings",
    body: r#"
## Usage
Converts an array into its string representation.  The general syntax
for this function is

```text
   s = num2str(X)
```
where `s` is a string (or string matrix) and `X` is an array.  By
default, the `num2str` function uses 4 digits of precision and an
exponent if required.  If you want more digits of precision, you can
specify the precition via the form

```text
   s = num2str(X, precision)
```
where `precision` is the number of digits to include in the string
representation.  For more control over the format of the output, you
can also specify a format specifier (see `printf` for more details).

```text
   s = num2str(X, format)
```
where `format` is the specifier string.
"#,
}

fm_doc::register_doc! {
    name: "ones",
    aliases: [],
    section: "array",
    summary: "Array of Ones",
    body: r#"
## Usage
Creates an array of ones of the specified size.  Two seperate
syntaxes are possible.  The first syntax specifies the array
dimensions as a sequence of scalar dimensions:

```text
   y = ones(d1,d2,...,dn).
```
The resulting array has the given dimensions, and is filled with
all ones.  The type of `y` is `float`, a 32-bit floating
point array.  To get arrays of other types, use the typecast
functions (e.g., `uint8`, `int8`, etc.).

The second syntax specifies the array dimensions as a vector,
where each element in the vector specifies a dimension length:

```text
   y = ones([d1,d2,...,dn]).
```
This syntax is more convenient for calling `ones` using a
variable for the argument.  In both cases, specifying only one
dimension results in a square matrix output.

## Example
The following examples demonstrate generation of some arrays of ones
using the first form.

```fm-exec
ones(2,3,2)
ones(1,3)
```

The same expressions, using the second form.

```fm-exec
ones([2,6])
ones([1,3])
```

Finally, an example of using the type casting function `uint16` to generate an array of 16-bit unsigned integers with a value of 1.

```fm-exec
uint16(ones(3))
```
"#,
}

fm_doc::register_doc! {
    name: "permute",
    aliases: [],
    section: "array",
    summary: "Array Permutation Function",
    body: r#"
## Usage
The `permute` function rearranges the contents of an array according
to the specified permutation vector.  The syntax for its use is

```text
    y = permute(x,p)
```
where `p` is a permutation vector - i.e., a vector containing the
integers `1...ndims(x)` each occuring exactly once.  The resulting
array `y` contains the same data as the array `x`, but ordered
according to the permutation.  This function is a generalization of
the matrix transpose operation.

## Example
Here we use `permute` to transpose a simple matrix (note that permute
also works for sparse matrices):

```fm-exec
A = [1,2;4,5]
permute(A,[2,1])
A'
```

Now we permute a larger n-dimensional array:

```fm-exec
A = randn(13,5,7,2);
size(A)
B = permute(A,[3,4,2,1]);
size(B)
```
"#,
}

fm_doc::register_doc! {
    name: "pinv",
    aliases: [],
    section: "array",
    summary: "Moore-Penrose Pseudoinverse",
    body: r#"
## Usage
Calculates the Moore-Penrose pseudoinverse of a matrix.
The general syntax for its use is

```text
   y = pinv(A,tol)
```
or for a default specification of the tolerance `tol`,

```text
   y = pinv(A)
```
For any `m x n` matrix `A`, the Moore-Penrose pseudoinverse
is the unique `n x m` matrix `B` that satisfies the following
four conditions
- `A B A = A`

- `B A B = B`

- `(A B)' = A B`

- `(B A)' = B A`

Also, it is true that `B y` is the minimum norm, least squares
solution to `A x = y`.  The Moore-Penrose pseudoinverse is computed
from the singular value decomposition of `A`, with singular values
smaller than `tol` being treated as zeros.  If `tol` is not specified
then it is chosen as

```text
  tol = max(size(A)) * norm(A) * teps(A).
```

## Function Internals
The calculation of the MP pseudo-inverse is almost trivial once the
svd of the matrix is available.  First, for a real, diagonal matrix
with positive entries, the pseudo-inverse is simply

$$
  \left(\Sigma^{+}\right)_{ii} = \begin{cases}
             1/\sigma_{ii} & \sigma_{ii} > 0 \\
             0             & \mathrm{else} \end{cases}
$$
One can quickly verify that this choice of matrix satisfies the
four properties of the pseudoinverse.  Then, the pseudoinverse
of a general matrix `A = U S V'` is defined as

$$
   A^{+} = V S^{+} U'
$$
and again, using the facts that `U' U = I` and `V V' = I`, one
can quickly verify that this choice of pseudoinverse satisfies the
four defining properties of the MP pseudoinverse.  Note that in
practice, the diagonal pseudoinverse `S^{+}` is computed with
a threshold (the `tol` argument to `pinv`) so that singular
values smaller than `tol` are treated like zeros.

## Examples
Consider a simple `1 x 2` matrix example, and note the various
Moore-Penrose conditions:

```fm-exec
A = float(rand(1,2))
B = pinv(A)
A*B*A
B*A*B
A*B
B*A
```

To demonstrate that `pinv` returns the least squares solution,
consider the following very simple case

```fm-exec
A = float([1;1;1;1])
```

The least squares solution to `A x = b` is just `x = mean(b)`,
and computing the `pinv` of `A` demonstrates this

```fm-exec
pinv(A)
```

Similarly, we can demonstrate the minimum norm solution with
the following simple case

```fm-exec
A = float([1,1])
```

The solutions of `A x = 5` are those `x_1` and `x_2` such that
`x_1 + x_2 = 5`.  The norm of `x` is `x_1^ + x_2^2`, which is
`x_1^2 + (5-x_1)^2`, which is minimized for `x_1 = x_2 = 2.5`:

```fm-exec
pinv(A) * 5.0
```
"#,
}

fm_doc::register_doc! {
    name: "rank",
    aliases: [],
    section: "array",
    summary: "Calculate the Rank of a Matrix",
    body: r#"
## Usage
Returns the rank of a matrix.  There are two ways to use
the `rank` function is

```text
   y = rank(A,tol)
```
where `tol` is the tolerance to use when computing the
rank.  The second form is

```text
   y = rank(A)
```
in which case the tolerance `tol` is chosen as

```text
   tol = max(size(A))*max(s)*eps,
```
where `s` is the vector of singular values of `A`.  The
rank is computed using the singular value decomposition `svd`.

## Examples
Some examples of matrix rank calculations

```fm-exec
rank([1,3,2;4,5,6])
rank([1,2,3;2,4,6])
```

Here we construct an ill-conditioned matrix, and show the use
of the `tol` argument.

```fm-exec
A = [1,0;0,eps/2]
rank(A)
rank(A,eps/8)
```
"#,
}

fm_doc::register_doc! {
    name: "rcond",
    aliases: [],
    section: "array",
    summary: "Reciprocal Condition Number Estimate",
    body: r#"
## Usage
The `rcond` function is a FreeMat wrapper around LAPACKs
function `XGECON`, which estimates the 1-norm condition
number (reciprocal).  For the details of the algorithm see
the LAPACK documentation.  The syntax for its use is

```text
   x = rcond(A)
```
where `A` is a matrix.

## Example
Here is the reciprocal condition number for a random square
matrix

```fm-exec
A = rand(30);
rcond(A)
```

And here we calculate the same value using the definition of
(reciprocal) condition number

```fm-exec
1/(norm(A,1)*norm(inv(A),1))
```

Note that the values are very similar.  LAPACKs `rcond`
function is far more efficient than the explicit calculation
(which is also used by the `cond` function.
"#,
}

fm_doc::register_doc! {
    name: "repmat",
    aliases: [],
    section: "array",
    summary: "Array Replication Function",
    body: r#"
## Usage
The `repmat` function replicates an array the specified
number of times.  The source and destination arrays may
be multidimensional.  There are three distinct syntaxes for
the `repmap` function.  The first form:

```text
  y = repmat(x,n)
```
replicates the array `x` on an `n-times-n` tiling, to create
a matrix `y` that has `n` times as many rows and columns
as `x`.  The output `y` will match `x` in all remaining
dimensions.  The second form is

```text
  y = repmat(x,m,n)
```
And creates a tiling of `x` with `m` copies of `x` in the
row direction, and `n` copies of `x` in the column direction.
The final form is the most general

```text
  y = repmat(x,[m n p...])
```
where the supplied vector indicates the replication factor in
each dimension.

## Example
Here is an example of using the `repmat` function to replicate
a row 5 times.  Note that the same effect can be accomplished
(although somewhat less efficiently) by a multiplication.

```fm-exec
x = [1 2 3 4]
y = repmat(x,[5,1])
```

The `repmat` function can also be used to create a matrix of scalars
or to provide replication in arbitrary dimensions.  Here we use it to
replicate a 2D matrix into a 3D volume.

```fm-exec
x = [1 2;3 4]
y = repmat(x,[1,1,3])
```
"#,
}

fm_doc::register_doc! {
    name: "reshape",
    aliases: [],
    section: "array",
    summary: "Reshape An Array",
    body: r#"
## Usage
Reshapes an array from one size to another. Two seperate
syntaxes are possible.  The first syntax specifies the array
dimensions as a sequence of scalar dimensions:

```text
   y = reshape(x,d1,d2,...,dn).
```
The resulting array has the given dimensions, and is filled with
the contents of `x`.  The type of `y` is the same as `x`.

As a special case, you can specify exactly one of the dimensions
as an empty matrix `[]`, in which case FreeMat will compute the
size required in that dimension to make the reshape work.  The
syntax for this version is

```text
   y = reshape(x,d1,...,da,[],db,...,dn)
```

The second syntax specifies the array dimensions as a vector,
where each element in the vector specifies a dimension length:

```text
   y = reshape(x,[d1,d2,...,dn]).
```
This syntax is more convenient for calling `reshape` using a
variable for the argument. The
`reshape` function requires that the length of `x` equal the product
of the `di` values.
Note that arrays are stored in column format,
which means that elements in `x` are transferred to the new array
`y` starting with the first column first element, then proceeding to
the last element of the first column, then the first element of the
second column, etc.

## Example
Here are several examples of the use of `reshape` applied to
various arrays.  The first example reshapes a row vector into a
matrix.

```fm-exec
a = uint8(1:6)
reshape(a,2,3)
```

The second example reshapes a longer row vector into a volume with
two planes.

```fm-exec
a = uint8(1:12)
reshape(a,[2,3,2])
```

The third example reshapes a matrix into another matrix.

```fm-exec
a = [1,6,7;3,4,2]
reshape(a,3,2)
```
"#,
}

fm_doc::register_doc! {
    name: "rref",
    aliases: [],
    section: "array",
    summary: "Reduced Row Echelon Form of a Matrix",
    body: r#"
## Usage
Calculates the reduced row echelon form of a matrix using Gauss
Jordan elimination with partial pivoting.  The generic syntax
for `rref` is

```text
   R = rref(A)
```
A default tolerance of `max(size(A))*eps*norm(A,inf)` is used to
detect negligible column elements.  The second form of `rref`
returns a vector `k` as well as `R`

```text
  [R,k] = rref(A)
```
where `k` is a vector that correponds to the columns of `A`
used as pivot columns.  If you want to control the tolerance
used to identify negligible elements, you can use the form

```text
  [R,k] = rref(A, tolerance)
```
This implementation of `rref` is based on the one from
the matcompat lib for octave.  It is copyright Paul Kienzle,
and distributed under the GNU GPL.
"#,
}

fm_doc::register_doc! {
    name: "shiftdim",
    aliases: [],
    section: "array",
    summary: "Shift Array Dimensions Function",
    body: r#"
## Usage
The `shiftdim` function is used to shift the dimensions of an array.
The general syntax for the `shiftdim` function is

```text
   y = shiftdim(x,n)
```
where `x` is a multidimensional array, and `n` is an integer.  If
`n` is a positive integer, then `shiftdim` circularly shifts the
dimensions of `x` to the left, wrapping the dimensions around as
necessary.  If `n` is a negative integer, then `shiftdim` shifts
the dimensions of `x` to the right, introducing singleton dimensions
as necessary.  In its second form:

```text
  [y,n] = shiftdim(x)
```
the `shiftdim` function will shift away (to the left) the leading
singleton dimensions of `x` until the leading dimension is not
 a singleton dimension (recall that a singleton dimension `p` is one for
which `size(x,p) == 1`).

## Example
Here are some simple examples of using `shiftdim` to remove the singleton
dimensions of an array, and then restore them:

```fm-exec
x = uint8(10*randn(1,1,1,3,2));
[y,n] = shiftdim(x);
n
size(y)
c = shiftdim(y,-n);
size(c)
any(c~=x)
```

Note that these operations (where shifting involves only singleton dimensions)
do not actually cause data to be resorted, only the size of the arrays change.
This is not true for the following example, which triggers a call to `permute`:

```fm-exec
z = shiftdim(x,4);
```

 Note that `z` is now the transpose of `x`

```fm-exec
squeeze(x)
squeeze(z)
```
"#,
}

fm_doc::register_doc! {
    name: "sort",
    aliases: [],
    section: "array",
    summary: "Sort",
    body: r#"
## Usage
Sorts an n-dimensional array along the specified dimensional.  The first
form sorts the array along the first non-singular dimension.

```text
  B = sort(A)
```
Alternately, the dimension along which to sort can be explicitly specified

```text
  B = sort(A,dim)
```
FreeMat does not support vector arguments for `dim` - if you need `A` to be
sorted along multiple dimensions (i.e., row first, then columns), make multiple
calls to `sort`.  Also, the direction of the sort can be specified using the
`mode` argument

```text
  B = sort(A,dim,mode)
```
where `mode = 'ascend'` means to sort the data in ascending order (the default),
and `mode = 'descend'` means to sort the data into descending order.

When two outputs are requested from `sort`, the indexes are also returned.
Thus, for

```text
  [B,IX] = sort(A)
  [B,IX] = sort(A,dim)
  [B,IX] = sort(A,dim,mode)
```
an array `IX` of the same size as `A`, where `IX` records the indices of `A`
(along the sorting dimension) corresponding to the output array `B`.

Two additional issues worth noting.  First, a cell array can be sorted if each
cell contains a `string`, in which case the strings are sorted by lexical order.
The second issue is that FreeMat uses the same method as MATLAB to sort complex
numbers.  In particular, a complex number `a` is less than another complex
number `b` if `abs(a) < abs(b)`.  If the magnitudes are the same then we
test the angle of `a`, i.e. `angle(a) < angle(b)`, where `angle(a)` is the
phase of `a` between `-pi,pi`.

## Example
Here are some examples of sorting on numerical arrays.

```fm-exec
A = int32(10*rand(4,3))
[B,IX] = sort(A)
[B,IX] = sort(A,2)
[B,IX] = sort(A,1,'descend')
```

Here we sort a cell array of strings.

```fm-exec
a = {'hello','abba','goodbye','jockey','cake'}
b = sort(a)
```
"#,
}

fm_doc::register_doc! {
    name: "squeeze",
    aliases: [],
    section: "array",
    summary: "Remove Singleton Dimensions of an Array",
    body: r#"
## Usage
This function removes the singleton dimensions of an array.  The
syntax for its use is

```text
   y = squeeze(x)
```
where `x` is a multidimensional array.  Generally speaking, if
`x` is of size `d1 x 1 x d2 x ...`, then `squeeze(x)` is of
size `d1 x d2 x ...`, i.e., each dimension of `x` that was
singular (size 1) is squeezed out.

## Example
Here is a many dimensioned, ungainly array, both before and
after squeezing;

```fm-exec
x = zeros(1,4,3,1,1,2);
size(x)
y = squeeze(x);
size(y)
```
"#,
}

fm_doc::register_doc! {
    name: "subsref",
    aliases: [],
    section: "array",
    summary: "Array Dereferencing",
    body: r#"
## Usage
This function can be used to index into basic array
types (or structures).  It provides a functional interface
to execute complex indexing expressions such as
`a.b(3){5}` at run time (i.e. while executing a script or
a function) without resorting to using `eval`.  Note that
this function should be overloaded for use with user defined
classes, and that it cannot be overloaeded for base types.
The basic syntax of the function is:

```text
   b = subsref(a,s)
```
where `s` is a structure array with two fields. The
first field is
- `type`  is a string containing either `'()'` or
 `'{}'` or `'.'` depending on the form of the call.

- `subs` is a cell array or string containing the
 the subscript information.

When multiple indexing experssions are combined together
such as `b = a(5).foo{:}`, the `s` array should contain
the following entries

```text
  s(1).type = '()'  s(1).subs = {5}
  s(2).type = '.'   s(2).subs = 'foo'
  s(3).type = '{}'  s(3).subs = ':'
```
"#,
}

fm_doc::register_doc! {
    name: "trace",
    aliases: [],
    section: "array",
    summary: "Sum Diagonal Elements of an Array",
    body: r#"
## Usage

 Returns the sum of the diagonal elements of a square matrix. The general
 syntax for its use is

```text
   y = trace(x)
```
 where x is a square matrix.
"#,
}

fm_doc::register_doc! {
    name: "transpose",
    aliases: [],
    section: "array",
    summary: "Matrix Transpose",
    body: r#"
## Usage
Performs a (nonconjugate) transpose of a matrix.  The syntax for
its use is

```text
    y = transpose(x)
```
and is a synonym for `y = x.'`.

## Example
Here is an example of the transpose of a complex matrix.  Note that
the entries are not conjugated.

```fm-exec
A = [1+i,2+i;3-2*i,4+2*i]
transpose(A)
```
"#,
}

fm_doc::register_doc! {
    name: "tril",
    aliases: [],
    section: "array",
    summary: "Lower Triangular Matrix Function",
    body: r#"
## Usage

 Returns the lower triangular matrix of a square matrix. The general
 syntax for its use is

```text
   y = tril(x)
```
 where |x| is a square matrix. This returns the lower triangular matrix
 (i.e.: all cells on or above the diagonal are set to 0). You can also
 specify a different diagonal using the alternate form

```text
   y = tril(x,n)
```
 where n is the diagonal offset. In this mode, the diagonal specified
 is not set to zero in the returned matrix (e.g.: tril(x) and tril(x,-1))
 will return the same value.
"#,
}

fm_doc::register_doc! {
    name: "triu",
    aliases: [],
    section: "array",
    summary: "Upper Triangular Matrix Function",
    body: r#"
## Usage

 Returns the upper triangular matrix of a square matrix. The general
 syntax for its use is

```text
   y = triu(x)
```
 where x is a square matrix. This returns the upper triangular matrix
 (i.e.: all elements on or below the diagonal are set to 0). You can also
 specify a different diagonal using the alternate form

```text
   y = triu(x,n)
```
 where n is the diagonal offset. In this mode, the diagonal specified
 is not set to zero in the returned matrix (e.g.: tril(x) and tril(x,1))
 will return the same value.
"#,
}

fm_doc::register_doc! {
    name: "unique",
    aliases: [],
    section: "array",
    summary: "Unique",
    body: r#"
## Usage
Returns a vector containing the unique elements of an array.  The first
form is simply

```text
   y = unique(x)
```
where `x` is either a numerical array or a cell-array of strings.  The
result is sorted in increasing order.  You can also retrieve two sets
of index vectors

```text
   [y, m, n] = unique(x)
```
such that `y = x(m)` and `x = y(n)`.  If the argument `x` is a matrix,
you can also indicate that FreeMat should look for unique rows in the
matrix via

```text
   y = unique(x,'rows')
```
and

```text
   [y, m, n] = unique(x,'rows')
```

## Example
Here is an example in row mode

```fm-exec
A = randi(1,3*ones(15,3))
unique(A,'rows')
[b,m,n] = unique(A,'rows');
b
A(m,:)
b(n,:)
```

Here is an example in vector mode

```fm-exec
A = randi(1,5*ones(10,1))
unique(A)
[b,m,n] = unique(A,'rows');
b
A(m)
b(n)
```

For cell arrays of strings.

```fm-exec
A = {'hi','bye','good','tell','hi','bye'}
unique(A)
```
"#,
}

fm_doc::register_doc! {
    name: "xnrm2",
    aliases: [],
    section: "array",
    summary: "BLAS Norm Calculation",
    body: r#"
## Usage
Calculates the 2-norm of a vector.  The syntax for its use
is

```text
   y = xnrm2(A)
```
where `A` is the n-dimensional array to analyze.  This form
uses the underlying BLAS implementation to compute the 2-norm.
"#,
}

fm_doc::register_doc! {
    name: "zeros",
    aliases: [],
    section: "array",
    summary: "Array of Zeros",
    body: r#"
## Usage
Creates an array of zeros of the specified size.  Two seperate
syntaxes are possible.  The first syntax specifies the array
dimensions as a sequence of scalar dimensions:

```text
   y = zeros(d1,d2,...,dn).
```
The resulting array has the given dimensions, and is filled with
all zeros.  The type of `y` is `double`, a 64-bit floating
point array.  To get arrays of other types, use the typecast
functions (e.g., `uint8`, `int8`, etc.).  An alternative syntax
is to use the following notation:

```text
   y = zeros(d1,d2,...,dn,classname)
```
where `classname` is one of 'double', 'single', 'int8', 'uint8',
'int16', 'uint16', 'int32', 'uint32', 'int64', 'uint64', 'float', 'logical'.

The second syntax specifies the array dimensions as a vector,
where each element in the vector specifies a dimension length:

```text
   y = zeros([d1,d2,...,dn]),
```
or

```text
   y = zeros([d1,d2,...,dn],classname).
```
This syntax is more convenient for calling `zeros` using a
variable for the argument.  In both cases, specifying only one
dimension results in a square matrix output.

## Example
The following examples demonstrate generation of some zero arrays
using the first form.

```fm-exec
zeros(2,3,2)
zeros(1,3)
```

The same expressions, using the second form.

```fm-exec
zeros([2,6])
zeros([1,3])
```

Finally, an example of using the type casting function `uint16` to generate an array of 16-bit unsigned integers with zero values.

```fm-exec
uint16(zeros(3))
```

Here we use the second syntax where the class of the output is specified
explicitly

```fm-exec
zeros(3,'int16')
```
"#,
}
