//! Migrated help docs for the `binary` section (help-system P7).
//! GENERATED by `cargo xtask migrate-place` — do not edit by hand.

fm_doc::register_section! {
    id: "binary",
    title: "Bitwise Operations",
    summary: "Bitwise and binary operations on integer values.",
}

fm_doc::register_doc! {
    name: "bitand",
    aliases: [],
    section: "binary",
    summary: "Bitwise Boolean And Operation",
    body: r#"
## Usage
Performs a bitwise binary and operation on the two arguments and
returns the result.  The syntax for its use is

```text
   y = bitand(a,b)
```
where `a` and `b` are multi-dimensional unsigned integer arrays.
The and operation is performed using 32 bit unsigned intermediates.  Note that if a
or b is a scalar, then each element of the other array is and'ed with
 that scalar.  Otherwise the two arrays must match in size.

## Example

```fm-exec
bitand(uint16([1,16,255]),uint16([3,17,128]))
bitand(uint16([1,16,255]),uint16(3))
```
"#,
}

fm_doc::register_doc! {
    name: "bitcmp",
    aliases: [],
    section: "binary",
    summary: "Bitwise Boolean Complement Operation",
    body: r#"
## Usage
 Usage

 Performs a bitwise binary complement operation on the argument and
 returns the result.  The syntax for its use is

```text
    y = bitcmp(a)
```
 where a is an unsigned integer arrays.  This version of the command
 uses as many bits as required by the type of a.  For example, if
 a is an uint8 type, then the complement is formed using 8 bits.
 The second form of bitcmp allows you to specify the number of bits
 to use,

```text
    y = bitcmp(a,n)
```
 in which case the complement is taken with respect to n bits, where n must be
 less than the length of the integer type.

## Example

```fm-exec
bitcmp(uint16(2^14-2))
bitcmp(uint16(2^14-2),14)
```
"#,
}

fm_doc::register_doc! {
    name: "bitor",
    aliases: [],
    section: "binary",
    summary: "Bitwise Boolean Or Operation",
    body: r#"
## Usage
Performs a bitwise binary or operation on the two arguments and
returns the result.  The syntax for its use is

```text
   y = bitor(a,b)
```
where `a` and `b` are multi-dimensional unsigned integer arrays.
The and operation is performed using 32 bit unsigned intermediates.  Note that if a
or b is a scalar, then each element of the other array is or'ed with
that scalar.  Otherwise the two arrays must match in size.

## Example

```fm-exec
bitand(uint16([1,16,255]),uint16([3,17,128]))
bitand(uint16([1,16,255]),uint16(3))
```
"#,
}

fm_doc::register_doc! {
    name: "bitxor",
    aliases: [],
    section: "binary",
    summary: "Bitwise Boolean Exclusive-Or (XOR) Operation",
    body: r#"
## Usage
Performs a bitwise binary xor operation on the two arguments and
returns the result.  The syntax for its use is

```text
   y = bitxor(a,b)
```
where `a` and `b` are multi-dimensional unsigned integer arrays.
The and operation is performed using 32 bit unsigned intermediates.  Note that if a
or b is a scalar, then each element of the other array is xor'ed with
 that scalar.  Otherwise the two arrays must match in size.

## Example

```fm-exec
bitand(uint16([1,16,255]),uint16([3,17,128]))
bitand(uint16([1,16,255]),uint16(3))
```
"#,
}
