//! Migrated help docs for the `class` section (help-system P7).
//! GENERATED by `cargo xtask migrate-place` — do not edit by hand.

fm_doc::register_section! {
    id: "class",
    title: "Object Oriented Programming",
    summary: "Object-oriented programming: classes, methods, and dispatch.",
}

fm_doc::register_doc! {
    name: "and",
    aliases: [],
    section: "class",
    summary: "Overloaded Logical And Operator",
    body: r#"
## Usage
This is a method that is invoked to combine two variables using a
logical and operator, and is invoked when you call

```text
   c = and(a,b)
```
or for

```text
   c = a & b
```
"#,
}

fm_doc::register_doc! {
    name: "cat",
    aliases: [],
    section: "class",
    summary: "Concatenation of Arrays",
    body: r#"
## Usage
This function concatenates arrays in a given
dimension.  The syntax for its use is

```text
   cat (DIM, A, B)
   cat (DIM, A, B, C ...)
```
to return the concatenation along the dimension `DIM` of all arguments.
`cat(1, A, B, C)` is the same as `[A; B; C]` or `vertcat(A, B, C)`.
`cat(2, A, B, C)` is the same as `[A, B, C]` or `horzcat(A, B, C)`.
"#,
}

fm_doc::register_doc! {
    name: "class",
    aliases: [],
    section: "class",
    summary: "Class Support Function",
    body: r#"
## Usage
There are several uses for the `class` function.  The first
version takes a single argument, and returns the class of
that variable.  The syntax for this form is

```text
  classname = class(variable)
```
and it returns a string containing the name of the class for
`variable`.  The second form of the class function is used
to construct an object of a specific type based on a structure
which contains data elements for the class.  The syntax for
this version is

```text
  classvar = class(template, classname, parent1, parent2,...)
```
This should be called inside the constructor for the class.
The resulting class will be of the type `classname`, and will
be derived from `parent1`, `parent2`, etc.  The `template`
argument should be a structure array that contains the members
of the class.  See the `constructors` help for some details
on how to use the `class` function.  Note that if the
`template` argument is an empty structure matrix, then the
resulting variable has no fields beyond those inherited from
the parent classes.
"#,
}

fm_doc::register_doc! {
    name: "colon",
    aliases: [],
    section: "class",
    summary: "Overloaded Colon Operator",
    body: r#"
## Usage
This is a method that is invoked in one of two forms, either
the two argument version

```text
  c = colon(a,b)
```
which is also called using the notation

```text
  c = a:b
```
and the three argument version

```text
  d = colon(a,b,c)
```
which is also called using the notation

```text
  d = a:b:c
```
"#,
}

fm_doc::register_doc! {
    name: "constructors",
    aliases: [],
    section: "class",
    summary: "Class Constructors",
    body: r#"
## Usage
When designing a constructor for a FreeMat class, you should
design the constructor to take a certain form.  The following
is the code for the sample `mat` object

```text
function p = mat(a)
  if (nargin == 0)
    p.c = [];
    p = class(p,'mat');
  elseif isa(a,'mat')
    p = a;
  else
    p.c = a;
    p = class(p,'mat');
  end
```
Generally speaking when it is provided with zero arguments, the
constructor returns a default version of the class using a template
structure with the right fields populated with default values.  If
the constructor is given a single argument that matches the class
we are trying to construct, the constructor passes through the
argument.  This form of the constructor is used for type conversion.
In particular,

```text
   p = mat(a)
```
guarantees that `p` is an array of class `mat`.  The last form
of the constructor builds a class object given the input.  The
meaning of this form depends on what makes sense for your class.
For example, for a polynomial class, you may want to pass in the
coefficients of the polynomial.
"#,
}

fm_doc::register_doc! {
    name: "ctranspose",
    aliases: [],
    section: "class",
    summary: "Overloaded Conjugate Transpose Operator",
    body: r#"
## Usage
This is a method that is invoked when a variable has the
conjugate transpose operator method applied, and is invoked
when you call

```text
   c = ctranspose(a)
```
or

```text
/  c = a'
```
"#,
}

fm_doc::register_doc! {
    name: "eq",
    aliases: [],
    section: "class",
    summary: "Overloaded Equals Comparison Operator",
    body: r#"
## Usage
This is a method that is invoked to combine two variables using an
equals comparison operator, and is invoked when you call

```text
   c = eq(a,b)
```
or for

```text
   c = a == b
```
"#,
}

fm_doc::register_doc! {
    name: "ge",
    aliases: [],
    section: "class",
    summary: "Overloaded Greater-Than-Equals Comparison Operator",
    body: r#"
## Usage
This is a method that is invoked to combine two variables using a
greater than or equals comparison operator, and is invoked when you call

```text
   c = ge(a,b)
```
or for

```text
   c = a >= b
```
"#,
}

fm_doc::register_doc! {
    name: "gt",
    aliases: [],
    section: "class",
    summary: "Overloaded Greater Than Comparison Operator",
    body: r#"
## Usage
This is a method that is invoked to combine two variables using a
greater than comparison operator, and is invoked when you call

```text
   c = gt(a,b)
```
or for

```text
   c = a > b
```
"#,
}

fm_doc::register_doc! {
    name: "horzcat",
    aliases: [],
    section: "class",
    summary: "Overloaded Horizontal Concatenation",
    body: r#"
## Usage
This is a method for a class that is invoked to concatenate two or more
variables of the same class type together.  Besides being called
when you invoke

```text
   c = horzcat(a,b,c)
```
when `a` is a class, it is also called for

```text
   c = [a,b,c]
```
when one of these variables is a class.  The exact meaning of
horizontal concatenation depends on the class you have designed.
"#,
}

fm_doc::register_doc! {
    name: "ldivide",
    aliases: [],
    section: "class",
    summary: "Overloaded Left Divide Operator",
    body: r#"
## Usage
This is a method that is invoked when two variables are divided
and is invoked when you call

```text
   c = ldivide(a,b)
```
or for

```text
   c = a .\ b
```
"#,
}

fm_doc::register_doc! {
    name: "le",
    aliases: [],
    section: "class",
    summary: "Overloaded Less-Than-Equals Comparison Operator",
    body: r#"
## Usage
This is a method that is invoked to compare two variables using a
less than or equals comparison operator, and is invoked when you call

```text
   c = le(a,b)
```
or for

```text
   c = a <= b
```
"#,
}

fm_doc::register_doc! {
    name: "lt",
    aliases: [],
    section: "class",
    summary: "Overloaded Less Than Comparison Operator",
    body: r#"
## Usage
This is a method that is invoked to compare two variables using a
less than comparison operator, and is invoked when you call

```text
   c = lt(a,b)
```
or for

```text
   c = a < b
```
"#,
}

fm_doc::register_doc! {
    name: "minus",
    aliases: [],
    section: "class",
    summary: "Overloaded Addition Operator",
    body: r#"
## Usage
This is a method that is invoked when two variables are subtracted
and is invoked when you call

```text
   c = minus(a,b)
```
or for

```text
   c = a - b
```
"#,
}

fm_doc::register_doc! {
    name: "mldivide",
    aliases: [],
    section: "class",
    summary: "Overloaded Matrix Left Divide Operator",
    body: r#"
## Usage
This is a method that is invoked when two variables are divided
using the matrix (left) divide operator, and is invoked when
you call

```text
   c = mldivide(a,b)
```
or for

```text
   c = a \ b
```
"#,
}

fm_doc::register_doc! {
    name: "mpower",
    aliases: [],
    section: "class",
    summary: "Overloaded Matrix Power Operator",
    body: r#"
## Usage
This is a method that is invoked when one variable is raised
to another variable using the matrix power operator, and
is invoked when you call

```text
  c = mpower(a,b)
```
or

```text
  c = a^b
```
"#,
}

fm_doc::register_doc! {
    name: "mrdivide",
    aliases: [],
    section: "class",
    summary: "Overloaded Matrix Right Divide Operator",
    body: r#"
## Usage
This is a method that is invoked when two variables are divided
using the matrix divide operator, and is invoked when you call

```text
   c = mrdivide(a,b)
```
or for

```text
   c = a / b
```
"#,
}

fm_doc::register_doc! {
    name: "mtimes",
    aliases: [],
    section: "class",
    summary: "Overloaded Matrix Multiplication Operator",
    body: r#"
## Usage
This is a method that is invoked when two variables are multiplied
using the matrix operator and is invoked when you call

```text
   c = mtimes(a,b)
```
or for

```text
   c = a * b
```
"#,
}

fm_doc::register_doc! {
    name: "ne",
    aliases: [],
    section: "class",
    summary: "Overloaded Not-Equals Comparison Operator",
    body: r#"
## Usage
This is a method that is invoked to combine two variables using a
not-equals comparison operator, and is invoked when you call

```text
   c = ne(a,b)
```
or for

```text
   c = a != b
```
"#,
}

fm_doc::register_doc! {
    name: "not",
    aliases: [],
    section: "class",
    summary: "Overloaded Logical Not Operator",
    body: r#"
## Usage
This is a method that is invoked when a variable is logically
inverted, and is invoked when you call

```text
   c = not(a)
```
or for

```text
   c = ~a
```
"#,
}

fm_doc::register_doc! {
    name: "or",
    aliases: [],
    section: "class",
    summary: "Overloaded Logical Or Operator",
    body: r#"
## Usage
This is a method that is invoked to combine two variables using a
logical or operator, and is invoked when you call

```text
   c = or(a,b)
```
or for

```text
   c = a | b
```
"#,
}

fm_doc::register_doc! {
    name: "plus",
    aliases: [],
    section: "class",
    summary: "Overloaded Addition Operator",
    body: r#"
## Usage
This is a method that is invoked when two variables are added
and is invoked when you call

```text
   c = plus(a,b)
```
or for

```text
   c = a + b
```
"#,
}

fm_doc::register_doc! {
    name: "power",
    aliases: [],
    section: "class",
    summary: "Overloaded Power Operator",
    body: r#"
## Usage
This is a method that is invoked when one variable is raised
to another variable using the dot-power operator, and is
invoked when you call

```text
   c = power(a,b)
```
or

```text
   c = a.^b
```
"#,
}

fm_doc::register_doc! {
    name: "rdivide",
    aliases: [],
    section: "class",
    summary: "Overloaded Right Divide Operator",
    body: r#"
## Usage
This is a method that is invoked when two variables are divided
and is invoked when you call

```text
   c = rdivide(a,b)
```
or for

```text
   c = a ./ b
```
"#,
}

fm_doc::register_doc! {
    name: "subsasgn",
    aliases: [],
    section: "class",
    summary: "Overloaded Class Assignment",
    body: r#"
## Usage
This method is called for expressions of the form

```text
  a(b) = c, a{b} = c, a.b = c
```
and overloading the `subsasgn` method can allow you
to define the meaning of these expressions for
objects of class `a`.  These expressions are mapped
to a call of the form

```text
  a = subsasgn(a,s,b)
```
where `s` is a structure array with two fields.  The
first field is
- `type`  is a string containing either `'()'` or
 `'{}'` or `'.'` depending on the form of the call.

- `subs` is a cell array or string containing the
 the subscript information.

When multiple indexing experssions are combined together
such as `a(5).foo{:} = b`, the `s` array contains
the following entries

```text
  s(1).type = '()'  s(1).subs = {5}
  s(2).type = '.'   s(2).subs = 'foo'
  s(3).type = '{}'  s(3).subs = ':'
```
"#,
}

fm_doc::register_doc! {
    name: "subsindex",
    aliases: [],
    section: "class",
    summary: "Overloaded Class Indexing",
    body: r#"
## Usage
This method is called for classes in the expressions
of the form

```text
  c = subsindex(a)
```
where `a` is an object, and `c` is an index vector.
It is also called for

```text
  c = b(a)
```
in which case `subsindex(a)` must return a vector containing
integers between `0` and `N-1` where `N` is the number
of elements in the vector `b`.
"#,
}

fm_doc::register_doc! {
    name: "times",
    aliases: [],
    section: "class",
    summary: "Overloaded Multiplication Operator",
    body: r#"
## Usage
This is a method that is invoked when two variables are multiplied
and is invoked when you call

```text
   c = times(a,b)
```
or for

```text
   c = a .* b
```
"#,
}

fm_doc::register_doc! {
    name: "uminus",
    aliases: [],
    section: "class",
    summary: "Overloaded Unary Minus Operator",
    body: r#"
## Usage
This is a method that is invoked when a variable is negated,
and is invoked when you call

```text
   c = uminus(a)
```
or for

```text
   c = -a
```
"#,
}

fm_doc::register_doc! {
    name: "uplus",
    aliases: [],
    section: "class",
    summary: "Overloaded Unary Plus Operator",
    body: r#"
## Usage
This is a method that is invoked when a variable is preceeded by a "+",
and is invoked when you call

```text
   c = uplus(a)
```
or for

```text
   c = +a
```
"#,
}

fm_doc::register_doc! {
    name: "vertcat",
    aliases: [],
    section: "class",
    summary: "Overloaded Vertical Concatenation",
    body: r#"
## Usage
This is a method for a class that is invoked to concatenate two or more
variables of the same class type together.  Besides being called when
you invoke

```text
   c = vertcat(a,b,c)
```
when `a` is a class, it is also called for

```text
   c = [a;b;c]
```
when one of the variables is a class.  The exact meaning of
vertical concatenation depends on the class you have designed.
"#,
}
