//! Migrated help docs for the `curvefit` section (help-system P7).
//! GENERATED by `cargo xtask migrate-place` — do not edit by hand.

fm_doc::register_section! {
    id: "curvefit",
    title: "Optimization and Curve Fitting",
    summary: "Optimization, root-finding, and curve-fitting routines.",
}

fm_doc::register_doc! {
    name: "fitfun",
    aliases: [],
    section: "curvefit",
    summary: "Fit a Function",
    body: r#"
## Usage
Fits `n` (non-linear) functions of `m` variables using least squares
and the Levenberg-Marquardt algorithm.  The general syntax for its usage
is

```text
  [xopt,yopt] = fitfun(fcn,xinit,y,weights,tol,params...)
```
Where `fcn` is the name of the function to be fit, `xinit` is the
initial guess for the solution (required), `y` is the right hand side,
i.e., the vector `y` such that:

$$
   xopt = \arg \min_{x} \|\mathrm{diag}(weights)*(f(x) - y)\|_2^2,
$$
the output `yopt` is the function `fcn` evaluated at `xopt`.
The vector `weights` must be the same size as `y`, and contains the
relative weight to assign to an error in each output value.  Generally,
the ith weight should reflect your confidence in the ith measurement.
The parameter `tol` is the tolerance used for convergence.
The function `fcn` must return a vector of the same size as `y`,
and `params` are passed to `fcn` after the argument `x`, i.e.,

$$
  y = fcn(x,param1,param2,...).
$$
Note that both `x` and `y` (and the output of the function) must all
be real variables.  Complex variables are not handled yet.
"#,
}

fm_doc::register_doc! {
    name: "gausfit",
    aliases: [],
    section: "curvefit",
    summary: "Gaussian Curve Fit",
    body: r#"
## Usage
The `gausfit` routine has the following syntax

```text
  [mu,sigma,dc,gain,yhat] = gausfit(t,y,w,mug,sigmag,dcg,gaing).
```
where the required inputs are
- `t` - the values of the independant variable (e.g., time samples)

- `y` - the values of the dependant variable (e.g., f(t))

The following inputs are all optional, and default values are
available for each of them.
- `w` - the weights to use in the fitting (set to ones if omitted)

- `mug` - initial estimate of the mean

- `sigmag` - initial estimate of the sigma (standard deviation)

- `dcg` - initial estimate of the DC value

- `gaing` - initial estimate of the gain

The fit is of the form `yhat=gain*exp((t-mu).^2/(2*sigma^2))+dc`.
The outputs are
- `mu` - the mean of the fit

- `sigma` - the sigma of the fit

- `dc` - the dc term of the fit

- `gain` - the gain of the gaussian fit

- `yhat` - the output samples (the Gaussian fits)

Because the fit is nonlinear, a good initial guess is critical to
convergence of the solution.  Thus, you can supply initial guesses
for each of the parameters using the `mug`, `sigmag`, `dcg`,
`gaing` arguments.  Any arguments not supplied are estimated using
a simple algorithm. In particular, the DC value is estimated by
taking the minimum value  from the vector `y`.  The gain is
estimated from the range of `y`.  The mean and standard deviation
are estimated using the first and second order moments of `y`.
This function uses `fitfun`.

## Example
Suppose we want to fit a cycle of a cosine using a Gaussian shape.

```fm
t = linspace(-pi,pi); 
y = cos(t);
[mu,sigma,dc,gain,yhat] = gausfit(t,y);
plot(t,y,'rx',t,yhat,'g-');
mprint gausfit1
```

Which results in the following plot
"#,
}

fm_doc::register_doc! {
    name: "interp2",
    aliases: [],
    section: "curvefit",
    summary: "2-D Interpolation",
    body: r#"
## Usage
Given a set of monotonically increasing `x` coordinates and a
corresponding set of `y` values, performs simple linear
interpolation to a new set of `x` coordinates. The general syntax
for its usage is

```text
   zi = interp2(z,xi,yi)
```
where `xi` and `yi` are vectors of the same length. The output
vector `zi` is the same size as the input vector `xi`.
For each element of `xi`, the values in `zi` are linearly interpolated
by default. Interpolation method can be selected as:

```text
   zi = interp2(z,xi,yi,method)
```
Default interpolation method is `'linear'`. Other methods are
 `'nearest'`, and `'cubic'`.
For values in `xi, yi` that are outside the size of `z`,
the default value returned is NaN.  To change this behavior,
you can specify the extrapolation value:

```text
   zi = interp2(z,xi,yi,method,extrapval)
```
The `z` and `xi,yi` vectors must be real, although complex types
are allowed for `z`.
"#,
}

fm_doc::register_doc! {
    name: "interplin1",
    aliases: [],
    section: "curvefit",
    summary: "Linear 1-D Interpolation",
    body: r#"
## Usage
Given a set of monotonically increasing `x` coordinates and a
corresponding set of `y` values, performs simple linear
interpolation to a new set of `x` coordinates. The general syntax
for its usage is

```text
   yi = interplin1(x1,y1,xi)
```
where `x1` and `y1` are vectors of the same length, and the entries
in `x1` are monotoniccally increasing.  The output vector `yi` is
the same size as the input vector `xi`.  For each element of `xi`,
the values in `y1` are linearly interpolated.  For values in `xi`
that are outside the range of `x1` the default value returned is
`nan`.  To change this behavior, you can specify the extrapolation
flag:

```text
   yi = interplin1(x1,y1,xi,extrapflag)
```
Valid options for `extrapflag` are:
- `'nan'` - extrapolated values are tagged with `nan`s

- `'zero'` - extrapolated values are set to zero

- `'endpoint'` - extrapolated values are set to the endpoint values

- `'extrap'` - linear extrapolation is performed

The `x1` and `xi` vectors must be real, although complex types
are allowed for `y1`.

## Example
Here is an example of simple linear interpolation with the different
extrapolation modes.  We start with a fairly coarse sampling of a
cosine.

```fm
x = linspace(-pi*7/8,pi*7/8,15);
y = cos(x);
plot(x,y,'ro');
mprint interplin1_1
```

which is shown here
Next, we generate a finer sampling over a slightly broader range
(in this case `[-pi,pi]`).  First, we demonstrate the `'nan'`
extrapolation method

```fm
xi = linspace(-4,4,100);
yi_nan = interplin1(x,y,xi,'nan');
yi_zero = interplin1(x,y,xi,'zero');
yi_endpoint = interplin1(x,y,xi,'endpoint');
yi_extrap = interplin1(x,y,xi,'extrap');
plot(x,y,'ro',xi,yi_nan,'g-x',xi,yi_zero,'g-x',xi,yi_endpoint,'g-x',xi,yi_extrap,'g-x');
mprint interplin1_2
```

which is shown here
"#,
}

fm_doc::register_doc! {
    name: "poly",
    aliases: [],
    section: "curvefit",
    summary: "Convert Roots To Polynomial Coefficients",
    body: r#"
## Usage
This function calculates the polynomial coefficients for given roots

```text
    p = poly(r)
```
when `r` is a vector, is a vector whose elements are the coefficients
of the polynomial whose roots are the elements of `r`.  Alternately,
you can provide a matrix

```text
    p = poly(A)
```
when `A` is an `N x N` square matrix, is a row vector with
`N+1` elements which are the coefficients of the
characteristic polynomial, `det(lambda*eye(size(A))-A)`.

Contributed by Paulo Xavier Candeias under GPL.

## Example
Here are some examples of the use of `poly`

```fm-exec
A = [1,2,3;4,5,6;7,8,0]
p = poly(A)
r = roots(p)
```
"#,
}

fm_doc::register_doc! {
    name: "polyder",
    aliases: [],
    section: "curvefit",
    summary: "Polynomial Coefficient Differentiation",
    body: r#"
## Usage
The `polyder` function returns the polynomial coefficients resulting
from differentiation of polynomial `p`. The syntax for its use is either

```text
 pder = polyder(p)
```
 for the derivitave of polynomial p, or

```text
 convp1p2der = polyder(p1,p2)
```
 for the derivitave of polynomial conv(p1,p2), or still

```text
 [nder,dder] = polyder(n,d)
```
for the derivative of polynomial `n/d` (`nder` is the numerator
and `dder` is the denominator). In all cases the polynomial
coefficients are assumed to be in decreasing degree.
Contributed by Paulo Xavier Candeias under GPL

## Example
Here are some examples of the use of `polyder`

```fm-exec
polyder([2,3,4])
```

```fm-exec
polyder([2,3,4],7)
```

```fm-exec
[n,d] = polyder([2,3,4],5)
```
"#,
}

fm_doc::register_doc! {
    name: "polyfit",
    aliases: [],
    section: "curvefit",
    summary: "Fit Polynomial To Data",
    body: r#"
## Usage
The `polyfit` routine has the following syntax

```text
  p = polyfit(x,y,n)
```
where `x` and `y` are vectors of the same size, and
`n` is the degree of the approximating polynomial.
The resulting vector `p` forms the coefficients of
the optimal polynomial (in descending degree) that fit
`y` with `x`.

## Function Internals
The `polyfit` routine finds the approximating polynomial

$$
   p(x) = p_1 x^n + p_2 x^{n-1} + \dots + p_n x + p_{n+1}
$$
such that

$$
   \sum_{i} (p(x_i) - y_i)^2
$$
is minimized.  It does so by forming the Vandermonde matrix
and solving the resulting set of equations using the backslash
operator.  Note that the Vandermonde matrix can become poorly
conditioned with large `n` quite rapidly.

## Example
A classic example from Edwards and Penny, consider the problem
of approximating a sinusoid with a polynomial.  We start with
a vector of points evenly spaced on the unit interval, along with
a vector of the sine of these points.

```fm
x = linspace(0,1,20);
y = sin(2*pi*x);
plot(x,y,'r-')
mprint polyfit1
```

The resulting plot is shown here
Next, we fit a third degree polynomial to the sine, and use
`polyval` to plot it

```fm
p = polyfit(x,y,3)
f = polyval(p,x);
plot(x,y,'r-',x,f,'ko');
mprint polyfit2
```

The resulting plot is shown here
Increasing the order improves the fit, as

```fm
p = polyfit(x,y,11)
f = polyval(p,x);
plot(x,y,'r-',x,f,'ko');
mprint polyfit3
```

The resulting plot is shown here
"#,
}

fm_doc::register_doc! {
    name: "polyint",
    aliases: [],
    section: "curvefit",
    summary: "Polynomial Coefficient Integration",
    body: r#"
## Usage
 The polyint function returns the polynomial coefficients resulting
 from integration of polynomial p. The syntax for its use is either

```text
 pint = polyint(p,k)
```
 or, for a default `k = 0`,

```text
 pint = polyint(p);
```
 where `p` is a vector of polynomial coefficients assumed to be in
 decreasing degree and `k` is the integration constant.
 Contributed by Paulo Xavier Candeias under GPL

## Example
Here is are some examples of the use of `polyint`.

```fm-exec
polyint([2,3,4])
```

And

```fm-exec
polyint([2,3,4],5)
```
"#,
}

fm_doc::register_doc! {
    name: "polyval",
    aliases: [],
    section: "curvefit",
    summary: "Evaluate Polynomial Fit at Selected Points",
    body: r#"
## Usage
The `polyval` routine has the following syntax

```text
  y = polyval(p,x)
```
where `p` is a vector of polynomial coefficients,
in decreasing degree (as generated by `polyfit`, for example).
If `x` is a matrix, the polynomial is evaluated in the matrix
sense (in which case `x` must be square).

## Function Internals
The polynomial is evaluated using a recursion method.  If the
polynomial is

$$
   p(x) = p_1 x^n + p_2 x^{n-1} + \dots + p_n x + p_{n+1}
$$
then the calculation is performed as

$$
   p(x) = ((p_1) x + p_2) x + p_3
$$

## Example
Here is a plot of `x^3` generated using polyval

```fm
p = [1 0 0 0]
x = linspace(-1,1);
y = polyval(p,x);
plot(x,y,'r-')
mprint polyval1
```

Here is the resulting plot
"#,
}

fm_doc::register_doc! {
    name: "roots",
    aliases: [],
    section: "curvefit",
    summary: "Find Roots of Polynomial",
    body: r#"
## Usage
The `roots` routine will return a column vector containing the
roots of a polynomial.  The general syntax is

```text
   z = roots(p)
```
where `p` is a vector containing the coefficients of the polynomial
ordered in descending powers.

## Function Internals
Given a vector

$$
   [p_1, p_2, \dots p_n]
$$
which describes a polynomial

$$
   p_1 x^{n-1} + p_2 x^{n-2} + \dots + p_n
$$
we construct the companion matrix (which has a characteristic polynomial
matching the polynomial described by `p`), and then find the eigenvalues
of it (which are the roots of its characteristic polynomial), and
which are also the roots of the polynomial of interest.  This technique
for finding the roots is described in the help page for `roots` on the Mathworks
website.

## Example
Here is an example of finding the roots to the polynomial

$$
   x^3 - 6x^2 - 72x - 27
$$

```fm-exec
roots([1 -6 -72 -27])
```
"#,
}
