//! Migrated help docs for the `debug` section (help-system P7).
//! GENERATED by `cargo xtask migrate-place` — do not edit by hand.

fm_doc::register_section! {
    id: "debug",
    title: "Debugging FreeMat Code",
    summary: "Debugging, breakpoints, and execution inspection.",
}

fm_doc::register_doc! {
    name: "dbauto",
    aliases: [],
    section: "debug",
    summary: "Control Dbauto Functionality",
    body: r#"
## Usage
The dbauto functionality in FreeMat allows you to debug your
FreeMat programs.  When `dbauto` is `on`, then any error
that occurs while the program is running causes FreeMat to
stop execution at that point and return you to the command line
(just as if you had placed a `keyboard` command there).  You can
then examine variables, modify them, and resume execution using
`return`.  Alternately, you can exit out of all running routines
via a `retall` statement.  Note that errors that occur inside of
`try`/`catch` blocks do not (by design) cause auto breakpoints.  The
`dbauto` function toggles the dbauto state of FreeMat.  The
syntax for its use is

```text
   dbauto(state)
```
where `state` is either

```text
   dbauto('on')
```
to activate dbauto, or

```text
   dbauto('off')
```
to deactivate dbauto.  Alternately, you can use FreeMat's string-syntax
equivalence and enter

```text
   dbauto on
```
or

```text
   dbauto off
```
to turn dbauto on or off (respectively).  Entering `dbauto` with no arguments
returns the current state (either 'on' or 'off').
"#,
}

fm_doc::register_doc! {
    name: "dbdelete",
    aliases: [],
    section: "debug",
    summary: "Delete a Breakpoint",
    body: r#"
## Usage
The `dbdelete` function deletes a breakpoint.  The syntax
for the `dbdelete` function is

```text
  dbdelete(num)
```
where `num` is the number of the breakpoint to delete.
"#,
}

fm_doc::register_doc! {
    name: "dbdown",
    aliases: [],
    section: "debug",
    summary: "Move Down One Debug Level",
    body: r#"
## Usage
The `dbdown` function moves up one level in the debug
hierarchy.  The syntax for the `dbdown` function is

```text
 dbdown
```
"#,
}

fm_doc::register_doc! {
    name: "dblist",
    aliases: [],
    section: "debug",
    summary: "List Breakpoints",
    body: r#"
## Usage
List the current set of breakpoints.  The syntax for the
`dblist` is simply

```text
  dblist
```
"#,
}

fm_doc::register_doc! {
    name: "dbstep",
    aliases: [],
    section: "debug",
    summary: "Step N Statements",
    body: r#"
## Usage
Step `N` statements during debug mode.  The synax for this is
either

```text
  dbstep(N)
```
to step `N` statements, or

```text
  dbstep
```
to step one statement.
"#,
}

fm_doc::register_doc! {
    name: "dbstop",
    aliases: [],
    section: "debug",
    summary: "",
    body: r#"
## Usage
Set a breakpoint.  The syntax for this is:

```text
  dbstop(funcname,linenumber)
```
where `funcname` is the name of the function where we want
to set the breakpoint, and `linenumber` is the line number.
"#,
}

fm_doc::register_doc! {
    name: "dbup",
    aliases: [],
    section: "debug",
    summary: "Move Up One Debug Level",
    body: r#"
## Usage
The `dbup` function moves up one level in the debug
hierarchy.  The syntax for the `dbup` function is

```text
 dbup
```
"#,
}

fm_doc::register_doc! {
    name: "fdump",
    aliases: [],
    section: "debug",
    summary: "Dump Information on Function",
    body: r#"
## Usage
Dumps information about a function (diagnostic information only)

```text
   fdump fname
```
"#,
}
