//! Migrated help docs for the `elementary` section (help-system P7).
//! GENERATED by `cargo xtask migrate-place` — do not edit by hand.

fm_doc::register_section! {
    id: "elementary",
    title: "Elementary Functions",
    summary: "Elementary mathematical functions on arrays.",
}

fm_doc::register_doc! {
    name: "abs",
    aliases: [],
    section: "elementary",
    summary: "Absolute Value Function",
    body: r#"
## Usage
Returns the absolute value of the input array for all elements.  The
general syntax for its use is

```text
   y = abs(x)
```
where `x` is an `n`-dimensional array of numerical type.  The output
is the same numerical type as the input, unless the input is `complex`
or `dcomplex`.  For `complex` inputs, the absolute value is a floating
point array, so that the return type is `float`.  For `dcomplex`
inputs, the absolute value is a double precision floating point array, so that
the return type is `double`.

## Example
The following demonstrates the `abs` applied to a complex scalar.

```fm-exec
abs(3+4*i)
```

The `abs` function applied to integer and real values:

```fm-exec
abs([-2,3,-4,5])
```

For a double-precision complex array,

```fm-exec
abs([2.0+3.0*i,i])
```
"#,
}

fm_doc::register_doc! {
    name: "all",
    aliases: [],
    section: "elementary",
    summary: "All True Function",
    body: r#"
## Usage
Reduces a logical array along a given dimension by testing for all
logical 1s.  The general
syntax for its use is

```text
  y = all(x,d)
```
where `x` is an `n`-dimensions array of `logical` type.
The output is of `logical` type.  The argument `d` is
optional, and denotes the dimension along which to operate.
The output `y` is the same size as `x`, except that it is
singular along the operated direction.  So, for example,
if `x` is a `3 x 3 x 4` array, and we `all` operation along
dimension `d=2`, then the output is of size `3 x 1 x 4`.

## Function Internals
The output is computed via

$$
y(m_1,\ldots,m_{d-1},1,m_{d+1},\ldots,m_{p}) =
\min_{k} x(m_1,\ldots,m_{d-1},k,m_{d+1},\ldots,m_{p})
$$
If `d` is omitted, then the minimum is taken over all elements of
`x`.

## Example
The following piece of code demonstrates various uses of the `all`
function

```fm-exec
A = [1,0,0;1,0,0;0,0,1]
```

We start by calling `all` without a dimension argument, in which
case it defaults to testing all values of `A`

```fm-exec
all(A)
```

The `all` function is useful in expressions also.

```fm-exec
all(A>=0)
```

Next, we apply the `all` operation along the rows.

```fm-exec
all(A,2)
```
"#,
}

fm_doc::register_doc! {
    name: "any",
    aliases: [],
    section: "elementary",
    summary: "Any True Function",
    body: r#"
## Usage
Reduces a logical array along a given dimension by testing for any
logical 1s.  The general
syntax for its use is

```text
  y = any(x,d)
```
where `x` is an `n`-dimensions array of `logical` type.
The output is of `logical` type.  The argument `d` is
optional, and denotes the dimension along which to operate.
The output `y` is the same size as `x`, except that it is
singular along the operated direction.  So, for example,
if `x` is a `3 x 3 x 4` array, and we `any` operation along
dimension `d=2`, then the output is of size `3 x 1 x 4`.

## Function Internals
The output is computed via

$$
y(m_1,\ldots,m_{d-1},1,m_{d+1},\ldots,m_{p}) =
\max_{k} x(m_1,\ldots,m_{d-1},k,m_{d+1},\ldots,m_{p})
$$
If `d` is omitted, then the summation is taken along the
first non-singleton dimension of `x`.

## Example
The following piece of code demonstrates various uses of the summation
function

```fm-exec
A = [1,0,0;1,0,0;0,0,1]
```

We start by calling `any` without a dimension argument, in which
case it defaults to the first nonsingular dimension (in this case,
along the columns or `d = 1`).

```fm-exec
any(A)
```

Next, we apply the `any` operation along the rows.

```fm-exec
any(A,2)
```
"#,
}

fm_doc::register_doc! {
    name: "ceil",
    aliases: [],
    section: "elementary",
    summary: "Ceiling Function",
    body: r#"
## Usage
Computes the ceiling of an n-dimensional array elementwise.  The
ceiling of a number is defined as the smallest integer that is
larger than or equal to that number. The general syntax for its use
is

```text
   y = ceil(x)
```
where `x` is a multidimensional array of numerical type.  The `ceil`
function preserves the type of the argument.  So integer arguments
are not modified, and `float` arrays return `float` arrays as
outputs, and similarly for `double` arrays.  The `ceil` function
is not defined for `complex` or `dcomplex` types.

## Example
The following demonstrates the `ceil` function applied to various
(numerical) arguments.  For integer arguments, the ceil function has
no effect:

```fm-exec
ceil(3)
ceil(-3)
```

Next, we take the `ceil` of a floating point value:

```fm-exec
ceil(float(3.023))
ceil(float(-2.341))
```

Note that the return type is a `float` also.  Finally, for a `double`
type:

```fm-exec
ceil(4.312)
ceil(-5.32)
```
"#,
}

fm_doc::register_doc! {
    name: "conj",
    aliases: [],
    section: "elementary",
    summary: "Conjugate Function",
    body: r#"
## Usage
Returns the complex conjugate of the input array for all elements.  The
general syntax for its use is

```text
   y = conj(x)
```
where `x` is an `n`-dimensional array of numerical type.  The output
is the same numerical type as the input.  The `conj` function does
nothing to real and integer types.

## Example
The following demonstrates the complex conjugate applied to a complex scalar.

```fm-exec
conj(3+4*i)
```

The `conj` function has no effect on real arguments:

```fm-exec
conj([2,3,4])
```

For a double-precision complex array,

```fm-exec
conj([2.0+3.0*i,i])
```
"#,
}

fm_doc::register_doc! {
    name: "cov",
    aliases: [],
    section: "elementary",
    summary: "Covariance Matrix",
    body: r#"
## Usage
Computes the covariance of a matrix or a vector.  The general
syntax for its use is

```text
  y = cov(x)
```
where `x` is a matrix or a vector.  If `x` is a vector then
`cov` returns the variance of `x`.  If `x` is a matrix then
`cov` returns the covariance matrix of the columns of `x`.
You can also call `cov` with two arguments to compute the
matrix of cross correlations.  The syntax for this mode is

```text
  y = cov(x,z)
```
where `x` and `z` are matrices of the same size.  Finally,
you can provide a normalization flag `d` that is either `0`
or `1`, which changes the normalization factor from `L-1` (for `d=0`) to
`L` (for `d=1`) where `L` is the number of rows in the matrix `x`.  In
this case, the syntaxes are

```text
  y = cov(x,z,d)
```
for the two-argument case, and

```text
  y = cov(x,d)
```
for the one-argument case.

## Example
The following demonstrates some uses of the `cov` function

```fm-exec
A = [5,1,3;3,2,1;0,3,1]
B = [4,-2,0;1,5,2;-2,0,1];
```

We start with the covariance matrix for `A`

```fm-exec
cov(A)
```

and again with the (biased) normalization

```fm-exec
cov(A,1)
```

Here we compute the cross covariance between `A` and `B`

```fm-exec
cov(A,B)
```

and again with biased normalization

```fm-exec
cov(A,B,1)
```
"#,
}

fm_doc::register_doc! {
    name: "cumprod",
    aliases: [],
    section: "elementary",
    summary: "Cumulative Product Function",
    body: r#"
## Usage
Computes the cumulative product of an n-dimensional array along a given
dimension.  The general syntax for its use is

```text
  y = cumprod(x,d)
```
where `x` is a multidimensional array of numerical type, and `d`
is the dimension along which to perform the cumulative product.  The
output `y` is the same size of `x`.  Integer types are promoted
to `int32`. If the dimension `d` is not specified, then the
cumulative sum is applied along the first non-singular dimension.

## Function Internals
The output is computed via

$$
  y(m_1,\ldots,m_{d-1},j,m_{d+1},\ldots,m_{p}) =
  \prod_{k=1}^{j} x(m_1,\ldots,m_{d-1},k,m_{d+1},\ldots,m_{p}).
$$

## Example
The default action is to perform the cumulative product along the
first non-singular dimension.

```fm-exec
A = [5,1,3;3,2,1;0,3,1]
cumprod(A)
```

To compute the cumulative product along the columns:

```fm-exec
cumprod(A,2)
```

The cumulative product also works along arbitrary dimensions

```fm-exec
B(:,:,1) = [5,2;8,9];
B(:,:,2) = [1,0;3,0]
cumprod(B,3)
```
"#,
}

fm_doc::register_doc! {
    name: "cumsum",
    aliases: [],
    section: "elementary",
    summary: "Cumulative Summation Function",
    body: r#"
## Usage
Computes the cumulative sum of an n-dimensional array along a given
dimension.  The general syntax for its use is

```text
  y = cumsum(x,d)
```
where `x` is a multidimensional array of numerical type, and `d`
is the dimension along which to perform the cumulative sum.  The
output `y` is the same size of `x`.  Integer types are promoted
to `int32`. If the dimension `d` is not specified, then the
cumulative sum is applied along the first non-singular dimension.

## Function Internals
The output is computed via

$$
  y(m_1,\ldots,m_{d-1},j,m_{d+1},\ldots,m_{p}) =
  \sum_{k=1}^{j} x(m_1,\ldots,m_{d-1},k,m_{d+1},\ldots,m_{p}).
$$

## Example
The default action is to perform the cumulative sum along the
first non-singular dimension.

```fm-exec
A = [5,1,3;3,2,1;0,3,1]
cumsum(A)
```

To compute the cumulative sum along the columns:

```fm-exec
cumsum(A,2)
```

The cumulative sum also works along arbitrary dimensions

```fm-exec
B(:,:,1) = [5,2;8,9];
B(:,:,2) = [1,0;3,0]
cumsum(B,3)
```
"#,
}

fm_doc::register_doc! {
    name: "deal",
    aliases: [],
    section: "elementary",
    summary: "Multiple Simultaneous Assignments",
    body: r#"
## Usage
When making a function call, it is possible to assign
multiple outputs in a single call, (see, e.g., `max` for
an example).  The `deal` call allows you to do the
same thing with a simple assignment.  The syntax for its
use is

```text
   [a,b,c,...] = deal(expr)
```
where `expr` is an expression with multiple values.  The simplest
example is where `expr` is the dereference of a cell array, e.g.
`expr <-- A{:}`.  In this case, the `deal` call is equivalent
to

```text
   a = A{1}; b = A{2}; C = A{3}; 
```
Other expressions which are multivalued are structure arrays with
multiple entries (non-scalar), where field dereferencing has been
applied.
"#,
}

fm_doc::register_doc! {
    name: "dec2hex",
    aliases: [],
    section: "elementary",
    summary: "Convert Decimal Number to Hexadecimal",
    body: r#"
## Usage
Converts an integer value into its hexadecimal representation.  The syntax
for its use is

```text
   y = dec2hex(x)
```
where `x` is an integer (and is promoted to a 64-bit integer if it is not).
The returned value `y` is a string containing the hexadecimal representation
of that integer.  If you require a minimum length for the hexadecimal
representation, you can specify an optional second argument

```text
   y = dec2hex(x,n)
```
where `n` indicates the minimum number of digits in the representation.

## Example
Here are some simple examples:

```fm-exec
dec2hex(1023)
```

```fm-exec
dec2hex(58128493)
```
"#,
}

fm_doc::register_doc! {
    name: "diff",
    aliases: [],
    section: "elementary",
    summary: "Difference Function",
    body: r#"
## Usage

```text
	y=diff(x)
	y=diff(x,k)
	y=diff(x,k,dim)
```
 Produce difference of successive vector elements.

 If `x` is a vector of length n, `diff (x)` is the
 vector of first differences
 \[
  [x_2 - x_1, ..., x_n - x_{n-1}].
 \]

 If `x` is a matrix, `diff (x)` is the matrix of column
 differences along the first non-singleton dimension.

 The second argument is optional.  If supplied, `diff (x,k)`,
 where `k` is a nonnegative integer, returns the
 `k`-th differences. It is possible that `k` is larger than
 then first non-singleton dimension of the matrix. In this case,
 `diff` continues to take the differences along the next
 non-singleton dimension.

 The dimension along which to take the difference can be explicitly
 stated with the optional variable `dim`. In this case the
 `k`-th order differences are calculated along this dimension.
 In the case where `k` exceeds `size (x, dim)`
 then an empty matrix is returned.
"#,
}

fm_doc::register_doc! {
    name: "dot",
    aliases: [],
    section: "elementary",
    summary: "Dot Product Function",
    body: r#"
## Usage
Computes the scalar dot product of its two arguments.  The general
syntax for its use is

```text
  y = dot(x,z)
```
where `x` and `z` are numerical vectors of the same length.  If
`x` and `z` are multi-dimensional arrays of the same size, then
the dot product is taken along the first non-singleton dimension.
You can also specify the dimension to take the dot product along using
the alternate form

```text
  y = dot(x,z,dim)
```
where `dim` specifies the dimension to take the dot product along.
"#,
}

fm_doc::register_doc! {
    name: "floor",
    aliases: [],
    section: "elementary",
    summary: "Floor Function",
    body: r#"
## Usage
Computes the floor of an n-dimensional array elementwise.  The
floor of a number is defined as the smallest integer that is
less than or equal to that number. The general syntax for its use
is

```text
   y = floor(x)
```
where `x` is a multidimensional array of numerical type.  The `floor`
function preserves the type of the argument.  So integer arguments
are not modified, and `float` arrays return `float` arrays as
outputs, and similarly for `double` arrays.  The `floor` function
is not defined for complex types.

## Example
The following demonstrates the `floor` function applied to various
(numerical) arguments.  For integer arguments, the floor function has
no effect:

```fm-exec
floor(3)
floor(-3)
```

Next, we take the `floor` of a floating point value:

```fm-exec
floor(3.023)
floor(-2.341)
```
"#,
}

fm_doc::register_doc! {
    name: "getfield",
    aliases: [],
    section: "elementary",
    summary: "Get Field Contents",
    body: r#"
## Usage
Given a structure or structure array, returns the contents of the
specified field.  The first version is for scalar structures, and
has the following syntax

```text
   y = getfield(x,'fieldname')
```
and is equivalent to `y = x.fieldname` where `x` is a scalar (1 x 1)
structure.  If `x` is not a scalar structure, then `y` is the
first value, i.e., it is equivalent to `y = x(1).fieldname`.
The second form allows you to specify a subindex into a
structure array, and has the following syntax

```text
    y = getfield(x, {m,n}, 'fieldname')
```
and is equivalent to `y = x(m,n).fieldname`.  You can chain multiple
references together using this syntax.
"#,
}

fm_doc::register_doc! {
    name: "hex2dec",
    aliases: [],
    section: "elementary",
    summary: "Convert Hexadecimal Numbers To Decimal",
    body: r#"
## Usage
Converts a hexadecimal number (encoded as a string matrix) into integers.
The syntax for its use is

```text
   y = hex2dec(x)
```
where `x` is a character matrix where each row represents an integer
in hexadecimal form.  The output is of type `Double`.

## Examples

```fm-exec
hex2dec('3ff')
```

Or for a more complex example

```fm-exec
hex2dec(['0ff';'2de';'123'])
```
"#,
}

fm_doc::register_doc! {
    name: "imag",
    aliases: [],
    section: "elementary",
    summary: "Imaginary Function",
    body: r#"
## Usage
Returns the imaginary part of the input array for all elements.  The
general syntax for its use is

```text
   y = imag(x)
```
where `x` is an `n`-dimensional array of numerical type.  The output
is the same numerical type as the input, unless the input is `complex`
or `dcomplex`.  For `complex` inputs, the imaginary part is a floating
point array, so that the return type is `float`.  For `dcomplex`
inputs, the imaginary part is a double precision floating point array, so that
the return type is `double`.  The `imag` function returns zeros for
real and integer types.

## Example
The following demonstrates `imag` applied to a complex scalar.

```fm-exec
imag(3+4*i)
```

The imaginary part of real and integer arguments is a vector of zeros, the
same type and size of the argument.

```fm-exec
imag([2,4,5,6])
```

For a double-precision complex array,

```fm-exec
imag([2.0+3.0*i,i])
```
"#,
}

fm_doc::register_doc! {
    name: "ind2sub",
    aliases: [],
    section: "elementary",
    summary: "Convert Linear Indexing To Multiple Indexing",
    body: r#"
## Usage
The `ind2sub` function converts linear indexing expression into a multi-dimensional indexing expressionl
 The syntax for its use
is

```text
   [d1, d2, ..., dn] = ind2sub(sizevec,index)
```
where `sizevec` is the size of the array being indexed into, index is the index value. Each
`di` is a vector of the same length, containing index values.

## Example
Suppose we have a simple `3 x 4` matrix `A` containing some random integer
elements

```fm-exec
A = randi(ones(3,4),10*ones(3,4))
```

```fm-exec
[d1 d2] = ind2sub(size(A),7)
A(d1,d2)
```
"#,
}

fm_doc::register_doc! {
    name: "max",
    aliases: [],
    section: "elementary",
    summary: "Maximum Function",
    body: r#"
## Usage
Computes the maximum of an array along a given dimension, or alternately,
computes two arrays (entry-wise) and keeps the smaller value for each array.
As a result, the `max` function has a number of syntaxes.  The first
one computes the maximum of an array along a given dimension.
The first general syntax for its use is either

```text
   [y,n] = max(x,[],d)
```
where `x` is a multidimensional array of numerical type, in which case the
output `y` is the maximum of `x` along dimension `d`.
The second argument `n` is the index that results in the maximum.
In the event that multiple maxima are present with the same value,
the index of the first maximum is used.
The second general syntax for the use of the `max` function is

```text
   [y,n] = max(x)
```
In this case, the maximum is taken along the first non-singleton
dimension of `x`.  For complex data types,
the maximum is based on the magnitude of the numbers.  NaNs are
ignored in the calculations.
The third general syntax for the use of the `max` function is as
a comparison function for pairs of arrays.  Here, the general syntax is

```text
   y = max(x,z)
```
where `x` and `z` are either both numerical arrays of the same dimensions,
or one of the two is a scalar.  In the first case, the output is the
same size as both arrays, and is defined elementwise by the smaller of the
two arrays.  In the second case, the output is defined elementwise by the
smaller of the array entries and the scalar.

## Function Internals
In the general version of the `max` function which is applied to
a single array (using the `max(x,[],d)` or `max(x)` syntaxes),
The output is computed via

$$
y(m_1,\ldots,m_{d-1},1,m_{d+1},\ldots,m_{p}) =
\max_{k} x(m_1,\ldots,m_{d-1},k,m_{d+1},\ldots,m_{p}),
$$
and the output array `n` of indices is calculated via

$$
n(m_1,\ldots,m_{d-1},1,m_{d+1},\ldots,m_{p}) = \arg
\max_{k} x(m_1,\ldots,m_{d-1},k,m_{d+1},\ldots,m_{p})
$$
In the two-array version (`max(x,z)`), the single output is computed as

$$
  y(m_1,\ldots,m_{d-1},1,m_{d+1},\ldots,m_{p}) =
\begin{cases}
  x(m_1,\ldots,m_{d-1},k,m_{d+1},\ldots,m_{p}) & x(\cdots) \leq z(\cdots) \\    z(m_1,\ldots,m_{d-1},k,m_{d+1},\ldots,m_{p}) & z(\cdots) < x(\cdots).
\end{cases}
$$

## Example
The following piece of code demonstrates various uses of the maximum
function.  We start with the one-array version.

```fm-exec
A = [5,1,3;3,2,1;0,3,1]
```

We first take the maximum along the columns, resulting in a row vector.

```fm-exec
max(A)
```

Next, we take the maximum along the rows, resulting in a column vector.

```fm-exec
max(A,[],2)
```

When the dimension argument is not supplied, `max` acts along the first non-singular dimension.  For a row vector, this is the column direction:

```fm-exec
max([5,3,2,9])
```

For the two-argument version, we can compute the smaller of two arrays,
as in this example:

```fm-exec
a = int8(100*randn(4))
b = int8(100*randn(4))
max(a,b)
```

Or alternately, we can compare an array with a scalar

```fm-exec
a = randn(2)
max(a,0)
```
"#,
}

fm_doc::register_doc! {
    name: "mean",
    aliases: [],
    section: "elementary",
    summary: "Mean Function",
    body: r#"
## Usage
Computes the mean of an array along a given dimension.  The general
syntax for its use is

```text
  y = mean(x,d)
```
where `x` is an `n`-dimensions array of numerical type.
The output is of the same numerical type as the input.  The argument
`d` is optional, and denotes the dimension along which to take
the mean.  The output `y` is the same size as `x`, except
that it is singular along the mean direction.  So, for example,
if `x` is a `3 x 3 x 4` array, and we compute the mean along
dimension `d=2`, then the output is of size `3 x 1 x 4`.

## Function Internals
The output is computed via

$$
y(m_1,\ldots,m_{d-1},1,m_{d+1},\ldots,m_{p}) = \frac{1}{N}
\sum_{k=1}^{N} x(m_1,\ldots,m_{d-1},k,m_{d+1},\ldots,m_{p})
$$
If `d` is omitted, then the mean is taken along the
first non-singleton dimension of `x`.

## Example
The following piece of code demonstrates various uses of the mean
function

```fm-exec
A = [5,1,3;3,2,1;0,3,1]
```

We start by calling `mean` without a dimension argument, in which
case it defaults to the first nonsingular dimension (in this case,
along the columns or `d = 1`).

```fm-exec
mean(A)
```

Next, we take the mean along the rows.

```fm-exec
mean(A,2)
```
"#,
}

fm_doc::register_doc! {
    name: "min",
    aliases: [],
    section: "elementary",
    summary: "Minimum Function",
    body: r#"
## Usage
Computes the minimum of an array along a given dimension, or alternately,
computes two arrays (entry-wise) and keeps the smaller value for each array.
As a result, the `min` function has a number of syntaxes.  The first
one computes the minimum of an array along a given dimension.
The first general syntax for its use is either

```text
   [y,n] = min(x,[],d)
```
where `x` is a multidimensional array of numerical type, in which case the
output `y` is the minimum of `x` along dimension `d`.
The second argument `n` is the index that results in the minimum.
In the event that multiple minima are present with the same value,
the index of the first minimum is used.
The second general syntax for the use of the `min` function is

```text
   [y,n] = min(x)
```
In this case, the minimum is taken along the first non-singleton
dimension of `x`.  For complex data types,
the minimum is based on the magnitude of the numbers.  NaNs are
ignored in the calculations.
The third general syntax for the use of the `min` function is as
a comparison function for pairs of arrays.  Here, the general syntax is

```text
   y = min(x,z)
```
where `x` and `z` are either both numerical arrays of the same dimensions,
or one of the two is a scalar.  In the first case, the output is the
same size as both arrays, and is defined elementwise by the smaller of the
two arrays.  In the second case, the output is defined elementwise by the
smaller of the array entries and the scalar.

## Function Internals
In the general version of the `min` function which is applied to
a single array (using the `min(x,[],d)` or `min(x)` syntaxes),
The output is computed via

$$
y(m_1,\ldots,m_{d-1},1,m_{d+1},\ldots,m_{p}) =
\min_{k} x(m_1,\ldots,m_{d-1},k,m_{d+1},\ldots,m_{p}),
$$
and the output array `n` of indices is calculated via

$$
n(m_1,\ldots,m_{d-1},1,m_{d+1},\ldots,m_{p}) = \arg
\min_{k} x(m_1,\ldots,m_{d-1},k,m_{d+1},\ldots,m_{p})
$$
In the two-array version (`min(x,z)`), the single output is computed as

$$
  y(m_1,\ldots,m_{d-1},1,m_{d+1},\ldots,m_{p}) =
\begin{cases}
  x(m_1,\ldots,m_{d-1},k,m_{d+1},\ldots,m_{p}) & x(\cdots) \leq z(\cdots) \\   z(m_1,\ldots,m_{d-1},k,m_{d+1},\ldots,m_{p}) & z(\cdots) < x(\cdots).
\end{cases}
$$

## Example
The following piece of code demonstrates various uses of the minimum
function.  We start with the one-array version.

```fm-exec
A = [5,1,3;3,2,1;0,3,1]
```

We first take the minimum along the columns, resulting in a row vector.

```fm-exec
min(A)
```

Next, we take the minimum along the rows, resulting in a column vector.

```fm-exec
min(A,[],2)
```

When the dimension argument is not supplied, `min` acts along the first
non-singular dimension.  For a row vector, this is the column direction:

```fm-exec
min([5,3,2,9])
```

For the two-argument version, we can compute the smaller of two arrays,
as in this example:

```fm-exec
a = int8(100*randn(4))
b = int8(100*randn(4))
min(a,b)
```

Or alternately, we can compare an array with a scalar

```fm-exec
a = randn(2)
min(a,0)
```
"#,
}

fm_doc::register_doc! {
    name: "num2hex",
    aliases: [],
    section: "elementary",
    summary: "Convert Numbers to IEEE Hex Strings",
    body: r#"
## Usage
Converts single and double precision arrays to IEEE hex strings.  The
syntax for its use is

```text
   y = num2hex(x)
```
where `x` is either a `float` or `double` array.  The output `y` is
a `n-by-p` character array, where `n` is the number of elements in `x`,
and `p` is 16 for `double` arrays, and 8 for `single` arrays.

## Example
Some interesting numbers

```fm-exec
num2hex([1 0 0.1 -pi inf nan])
```

The same in single precision

```fm-exec
num2hex(float([1 0 0.1 -pi inf nan]))
```
"#,
}

fm_doc::register_doc! {
    name: "prod",
    aliases: [],
    section: "elementary",
    summary: "Product Function",
    body: r#"
## Usage
Computes the product of an array along a given dimension.  The general
syntax for its use is

```text
   y = prod(x,d)
```
where `x` is an `n`-dimensions array of numerical type.
The output is of the same numerical type as the input, except
for integer types, which are automatically promoted to `int32`.
 The argument `d` is optional, and denotes the dimension along
which to take the product.  The output is computed via

$$
  y(m_1,\ldots,m_{d-1},1,m_{d+1},\ldots,m_{p}) =
    \prod_{k} x(m_1,\ldots,m_{d-1},k,m_{d+1},\ldots,m_{p})
$$
If `d` is omitted, then the product is taken along the
first non-singleton dimension of `x`. Note that by definition
(starting with FreeMat 2.1) `prod([]) = 1`.

## Example
The following piece of code demonstrates various uses of the product
function

```fm-exec
A = [5,1,3;3,2,1;0,3,1]
```

We start by calling `prod` without a dimension argument, in which case it defaults to the first nonsingular dimension (in this case, along the columns or `d = 1`).

```fm-exec
prod(A)
```

Next, we take the product along the rows.

```fm-exec
prod(A,2)
```
"#,
}

fm_doc::register_doc! {
    name: "real",
    aliases: [],
    section: "elementary",
    summary: "Real Function",
    body: r#"
## Usage
Returns the real part of the input array for all elements.  The
general syntax for its use is

```text
   y = real(x)
```
where `x` is an `n`-dimensional array of numerical type.  The output
is the same numerical type as the input, unless the input is `complex`
or `dcomplex`.  For `complex` inputs, the real part is a floating
point array, so that the return type is `float`.  For `dcomplex`
inputs, the real part is a double precision floating point array, so that
the return type is `double`.  The `real` function does
nothing to real and integer types.

## Example
The following demonstrates the `real` applied to a complex scalar.

```fm-exec
real(3+4*i)
```

The `real` function has no effect on real arguments:

```fm-exec
real([2,3,4])
```

For a double-precision complex array,

```fm-exec
real([2.0+3.0*i,i])
```
"#,
}

fm_doc::register_doc! {
    name: "round",
    aliases: [],
    section: "elementary",
    summary: "Round Function",
    body: r#"
## Usage
Rounds an n-dimensional array to the nearest integer elementwise.
The general syntax for its use is

```text
   y = round(x)
```
where `x` is a multidimensional array of numerical type.  The `round`
function preserves the type of the argument.  So integer arguments
are not modified, and `float` arrays return `float` arrays as
outputs, and similarly for `double` arrays.  The `round` function
is not defined for `complex` or `dcomplex` types.

## Example
The following demonstrates the `round` function applied to various
(numerical) arguments.  For integer arguments, the round function has
no effect:

```fm-exec
round(3)
round(-3)
```

Next, we take the `round` of a floating point value:

```fm-exec
round(3.023f)
round(-2.341f)
```

Note that the return type is a `float` also.  Finally, for a `double`
type:

```fm-exec
round(4.312)
round(-5.32)
```
"#,
}

fm_doc::register_doc! {
    name: "std",
    aliases: [],
    section: "elementary",
    summary: "Standard Deviation Function",
    body: r#"
## Usage
Computes the standard deviation of an array along a given dimension.
The general syntax for its use is

```text
  y = std(x,d)
```
where `x` is an `n`-dimensions array of numerical type.
The output is of the same numerical type as the input.  The argument
`d` is optional, and denotes the dimension along which to take
the variance.  The output `y` is the same size as `x`, except
that it is singular along the mean direction.  So, for example,
if `x` is a `3 x 3 x 4` array, and we compute the mean along
dimension `d=2`, then the output is of size `3 x 1 x 4`.

## Example
The following piece of code demonstrates various uses of the `std`
function

```fm-exec
A = [5,1,3;3,2,1;0,3,1]
```

We start by calling `std` without a dimension argument, in which
case it defaults to the first nonsingular dimension (in this case,
along the columns or `d = 1`).

```fm-exec
std(A)
```

Next, we take the variance along the rows.

```fm-exec
std(A,2)
```
"#,
}

fm_doc::register_doc! {
    name: "sub2ind",
    aliases: [],
    section: "elementary",
    summary: "Convert Multiple Indexing To Linear Indexing",
    body: r#"
## Usage
The `sub2ind` function converts a multi-dimensional indexing expression
into a linear (or vector) indexing expression.  The syntax for its use
is

```text
   y = sub2ind(sizevec,d1,d2,...,dn)
```
where `sizevec` is the size of the array being indexed into, and each
`di` is a vector of the same length, containing index values.  The basic
idea behind `sub2ind` is that it makes

```text
  [z(d1(1),d2(1),...,dn(1)),...,z(d1(n),d2(n),...,dn(n))]
```
equivalent to

```text
  z(sub2ind(size(z),d1,d2,...,dn))
```
where the later form is using vector indexing, and the former one is using
native, multi-dimensional indexing.

## Example
Suppose we have a simple `3 x 4` matrix `A` containing some random integer
elements

```fm-exec
A = randi(ones(3,4),10*ones(3,4))
```

We can extract the elements `(1,3),(2,3),(3,4)` of `A` via `sub2ind`.
To calculate which elements of `A` this corresponds to, we can use
`sub2ind` as

```fm-exec
n = sub2ind(size(A),1:3,2:4)
A(n)
```
"#,
}

fm_doc::register_doc! {
    name: "sum",
    aliases: [],
    section: "elementary",
    summary: "Sum Function",
    body: r#"
## Usage
Computes the summation of an array along a given dimension.  The general
syntax for its use is

```text
  y = sum(x,d)
```
where `x` is an `n`-dimensions array of numerical type.
The output is of the same numerical type as the input.  The argument
`d` is optional, and denotes the dimension along which to take
the summation.  The output `y` is the same size as `x`, except
that it is singular along the summation direction.  So, for example,
if `x` is a `3 x 3 x 4` array, and we compute the summation along
dimension `d=2`, then the output is of size `3 x 1 x 4`.

## Function Internals
The output is computed via

$$
y(m_1,\ldots,m_{d-1},1,m_{d+1},\ldots,m_{p}) =
\sum_{k} x(m_1,\ldots,m_{d-1},k,m_{d+1},\ldots,m_{p})
$$
If `d` is omitted, then the summation is taken along the
first non-singleton dimension of `x`.

## Example
The following piece of code demonstrates various uses of the summation
function

```fm-exec
A = [5,1,3;3,2,1;0,3,1]
```

We start by calling `sum` without a dimension argument, in which
case it defaults to the first nonsingular dimension (in this case,
along the columns or `d = 1`).

```fm-exec
sum(A)
```

Next, we take the sum along the rows.

```fm-exec
sum(A,2)
```
"#,
}

fm_doc::register_doc! {
    name: "test",
    aliases: [],
    section: "elementary",
    summary: "Test Function",
    body: r#"
## Usage
Tests for the argument array to be all logical 1s.  It is
completely equivalent to the `all` function applied to
a vectorized form of the input.  The syntax for the `test`
function is

```text
   y = test(x)
```
and the result is equivalent to `all(x(:))`.
"#,
}

fm_doc::register_doc! {
    name: "var",
    aliases: [],
    section: "elementary",
    summary: "Variance Function",
    body: r#"
## Usage
Computes the variance of an array along a given dimension.  The general
syntax for its use is

```text
  y = var(x,d)
```
where `x` is an `n`-dimensions array of numerical type.
The output is of the same numerical type as the input.  The argument
`d` is optional, and denotes the dimension along which to take
the variance.  The output `y` is the same size as `x`, except
that it is singular along the mean direction.  So, for example,
if `x` is a `3 x 3 x 4` array, and we compute the mean along
dimension `d=2`, then the output is of size `3 x 1 x 4`.

## Function Internals
The output is computed via

$$
y(m_1,\ldots,m_{d-1},1,m_{d+1},\ldots,m_{p}) = \frac{1}{N-1}
\sum_{k=1}^{N} \left(x(m_1,\ldots,m_{d-1},k,m_{d+1},\ldots,m_{p})
 - \bar{x}\right)^2,
$$
where

$$
\bar{x}  = \frac{1}{N}
\sum_{k=1}^{N} x(m_1,\ldots,m_{d-1},k,m_{d+1},\ldots,m_{p})
$$
If `d` is omitted, then the mean is taken along the
first non-singleton dimension of `x`.

## Example
The following piece of code demonstrates various uses of the var
function

```fm-exec
A = [5,1,3;3,2,1;0,3,1]
```

We start by calling `var` without a dimension argument, in which
case it defaults to the first nonsingular dimension (in this case,
along the columns or `d = 1`).

```fm-exec
var(A)
```

Next, we take the variance along the rows.

```fm-exec
var(A,2)
```
"#,
}

fm_doc::register_doc! {
    name: "vec",
    aliases: [],
    section: "elementary",
    summary: "Reshape to a Vector",
    body: r#"
## Usage
Reshapes an n-dimensional array into a column vector.  The general
syntax for its use is

```text
   y = vec(x)
```
where `x` is an n-dimensional array (not necessarily numeric).  This
function is equivalent to the expression `y = x(:)`.

## Example
A simple example of the `vec` operator reshaping a 2D matrix:

```fm-exec
A = [1,2,4,3;2,3,4,5]
vec(A)
```
"#,
}
