//! Migrated help docs for the `external` section (help-system P7).
//! GENERATED by `cargo xtask migrate-place` — do not edit by hand.

fm_doc::register_section! {
    id: "external",
    title: "FreeMat External Interface",
    summary: "Interfacing FreeMat with external code and libraries.",
}

fm_doc::register_doc! {
    name: "cenum",
    aliases: [],
    section: "external",
    summary: "Lookup Enumerated C Type",
    body: r#"
## Usage
The `cenum` function allows you to use the textual strings of C
enumerated types (that have been defined using `ctypedefine`) in
your FreeMat scripts isntead of the hardcoded numerical values.  The
general syntax for its use is

```text
  enum_int = cenum(enum_type,enum_string)
```
which looks up the integer value of the enumerated type based on the
string.  You can also supply an integer argument, in which case
`cenum` will find the matching string

```text
  enum_string = cenum(enum_type,enum_int)
```
"#,
}

fm_doc::register_doc! {
    name: "ctypecast",
    aliases: [],
    section: "external",
    summary: "Cast FreeMat Structure to C Structure",
    body: r#"
## Usage
The `ctypecast` function is a convenience function for ensuring that
a FreeMat structure fits the definition of a C struct (as defined
via `ctypedefine`.  It does so by encoding the structure
to a byte array using `ctypefreeze` and then recovering it using
the `ctypethaw` function.  The usage is simply

```text
   s = ctypecast(s,typename)
```
where `s` is the structure and `typename` is the name of the
C structure that describes the desired layout and types for elements
of `s`.  This function is equivalent to calling `ctypefreeze`
and `ctypethaw` in succession on a FreeMat structure.
"#,
}

fm_doc::register_doc! {
    name: "ctypedefine",
    aliases: [],
    section: "external",
    summary: "Define C Type",
    body: r#"
## Usage
The `ctypedefine` function allows you to define C types for use
with FreeMat.  Three variants of C types can be used.  You can
use structures, enumerations, and aliases (typedefs).  All three are defined
through a single function `ctypedefine`.  The general syntax for
its use is

```text
  ctypedefine(typeclass,typename,...)
```
where `typeclass` is the variant of the type (legal values are
`'struct'`, `'alias'`, `'enum'`).  The second argument is the
name of the C type.  The remaining arguments depend on what the
class of the typedef is.

To define a C structure, use the `'struct'` type class.  The usage
in this case is:

```text
  ctypedefine('struct',typename,field1,type1,field2,type2,...)
```
The argument `typename` must be a valid identifier string.  Each of
of the `field` arguments is also a valid identifier string that
describe in order, the elements of the C structure.  The `type` arguments
are `typespecs`.  They can be of three types:
- Built in types, e.g. `'uint8'` or `'double'` to name a couple of
      examples.

- C types that have previously been defined with a call to
      `ctypedefine`, e.g. `'mytype'` where `'mytype'` has already been
      defined through a call to `ctypedefine`.

- Arrays of either built in types or previously defined C types
      with the length of the array coded as an integer in square brackets,
      for example: `'uint8[10]'` or `'double[1000]'`.

To define a C enumeration, use the `'enum'` type class.  The usage
in this case is:
  ctypedefine('enum',typename,name1,value1,name2,value2,...)
@]
The argument `typename` must be a valid identifier string.  Each of the
`name` arguments must also be valid identifier strings that describe
the possible values that the enumeration can take an, and their corresponding
integer values.  Note that the names should be unique.  The behavior of
the various `cenum` functions is undefined if the names are not unique.

To define a C alias (or typedef), use the following form of `ctypedefine`:

```text
  ctypedefine('alias',typename,aliased_typename)
```
where `aliased_typename` is the type that is being aliased to.
"#,
}

fm_doc::register_doc! {
    name: "ctypefreeze",
    aliases: [],
    section: "external",
    summary: "Convert FreeMat Structure to C Type",
    body: r#"
## Usage
The `ctypefreeze` function is used to convert a FreeMat structure into
a C struct as defined by a C structure typedef.  To use the `cstructfreeze`
function, you must first define the type of the C structure using the
`ctypedefine` function.  The `ctypefreeze` function then serializes
a FreeMat structure to a set of bytes, and returns it as an array.  The
usage for `ctypefreeze` is

```text
  byte_array = ctypefreeze(mystruct, 'typename')
```
where `mystruct` is the array we want to 'freeze' to a memory array,
and `typename` is the name of the C type that we want the resulting
byte array to conform to.
"#,
}

fm_doc::register_doc! {
    name: "ctypenew",
    aliases: [],
    section: "external",
    summary: "Create New Instance of C Structure",
    body: r#"
## Usage
The `ctypenew` function is a convenience function for
creating a FreeMat structure that corresponds to a C
structure.  The entire structure is initialized with zeros.
This has some negative implications, because if the
structure definition uses `cenums`, they may come out
as `'unknown'` values if there are no enumerations corresponding
to zero.  The use of the function is

```text
   a = ctypenew('typename')
```
which creates a single structure of C structure type `'typename'`.
To create an array of structures, we can provide a second argument

```text
   a = ctypenew('typename',count)
```
where `count` is the number of elements in the structure array.
"#,
}

fm_doc::register_doc! {
    name: "ctypeprint",
    aliases: [],
    section: "external",
    summary: "Print C Type",
    body: r#"
## Usage
The `ctypeprint` function prints a C type on the console.  The
usage is

```text
  ctypeprint(typename)
```
where `typename` is a string containing the name of the C type to print.
Depending on the class of the C type (e.g., structure, alias or enumeration)
the `ctypeprint` function will dump information about the type definition.
"#,
}

fm_doc::register_doc! {
    name: "ctyperead",
    aliases: [],
    section: "external",
    summary: "Read a C Structure From File",
    body: r#"
## Usage
The `ctyperead` function is a convenience function for
reading a C structure from a file.  This is generally a
very bad idea, as direct writing of C structures to files
is notoriously unportable.  Consider yourself warned.  The
syntax for this function is

```text
   a = ctyperead(fid,'typename')
```
where `'typename'` is a string containing the name of the
C structure as defined using `ctypedefine`, and `fid`
is the file handle returned by the `fopen` command.  Note
that this form will read a single structure from the file.
If you want to read multiple structures into an array,
use the following form

```text
   a = ctyperead(fid,'typename',count)
```
Note that the way this function works is by using `ctypesize`
to compute the size of the structure, reading that many bytes
from the file, and then calling `ctypethaw` on the resulting
buffer.  A consequence of this behavior is that the byte-endian
corrective behavior of FreeMat does not work.
"#,
}

fm_doc::register_doc! {
    name: "ctypesize",
    aliases: [],
    section: "external",
    summary: "Compute Size of C Struct",
    body: r#"
## Usage
The `ctypesize` function is used to compute the size of a C structure
that is defined using the `ctypedefine` function.  The usage of
`ctypesize` is

```text
   size = ctypesize('typename')
```
where `typename` is the name of the C structure you want to compute
the size of.  The returned count is measured in bytes.  Note that as
indicated in the help for `ctypedefine` that FreeMat does not
automatically pad the entries of the structure to match the particulars
of your C compiler.  Instead, the assumption is that you have adequate
padding entries in your structure to align the FreeMat members with the
C ones.  See `ctypedefine` for more details.  You can also specify
an optional count parameter if you want to determine how large multiple
structures are

```text
   size = ctypesize('typename',count)
```
"#,
}

fm_doc::register_doc! {
    name: "ctypethaw",
    aliases: [],
    section: "external",
    summary: "Convert C Struct to FreeMat Structure",
    body: r#"
## Usage
The `ctypethaw` function is used to convert a C structure that is
encoded in a byte array into a FreeMat structure using a C structure
typedef.  To use the `ctypethaw` function, you must first define
the type of the C structure using the `ctypedefine` function.  The
usage of `ctypethaw` is

```text
  mystruct = ctypethaw(byte_array, 'typename')
```
where `byte_array` is a `uint8` array containing the bytes that encode
the C structure, and `typename` is a string that contains the type
description as registered with `ctypedefine`.  If you want to
retrieve multiple structures from a single byte array, you can specify
a count as

```text
  mystruct = ctypethaw(byte_array, 'typename', count)
```
where `count` is an integer containing the number of structures to
retrieve.  Sometimes it is also useful to retrieve only part of the
structure from a byte array, and then (based on the contents of the
structure) retrieve more data.  In this case, you can retrieve the
residual byte array using the optional second output argument of
`ctypethaw`:

```text
  [mystruct,byte_array_remaining] = ctypethaw(byte_array, 'typename',...)
```
"#,
}

fm_doc::register_doc! {
    name: "ctypewrite",
    aliases: [],
    section: "external",
    summary: "Write a C Typedef To File",
    body: r#"
## Usage
The `ctypewrite` function is a convenience function for
writing a C typedef to a file.  This is generally a very
bad idea, as writing of C typedefs to files is notoriously
unportable.  Consider yourself warned.  The syntax for this
function is

```text
  ctypewrite(fid,a,'typename')
```
where `a` is the FreeMat typedef to write, `'typename'` is
a string containing the name of the C typedef to use when
writing the typedef to the file (previously defined using
`ctypedefine`), and `fid` is the file handle returned
by `fopen`.
"#,
}

fm_doc::register_doc! {
    name: "import",
    aliases: [],
    section: "external",
    summary: "Foreign Function Import",
    body: r#"
## Usage
The import function allows you to call functions that are compiled into
shared libraries, as if they were FreeMat functions. The usage is

```text
  import(libraryname,symbol,function,return,arguments)
```
The argument `libraryname` is the name of the library (as a string)
to import the function from.  The second argument `symbol` (also
a string), is the name of the symbol to import from the library.  The
third argument `function` is the the name of the function after its
been imported into Freemat.  The fourth argument is a string that
specifies the return type of the function. It can take on one of the
following types:
- 'uint8' for an unsigned, 8-bit integer.

- 'int8' for a signed, 8-bit integer.

- 'uint16' an unsigned, 16-bit  integer.

- 'int16' a signed, 16-bit integer.

- 'uint32' for an unsigned, 32-bit integer.

- 'int32' for a signed, 32-bit integer.

- 'single' for a 32-bit floating point.

- 'double' for a 64-bit floating point.

- 'void' for no return type.

The fourth argument is more complicated.  It encodes the arguments of the
imported function using a special syntax.  In general, the argument list
is a string consisting of entries of the form:

```text
  type[optional bounds check] {optional &}name
```

Here is a list of various scenarios (expressed in 'C'), and the corresponding
entries, along with snippets of code.

<H2>Scalar variable passed by value</H2>
Suppose a function is defined in the library as

```text
  int fooFunction(float t),
```
i.e., it takes a scalar value (or a string) that is passed by value.  Then
the corresponding argument string would be

```text
  'float t'
```
For a C-string, which corresponds to a function prototype of

```text
  int fooFunction(const char *t),
```
the corresponding argument string would be

```text
  'string t'
```
Other types are as listed above.  Note that FreeMat will automatically
promote the type of scalar variables to the type expected by the `C`
function.  For example, if we call a function expecting a `float`
with a `double` or `int16` argument, then FreeMat will automatically
apply type promotion rules prior to calling the function.

<H2>Scalar variable passed by reference:</H2>
Suppose a function is defined in the library as

```text
  int fooFunction(float *t),
```
i.e., it takes a scalar value (or a string) that is passed as a pointer.  Then
the corresponding argument string would be

```text
  'float &t'
```
If the function `fooFunction` modifies `t`, then the argument
passed in FreeMat will also be modified.

<H2>Array variable passed by value:</H2>
In `C`, it is impossible to distinguish an array being passed from
a simple pointer being passed.  More often than not, another argument
indicates the length of the array.  FreeMat has the ability to perform
bounds-checking on array values.  For example, suppose we have a function
of the form

```text
  int sum_onehundred_ints(int *t),
```
where `sum_onehundred_ints` assumes that `t` is a length `100` vector.
Then the corresponding FreeMat argument is

```text
  'float32[100] t'.
```
Note that because the argument is marked as not being passed by reference,
that if `sub_onehundred_ints` modifies the array `t`, this
will not affect the FreeMat argument.  Note that the bounds-check expression
can be any legal scalar expression that evaluates to an integer, and can be
a function of the arguments.  For example to pass a square $ N \times N $
matrix to the following function:

```text
  float determinantmatrix(int N, float *A),
```
we can use the following argument to `import`:

```text
  'int32 N, float[N*N] t'.
```

<H2>Array variable passed by reference:</H2>
If the function in `C` modifies an array, and we wish this to be
reflected in the FreeMat side, we must pass that argument by reference.
Hence, consider the following hypothetical function that squares the
elements of an array (functionally equivalent to $ x.^2 $):

```text
  void squarearray(int N, float *A)
```
we can use the following argument to `import`:

```text
  'int32 N, float[N] &A'.
```
Note that to avoid problems with memory allocation, external functions
are not allowed to return pointers.  As a result, as a general operating
mechanism, the FreeMat code must allocate the proper arrays, and then
pass them by reference to the external function.

<H2>Sending text to the FreeMat console:</H2>
Starting with FreeMat 4.0, it is possible for external code that is
called using the `import` statement to send text to the FreeMat console.
To do so, you must define in each library that wants to send text a
function with the name `freemat_io_handler` that captures its
argument (a function pointer), and stores it
for use by functions in the library.  That function pointer takes a
standard C string argument.  Here is a snippet of code to demonstrate
how this works:

```text
  /* just to make it readable */
  typedef void (*strfunc)(const char*); 

  /* The name we want to use for the function */
  strfunc FreeMatText;                  

  /* this name is case sensitive and must not be mangled (i.e., use extern "C") */
  void freemat_io_handler(strfunc printFunc) {
     FreeMatText = printFunc;
  }

  double SomeImportedFunction(double t) {
     FreeMatText("I am going to double that argument!\n");
     return (t*2);
  }
```
In this case, once `SomeImportedFunction` is called from within FreeMat, the
text `"I am going to double that argument"` will appear in the FreeMat console.

Your `freemat_io_handler` function is automatically called when your library is
loaded by FreeMat, which happens with the first `import` statement that references
it.

Repeating `import` calls to import the same function name will be ignored, except
the first call. In order to refresh the function without restarting FreeMat,
you have to first clear all imported libraries via:

```text
   clear 'libs'
```

## Example
Here is a complete example.  We have a `C` function that adds
two float vectors of the same length, and stores the result in a third array
that is modified by the function.  First, the `C` code:

```fm-file:addArrays.c
void addArrays(int N, float *a, float *b, float *c) {
  int i;
 
  for (i=0;i<N;i++)
   c[i] = a[i] + b[i];
}
```

```text
     addArrays.c
```

We then compile this into a dynamic library, say, `add.so`.  The import
command would then be:

```text
  import('add.so','addArrays','addArrays','void', ...
         'int32 N, float[N] a, float[N] b, float[N] &c');
```
We could then exercise the function exactly as if it had been written
in FreeMat.  The following only works on systems using the GNU
C Compiler:

```fm
if (strcmp(computer,'MAC')) system('gcc -bundle -flat_namespace -undefined suppress -o add.so addArrays.c'); end;
if (~strcmp(computer,'MAC')) system('gcc -shared -fPIC -o add.so addArrays.c'); end;
import('add.so','addArrays','addArrays','void','int32 N, float[N] a, float[N] b, float[N] &c');
a = [3,2,3,1];
b = [5,6,0,2]; 
c = [0,0,0,0];
addArrays(length(a),a,b,c)
c
```
"#,
}

fm_doc::register_doc! {
    name: "loadlib",
    aliases: [],
    section: "external",
    summary: "Load Library Function",
    body: r#"
## Usage
The `loadlib` function allows a function in an external library
to be added to FreeMat dynamically.  This interface is generally
to be used as last resort, as the form of the function being called
is assumed to match the internal implementation.  In short, this
is not the interface mechanism of choice.  For all but very complicated
functions, the `import` function is the preferred approach. Thus,
only a very brief summary of it is presented here.  The syntax
for `loadlib` is

```text
  loadlib(libfile, symbolname, functionname, nargin, nargout)
```
where `libfile` is the complete path to the library to use, `symbolname`
is the name of the symbol in the library, `functionname` is the name
of the function after it is imported into FreeMat (this is optional, it
defaults to the `symbolname`), `nargin` is the number of input arguments
(defaults to 0), and `nargout` is the number of output arguments (defaults
to 0).  If the number of (input or output) arguments is variable then
set the corresponding argument to `-1`.
"#,
}
