//! Migrated help docs for the `flow` section (help-system P7).
//! GENERATED by `cargo xtask migrate-place` — do not edit by hand.

fm_doc::register_section! {
    id: "flow",
    title: "Flow Control",
    summary: "Control flow: conditionals, loops, and branching.",
}

fm_doc::register_doc! {
    name: "break",
    aliases: [],
    section: "flow",
    summary: "Exit Execution In Loop",
    body: r#"
## Usage
The `break` statement is used to exit a loop prematurely.
It can be used inside a `for` loop or a `while` loop.  The
syntax for its use is

```text
   break
```
inside the body of the loop.  The `break` statement forces
execution to exit the loop immediately.

## Example
Here is a simple example of how `break` exits the loop.
We have a loop that sums integers from `1` to `10`, but
that stops prematurely at `5` using a `break`.  We will
use a `while` loop.

```fm-file:break_ex.m
function accum = break_ex
  accum = 0;
  i = 1;
  while (i<=10)
    accum = accum + i;
    if (i == 5)
      break;
    end
    i = i + 1;
  end
```

```text
     break_ex.m
```

The function is exercised here:

```fm-exec
break_ex
sum(1:5)
```
"#,
}

fm_doc::register_doc! {
    name: "continue",
    aliases: [],
    section: "flow",
    summary: "Continue Execution In Loop",
    body: r#"
## Usage
The `continue` statement is used to change the order of
execution within a loop.  The `continue` statement can
be used inside a `for` loop or a `while` loop.  The
syntax for its use is

```text
   continue
```
inside the body of the loop.  The `continue` statement
forces execution to start at the top of the loop with
the next iteration.  The examples section shows how
the `continue` statement works.

## Example
Here is a simple example of using a `continue` statement.
We want to sum the integers from `1` to `10`, but not
the number `5`.  We will use a `for` loop and a continue
statement.

```fm-file:continue_ex.m
function accum = continue_ex
  accum = 0;
  for i=1:10
    if (i==5)
      continue;
    end
    accum = accum + 1; %skipped if i == 5!
  end
```

```text
     continue_ex.m
```

The function is exercised here:

```fm-exec
continue_ex
sum([1:4,6:10])
```
"#,
}

fm_doc::register_doc! {
    name: "error",
    aliases: [],
    section: "flow",
    summary: "Causes an Error Condition Raised",
    body: r#"
## Usage
The `error` function causes an error condition (exception
to be raised).  The general syntax for its use is

```text
   error(s),
```
where `s` is the string message describing the error.  The
`error` function is usually used in conjunction with `try`
and `catch` to provide error handling.  If the string `s`,
then (to conform to the MATLAB API), `error` does nothing.

## Example
Here is a simple example of an `error` being issued by a function
`evenoddtest`:

```fm-file:evenoddtest.m
function evenoddtest(n)
  if (n==0)
    error('zero is neither even nor odd');
  elseif ( n ~= fix(n) )
    error('expecting integer argument');
  end;
  if (n==int32(n/2)*2)
    printf('%d is even\n',n);
  else
    printf('%d is odd\n',n);
  end
```

```text
     evenoddtest.m
```

The normal command line prompt `-->` simply prints the error
that occured.

```fm-exec
# errors: 2
evenoddtest(4)
evenoddtest(5)
evenoddtest(0)
evenoddtest(pi)
```
"#,
}

fm_doc::register_doc! {
    name: "for",
    aliases: [],
    section: "flow",
    summary: "For Loop",
    body: r#"
## Usage
The `for` loop executes a set of statements with an
index variable looping through each element in a vector.
The syntax of a `for` loop is one of the following:

```text
  for (variable=expression)
     statements
  end
```
Alternately, the parenthesis can be eliminated

```text
  for variable=expression
     statements
  end
```
or alternately, the index variable can be pre-initialized
with the vector of values it is going to take:

```text
  for variable
     statements
  end
```
The third form is essentially equivalent to `for variable=variable`,
where `variable` is both the index variable and the set of values
over which the for loop executes.  See the examples section for
an example of this form of the `for` loop.

## Examples
Here we write `for` loops to add all the integers from
`1` to `100`.  We will use all three forms of the `for`
statement.

```fm-exec
accum = 0;
for (i=1:100); accum = accum + i; end
accum
```

The second form is functionally the same, without the
extra parenthesis

```fm-exec
accum = 0;
for i=1:100; accum = accum + i; end
accum
```

In the third example, we pre-initialize the loop variable
with the values it is to take

```fm-exec
```
"#,
}

fm_doc::register_doc! {
    name: "if-elseif-else",
    aliases: [],
    section: "flow",
    summary: "Conditional Statements",
    body: r#"
## Usage
The `if` and `else` statements form a control structure for
conditional execution.  The general syntax involves an `if`
test, followed by zero or more `elseif` clauses, and finally
an optional `else` clause:

```text
  if conditional_expression_1
    statements_1
  elseif conditional_expression_2
    statements_2
  elseif conditional_expresiion_3
    statements_3
  ...
  else
    statements_N
  end
```
Note that a conditional expression is considered true if
the real part of the result of the expression contains
all non-zero elements (this strange convention is adopted
for compatibility with MATLAB).

## Examples
Here is an example of a function that uses an `if` statement

```fm-file:if_test.m
function c = if_test(a)
  if (a == 1)
     c = 'one';
  elseif (a==2)
     c = 'two';
  elseif (a==3)
     c = 'three';
  else
     c = 'something else';
  end
```

```text
     if_test.m
```

Some examples of `if_test` in action:

```fm-exec
if_test(1)
if_test(2)
if_test(3)
if_test(pi)
```
"#,
}

fm_doc::register_doc! {
    name: "keyboard",
    aliases: [],
    section: "flow",
    summary: "Initiate Interactive Debug Session",
    body: r#"
## Usage
The `keyboard` statement is used to initiate an
interactive session at a specific point in a function.
The general syntax for the `keyboard` statement is

```text
   keyboard
```
A `keyboard` statement can be issued in a `script`,
in a `function`, or from within another `keyboard` session.
The result of a `keyboard` statement is that execution
of the program is halted, and you are given a prompt
of the form:

```text
 [scope,n] -->
```
where `scope` is the current scope of execution (either
the name of the function we are executing, or `base` otherwise).
And `n` is the depth of the `keyboard` session. If, for example,
we are in a `keyboard` session, and we call a function that issues
another `keyboard` session, the depth of that second session
will be one higher.  Put another way, `n` is the number of `return`
statements you have to issue to get back to the base workspace.
Incidentally, a `return` is how you exit the `keyboard` session
and resume execution of the program from where it left off.  A
`retall` can be used to shortcut execution and return to the base
workspace.

The `keyboard` statement is an excellent tool for debugging
FreeMat code, and along with `eval` provide a unique set of
capabilities not usually found in compiled environments.  Indeed,
the `keyboard` statement is equivalent to a debugger breakpoint in
more traditional environments, but with significantly more inspection
power.

## Example
Here we demonstrate a two-level `keyboard` situation.  We have
a simple function that calls `keyboard` internally:

```fm-file:key_one.m
function c = key_one(a,b)
c = a + b;
keyboard
```

```text
     key_one.m
```

Now, we execute the function from the base workspace, and
at the `keyboard` prompt, we call it again.  This action
puts us at depth 2.  We can confirm that we are in the second
invocation of the function by examining the arguments.  We
then issue two `return` statements to return to the base
workspace.

```fm
key_one(1,2)
key_one(5,7)
a
b
c
return
a
b
c
return
```
"#,
}

fm_doc::register_doc! {
    name: "lasterr",
    aliases: [],
    section: "flow",
    summary: "Retrieve Last Error Message",
    body: r#"
## Usage
Either returns or sets the last error message.  The
general syntax for its use is either

```text
  msg = lasterr
```
which returns the last error message that occured, or

```text
  lasterr(msg)
```
which sets the contents of the last error message.

## Example
Here is an example of using the `error` function to
set the last error, and then retrieving it using
lasterr.

```fm
try; error('Test error message'); catch; end;
lasterr
```

Or equivalently, using the second form:

```fm
lasterr('Test message');
lasterr
```
"#,
}

fm_doc::register_doc! {
    name: "retall",
    aliases: [],
    section: "flow",
    summary: "Return From All Keyboard Sessions",
    body: r#"
## Usage
The `retall` statement is used to return to the base workspace
from a nested `keyboard` session.  It is equivalent to forcing
execution to return to the main prompt, regardless of the level
of nesting of `keyboard` sessions, or which functions are
running.  The syntax is simple

```text
   retall
```
The `retall` is a convenient way to stop debugging.  In the
process of debugging a complex program or set of functions,
you may find yourself 5 function calls down into the program
only to discover the problem.  After fixing it, issueing
a `retall` effectively forces FreeMat to exit your program
and return to the interactive prompt.

## Example
Here we demonstrate an extreme example of `retall`.  We
are debugging a recursive function `self` to calculate the sum
of the first N integers.  When the function is called,
a `keyboard` session is initiated after the function
has called itself N times.  At this `keyboard` prompt,
we issue another call to `self` and get another `keyboard`
prompt, this time with a depth of 2.  A `retall` statement
returns us to the top level without executing the remainder
of either the first or second call to `self`:

```fm-file:self.m
function y = self(n)
  if (n>1)
    y = n + self(n-1);
    printf('y is %d\n',y);
  else
    y = 1;
    printf('y is initialized to one\n');
    keyboard
  end
```

```text
     self.m
```

```fm-exec
self(4)
self(6)
retall
```
"#,
}

fm_doc::register_doc! {
    name: "return",
    aliases: [],
    section: "flow",
    summary: "Return From Function",
    body: r#"
## Usage
The `return` statement is used to immediately return from
a function, or to return from a `keyboard` session.  The
syntax for its use is

```text
  return
```
Inside a function, a `return` statement causes FreeMat
to exit the function immediately.  When a `keyboard` session
is active, the `return` statement causes execution to
resume where the `keyboard` session started.

## Example
In the first example, we define a function that uses a
`return` to exit the function if a certain test condition
is satisfied.

```fm-file:return_func.m
function ret = return_func(a,b)
  ret = 'a is greater';
  if (a > b)
    return;
  end
  ret = 'b is greater';
  printf('finishing up...\n');
```

```text
     return_func.m
```

Next we exercise the function with a few simple test
cases:

```fm
return_func(1,3)
return_func(5,2)
```

In the second example, we take the function and rewrite
it to use a `keyboard` statement inside the `if` statement.

```fm-file:return_func2.m
function ret = return_func2(a,b)
  if (a > b)
     ret = 'a is greater';
     keyboard;
  else
     ret = 'b is greater';
  end
  printf('finishing up...\n');
```

```text
     return_func2.m
```

Now, we call the function with a larger first argument, which
triggers the `keyboard` session.  After verifying a few
values inside the `keyboard` session, we issue a `return`
statement to resume execution.

```fm
return_func2(2,4)
return_func2(5,1)
ret
a
b
return
```
"#,
}

fm_doc::register_doc! {
    name: "switch",
    aliases: [],
    section: "flow",
    summary: "Switch statement",
    body: r#"
## Usage
The `switch` statement is used to selective execute code
based on the value of either scalar value or a string.
The general syntax for a `switch` statement is

```text
  switch(expression)
    case test_expression_1
      statements
    case test_expression_2
      statements
    otherwise
      statements
  end
```
The `otherwise` clause is optional.  Note that each test
expression can either be a scalar value, a string to test
against (if the switch expression is a string), or a
`cell-array` of expressions to test against.  Note that
unlike `C` `switch` statements, the FreeMat `switch`
does not have fall-through, meaning that the statements
associated with the first matching case are executed, and
then the `switch` ends.  Also, if the `switch` expression
matches multiple `case` expressions, only the first one
is executed.

## Examples
Here is an example of a `switch` expression that tests
against a string input:

```fm-file:switch_test.m
function c = switch_test(a)
  switch(a)
    case {'lima beans','root beer'}
      c = 'food';
    case {'red','green','blue'}
      c = 'color';
    otherwise
      c = 'not sure';
  end
```

```text
     switch_test.m
```

Now we exercise the switch statements

```fm-exec
switch_test('root beer')
switch_test('red')
switch_test('carpet')
```
"#,
}

fm_doc::register_doc! {
    name: "try-catch",
    aliases: [],
    section: "flow",
    summary: "Try and Catch Statement",
    body: r#"
## Usage
The `try` and `catch` statements are used for error handling
and control.  A concept present in `C++`, the `try` and `catch`
statements are used with two statement blocks as follows

```text
   try
     statements_1
   catch
     statements_2
   end
```
The meaning of this construction is: try to execute `statements_1`,
and if any errors occur during the execution, then execute the
code in `statements_2`.  An error can either be a FreeMat generated
error (such as a syntax error in the use of a built in function), or
an error raised with the `error` command.

## Examples
Here is an example of a function that uses error control via `try`
and `catch` to check for failures in `fopen`.

```fm-file:read_file.m
function c = read_file(filename)
try
   fp = fopen(filename,'r');
   c = fgetline(fp);
   fclose(fp);
catch
   c = ['could not open file because of error :' lasterr]
end
```

```text
     read_file.m
```

Now we try it on an example file - first one that does not exist,
and then on one that we create (so that we know it exists).

```fm-exec
read_file('this_filename_is_invalid')
fp = fopen('test_text.txt','w');
fprintf(fp,'a line of text\n');
fclose(fp);
read_file('test_text.txt')
```
"#,
}

fm_doc::register_doc! {
    name: "warning",
    aliases: [],
    section: "flow",
    summary: "Emits a Warning Message",
    body: r#"
## Usage
The `warning` function causes a warning message to be
sent to the user.  The general syntax for its use is

```text
   warning(s)
```
where `s` is the string message containing the warning.

The `warning` function can also be used to turn off warnings, and to
retrieve the current state of the warning flag.  To turn off warnings
use the syntax

```text
   warning off
```
at which point, warnings will not be displayed.  To turn on warnings
use the syntax

```text
   warning on
```
In both cases, you can also retrieve the current state of the warnings
flag

```text
   y = warning('on')
   y = warning('off')
```
"#,
}

fm_doc::register_doc! {
    name: "while",
    aliases: [],
    section: "flow",
    summary: "While Loop",
    body: r#"
## Usage
The `while` loop executes a set of statements as long as
a the test condition remains `true`.  The syntax of a
`while` loop is

```text
  while test_expression
     statements
  end
```
Note that a conditional expression is considered true if
the real part of the result of the expression contains
any non-zero elements (this strange convention is adopted
for compatibility with MATLAB).

## Examples
Here is a `while` loop that adds the integers from `1`
to `100`:

```fm-exec
accum = 0;
k=1;
while (k<=100), accum = accum + k; k = k + 1; end
accum
```
"#,
}
