//! Migrated help docs for the `freemat` section (help-system P7).
//! GENERATED by `cargo xtask migrate-place` — do not edit by hand.

fm_doc::register_section! {
    id: "freemat",
    title: "FreeMat Functions",
    summary: "Core FreeMat environment and utility functions.",
}

fm_doc::register_doc! {
    name: "addpath",
    aliases: [],
    section: "freemat",
    summary: "Add",
    body: r#"
## Usage
The `addpath` routine adds a set of directories to the current path.
The first form takes a single directory and adds it to the beginning
or top of the path:

```text
  addpath('directory')
```
The second form add several directories to the top of the path:

```text
  addpath('dir1','dir2',...,'dirn')
```
Finally, you can provide a flag to control where the directories get
added to the path

```text
  addpath('dir1','dir2',...,'dirn','-flag')
```
where if `flag` is either `'-0'` or `'-begin'`, the directories are
added to the top of the path, and if the `flag` is either `'-1'` or
`'-end'` the directories are added to the bottom (or end) of the path.
"#,
}

fm_doc::register_doc! {
    name: "assignin",
    aliases: [],
    section: "freemat",
    summary: "Assign Variable in Workspace",
    body: r#"
## Usage
The `assignin` function allows you to assign a value to a variable
in either the callers work space or the base work space.  The syntax
for `assignin` is

```text
   assignin(workspace,variablename,value)
```
The argument `workspace` must be either 'caller' or 'base'.  If it is
'caller' then the variable is assigned in the caller's work space.
That does not mean the caller of `assignin`, but the caller of the
current function or script.  On the other hand if the argument is 'base',
then the assignment is done in the base work space.  Note that the
variable is created if it does not already exist.
"#,
}

fm_doc::register_doc! {
    name: "bind",
    aliases: [],
    section: "freemat",
    summary: "Bind Standalone Executable",
    body: r#"
## Usage
The `bind` function allows you to build a stand alone
executable on Linux.  The syntax for its use is
```text
  bind(output,mainexe,startcommand,varargin)
```
where `output` is the name of the output binary, 
`mainexe` is the location of the FreeMat intepreter to be
used (e.g., `'/usr/local/bin/FreeMat'`).  The next argument
is the start command, i.e., the command to execute once the
interpreter is started.  Generally speaking, it should be
`-f main` where `main` is the name of the routine to start
up.  The last argument is the list of 
M-files to bind into the executable as p-code.  Note that
the resulting binary executable will pass arguments to your main
function automatically, see the example for example.  Bound
executables can use graphics, MPI, and any other FreeMat 
capabilities.

## Example
Here is the ubiquitous "hello world" example done FreeMat
style.  Note that this example will only work under Linux at
the moment.  Support for standalone executables on Mac OS and
Windows is scheduled for a later version of FreeMat.
```fm-file:hello.m
function hello(x)
 printf(' Hello %s\n',x);
```
Here is the `hello` function from within FreeMat
```fm
hello('world!')
```
Now we bind it into an executable.
```fm
bind('hello_bind','../../build/src/x11/FreeMat','-f hello','hello');
```
We have to make the output executable and run it.
```fm
system('chmod +x hello_bind');
system('./hello_bind world!')
```
"#,
}

fm_doc::register_doc! {
    name: "blaslib",
    aliases: [],
    section: "freemat",
    summary: "Select BLAS library",
    body: r#"
## Usage
The `blaslib` function allows you to select the FreeMat blas library.
It has two modes of operation.  The first is to select blas library:

```text
  blaslib LIB_NAME
```
If you want to see current blas library selected
issue a `blaslib` command with no arguments.

```text
   blaslib
```
the returned list of libraries will include an asterix next to the library
currently selected.  If no library is selected, FreeMat will use its internal (reference)
 BLAS implementation, which is slow, but portable.

Location of the optimized library is specified in blas.ini file which is
installed in the binary directory (i.e. directory where FreeMat
executable is located).

The format of blas.ini file is following:

```text
 [Linux64]
ATLAS64\libname=/usr/lib64/atlas/libblas.so
ATLAS64\capfnames=false
ATLAS64\prefix=
ATLAS64\suffix=_
ATLAS64\desc="ATLAS BLAS. Optimized."
```
Where Linux64 is the OS flavor for the blas library described below
it. Other options are [Win32], [Linux32], [OSX]. Note that Linux is our
name for all unix platforms.
- `ATLAS64` - name of the library as it will appear in the list when you
type blaslib command in FreeMat.

- `ATLAS64\\libname` - path to the library. It has to be a shared library
(Linux), DLL (Windows), Bundle (? OSX). This library has to be a Fortran
BLAS library, not cblas!

- `ATLAS64\\capfnames` - does the library use capital letters for function
names (usually false).

- `ATLAS64\\prefix` - prefix (characters that are put in front of) for all
blas functions in the library (e.g. `ATL_` or `AMD_`).

- `ATLAS64\\suffix` - suffix (characters that are put after) for all blas
function in the library (e.g. `_`)

- `ATLAS64\\desc` - text description of the library.

On FreeMat startup it looks at the blas.ini file, and tries to load each
library described in the section for the given OS flavor. FreeMat will
use the first library it can successfully load. If you want to switch
the BLAS libraries dynamically in the running FreeMat session you need
to use blaslib command.

If FreeMat can't load any library it will default to using built in BLAS.

You should be a careful when using non-default BLAS
libraries. Some libraries do not implement all the BLAS functions
correctly. You should run FreeMat test suite (type `run_tests()`) and use
common sense when evaluating the results of numerical computations.
"#,
}

fm_doc::register_doc! {
    name: "builtin",
    aliases: [],
    section: "freemat",
    summary: "Evaulate Builtin Function",
    body: r#"
## Usage
The `builtin` function evaluates a built in function
with the given name, bypassing any overloaded functions.
The syntax of `builtin` is

```text
  [y1,y2,...,yn] = builtin(fname,x1,x2,...,xm)
```
where `fname` is the name of the function to call.  Apart
from the fact that `fname` must be a string, and that `builtin`
always calls the non-overloaded method, it operates exactly like
`feval`.  Note that unlike MATLAB, `builtin` does not force
evaluation to an actual compiled function.  It simply subverts
the activation of overloaded method calls.
"#,
}

fm_doc::register_doc! {
    name: "clc",
    aliases: [],
    section: "freemat",
    summary: "Clear Dislplay",
    body: r#"
## Usage
The `clc` function clears the current display.  The syntax for
its use is

```text
   clc
```
"#,
}

fm_doc::register_doc! {
    name: "clock",
    aliases: [],
    section: "freemat",
    summary: "Get Current Time",
    body: r#"
## Usage
Returns the current date and time as a vector.  The syntax for its use is

```text
   y = clock
```
where `y` has the following format:

```text
   y = [year month day hour minute seconds]
```

## Example
Here is the time that this manual was last built:

```fm
clock
```
"#,
}

fm_doc::register_doc! {
    name: "clocktotime",
    aliases: [],
    section: "freemat",
    summary: "Convert Clock Vector to Epoch Time",
    body: r#"
## Usage
Given the output of the `clock` command, this function computes
the epoch time, i.e, the time in seconds since January 1,1970
at 00:00:00 UTC.  This function is most useful for calculating elapsed
times using the clock, and should be accurate to less than a millisecond
(although the true accuracy depends on accuracy of the argument vector).
The usage for `clocktotime` is

```text
   y = clocktotime(x)
```
where `x` must be in the form of the output of `clock`, that is

```text
   x = [year month day hour minute seconds]
```

## Example
Here is an example of using `clocktotime` to time a delay of 1 second

```fm
x = clock
sleep(1)
y = clock
clocktotime(y) - clocktotime(x)
```
"#,
}

fm_doc::register_doc! {
    name: "computer",
    aliases: [],
    section: "freemat",
    summary: "Computer System FreeMat is Running On",
    body: r#"
## Usage
Returns a string describing the name of the system FreeMat is running on.
The exact value of this string is subject to change, although the `'MAC'`
and `'PCWIN'` values are probably fixed.

```text
  str = computer
```
Currently, the following return values are defined
- `'PCWIN'` - MS Windows

- `'MAC'` - Mac OS X

- `'UNIX'` - All others
"#,
}

fm_doc::register_doc! {
    name: "diary",
    aliases: [],
    section: "freemat",
    summary: "Create a Log File of Console",
    body: r#"
## Usage
The `diary` function controls the creation of a log file that duplicates
the text that would normally appear on the console.
The simplest syntax for the command is simply:

```text
   diary
```
which toggles the current state of the diary command.  You can also explicitly
set the state of the diary command via the syntax

```text
   diary off
```
or

```text
   diary on
```
To specify a filename for the log (other than the default of `diary`), you
can use the form:

```text
   diary filename
```
or

```text
   diary('filename')
```
which activates the diary with an output filename of `filename`.  Note that the
`diary` command is thread specific, but that the output is appended to a given
file.  That means that if you call `diary` with the same filename on multiple
threads, their outputs will be intermingled in the log file (just as on the console).
Because the `diary` state is tied to individual threads, you cannot retrieve the
current diary state using the `get(0,'Diary')` syntax from MATLAB.  Instead, you
must call the `diary` function with no inputs and one output:

```text
   state = diary
```
which returns a logical `1` if the output of the current thread is currently going to
a diary, and a logical `0` if not.
"#,
}

fm_doc::register_doc! {
    name: "docli",
    aliases: [],
    section: "freemat",
    summary: "Start a Command Line Interface",
    body: r#"
## Usage
The `docli` function is the main function that you interact with
when you run FreeMat.  I am not sure why you would want to use
it, but hey - its there if you want to use it.
"#,
}

fm_doc::register_doc! {
    name: "edit",
    aliases: [],
    section: "freemat",
    summary: "Open Editor Window",
    body: r#"
## Usage
Brings up the editor window.  The arguments of `edit` function
are names of files for editing:

```text
  edit file1 file2 file3
```
"#,
}

fm_doc::register_doc! {
    name: "editor",
    aliases: [],
    section: "freemat",
    summary: "Open Editor Window",
    body: r#"
## Usage
Brings up the editor window.  The `editor` function takes no
arguments:

```text
  editor
```
"#,
}

fm_doc::register_doc! {
    name: "errorcount",
    aliases: [],
    section: "freemat",
    summary: "Retrieve the Error Counter for the Interpreter",
    body: r#"
## Usage
This routine retrieves the internal counter for the interpreter,
and resets it to zero.  The general syntax for its use is

```text
   count = errorcount
```
"#,
}

fm_doc::register_doc! {
    name: "etime",
    aliases: [],
    section: "freemat",
    summary: "Elapsed Time Function",
    body: r#"
## Usage
The `etime` calculates the elapsed time between two `clock` vectors
`x1` and `x2`.  The syntax for its use is

```text
   y = etime(x1,x2)
```
where `x1` and `x2` are in the `clock` output format

```text
   x = [year month day hour minute seconds]
```

## Example
Here we use `etime` as a substitute for `tic` and `toc`

```fm
x1 = clock;
sleep(1);
x2 = clock;
etime(x2,x1);
```
"#,
}

fm_doc::register_doc! {
    name: "eval",
    aliases: [],
    section: "freemat",
    summary: "Evaluate a String",
    body: r#"
## Usage
The `eval` function evaluates a string.  The general syntax
for its use is

```text
   eval(s)
```
where `s` is the string to evaluate.  If `s` is an expression
(instead of a set of statements), you can assign the output
of the `eval` call to one or more variables, via

```text
   x = eval(s)
   [x,y,z] = eval(s)
```

Another form of `eval` allows you to specify an expression or
set of statements to execute if an error occurs.  In this
form, the syntax for `eval` is

```text
   eval(try_clause,catch_clause),
```
or with return values,

```text
   x = eval(try_clause,catch_clause)
   [x,y,z] = eval(try_clause,catch_clause)
```
These later forms are useful for specifying defaults.  Note that
both the `try_clause` and `catch_clause` must be expressions,
as the equivalent code is

```text
  try
    [x,y,z] = try_clause
  catch
    [x,y,z] = catch_clause
  end
```
so that the assignment must make sense in both cases.

## Example
Here are some examples of `eval` being used.

```fm
eval('a = 32')
b = eval('a')
```

The primary use of the `eval` statement is to enable construction
of expressions at run time.

```fm
s = ['b = a' ' + 2']
eval(s)
```

Here we demonstrate the use of the catch-clause to provide a
default value

```fm
a = 32
b = eval('a','1')
b = eval('z','a+1')
```

Note that in the second case, `b` takes the value of 33, indicating
that the evaluation of the first expression failed (because `z` is
not defined).
"#,
}

fm_doc::register_doc! {
    name: "evalin",
    aliases: [],
    section: "freemat",
    summary: "Evaluate a String in Workspace",
    body: r#"
## Usage
The `evalin` function is similar to the `eval` function, with an additional
argument up front that indicates the workspace that the expressions are to
be evaluated in.  The various syntaxes for `evalin` are:

```text
   evalin(workspace,expression)
   x = evalin(workspace,expression)
   [x,y,z] = evalin(workspace,expression)
   evalin(workspace,try_clause,catch_clause)
   x = evalin(workspace,try_clause,catch_clause)
   [x,y,z] = evalin(workspace,try_clause,catch_clause)
```
The argument `workspace` must be either 'caller' or 'base'.  If it is
'caller', then the expression is evaluated in the caller's work space.
That does not mean the caller of `evalin`, but the caller of the current
function or script.  On the other hand if the argument is 'base', then
the expression is evaluated in the base work space.   See `eval` for
details on the use of each variation.
"#,
}

fm_doc::register_doc! {
    name: "exit",
    aliases: [],
    section: "freemat",
    summary: "Exit Program",
    body: r#"
## Usage
The usage is

```text
   exit
```
Quits FreeMat.  This script is a simple synonym for `quit`.
"#,
}

fm_doc::register_doc! {
    name: "feval",
    aliases: [],
    section: "freemat",
    summary: "Evaluate a Function",
    body: r#"
## Usage
The `feval` function executes a function using its name.
The syntax of `feval` is

```text
  [y1,y2,...,yn] = feval(f,x1,x2,...,xm)
```
where `f` is the name of the function to evaluate, and
`xi` are the arguments to the function, and `yi` are the
return values.

Alternately, `f` can be a function handle to a function
(see the section on `function handles` for more information).

Finally, FreeMat also supports `f` being a user defined class
in which case it will atttempt to invoke the `subsref` method
of the class.

## Example
Here is an example of using `feval` to call the `cos`
function indirectly.

```fm
feval('cos',pi/4)
```

Now, we call it through a function handle

```fm
c = @cos
feval(c,pi/4)
```

Here we construct an inline object (which is a user-defined class)
and use `feval` to call it

```fm
afunc = inline('cos(t)+sin(t)','t')
feval(afunc,pi)
afunc(pi)
```

In both cases, (the `feval` call and the direct invokation), FreeMat
calls the `subsref` method of the class, which computes the requested
function.
"#,
}

fm_doc::register_doc! {
    name: "filesep",
    aliases: [],
    section: "freemat",
    summary: "Directory Separation Character",
    body: r#"
## Usage
The `filesep` routine returns the character used to separate directory
names on the current platform (basically, a forward slash for Windows,
and a backward slash for all other OSes).  The syntax is simple:

```text
  x = filesep
```
"#,
}

fm_doc::register_doc! {
    name: "help",
    aliases: [],
    section: "freemat",
    summary: "Help",
    body: r#"
## Usage
Displays help on a function available in FreeMat.  The help function
takes one argument:

```text
  help topic
```
where `topic` is the topic to look for help on.  For scripts, the
result of running `help` is the contents of the comments at the top
of the file.  If FreeMat finds no comments, then it simply displays
the function declaration.
"#,
}

fm_doc::register_doc! {
    name: "helpwin",
    aliases: [],
    section: "freemat",
    summary: "Online Help Window",
    body: r#"
## Usage
Brings up the online help window with the FreeMat manual.  The
`helpwin` function takes no arguments:

```text
  helpwin
  helpwin FunctionName
```
"#,
}

fm_doc::register_doc! {
    name: "jitcontrol",
    aliases: [],
    section: "freemat",
    summary: "Control the Just In Time Compiler",
    body: r#"
## Usage
The `jitcontrol` functionality in FreeMat allows you to control
the use of the Just In Time (JIT) compiler.  Starting in FreeMat
version 4, the JIT compiler is enabled by default on all platforms
where it is successfully built.  The JIT compiler should significantly
improve the performance of loop intensive, scalar code.  As development
progresses, more and more functionality will be enabled under the JIT.
In the mean time (if you use the GUI version of FreeMat) you can use
the JIT chat window to get information on why your code was JIT compiled
(or not).
"#,
}

fm_doc::register_doc! {
    name: "mfilename",
    aliases: [],
    section: "freemat",
    summary: "Name of Current Function",
    body: r#"
## Usage
Returns a string describing the name of the current function.  For M-files
this string will be the complete filename of the function.  This is true even
for subfunctions.  The syntax for its use is

```text
    y = mfilename
```
"#,
}

fm_doc::register_doc! {
    name: "path",
    aliases: [],
    section: "freemat",
    summary: "Get or Set FreeMat Path",
    body: r#"
## Usage
The `path` routine has one of the following syntaxes.  In the first form

```text
  x = path
```
`path` simply returns the current path.  In the second, the current path
is replaced by the argument string `'thepath'`

```text
  path('thepath')
```
In the third form, a new path is appended to the current search path

```text
  path(path,'newpath')
```
In the fourth form, a new path is prepended to the current search path

```text
  path('newpath',path)
```
In the final form, the path command prints out the current path

```text
  path
```
"#,
}

fm_doc::register_doc! {
    name: "pathsep",
    aliases: [],
    section: "freemat",
    summary: "Path Directories Separation Character",
    body: r#"
## Usage
The `pathsep` routine returns the character used to separate multiple directories
on a path string for the current platform (basically, a semicolon for Windows,
and a regular colon  for all other OSes).  The syntax is simple:

```text
  x = pathsep
```
"#,
}

fm_doc::register_doc! {
    name: "pathtool",
    aliases: [],
    section: "freemat",
    summary: "Open Path Setting Tool",
    body: r#"
## Usage
Brings up the pathtool dialog.  The `pathtool` function takes
no arguments:

```text
  pathtool
```
"#,
}

fm_doc::register_doc! {
    name: "pcode",
    aliases: [],
    section: "freemat",
    summary: "Convert a Script or Function to P-Code",
    body: r#"
## Usage
Writes out a script or function as a P-code function.
The general syntax for its use is:

```text
   pcode fun1 fun2 ...
```
The compiled functions are written to the current
directory.
"#,
}

fm_doc::register_doc! {
    name: "profiler",
    aliases: [],
    section: "freemat",
    summary: "Control Profiling",
    body: r#"
## Usage
The `profile` function allows you to control the FreeMat profiler.
It has two modes of operation.  The first is to enable-disable
the profiler.  To turn on profiling:

```text
  profiler on
```
to turn off profiling, use

```text
  profiler off
```
Note that regardless of the state of the profiler, only functions
and scripts are profiled.  Commands entered on the command line
are not profiled.  To see information that has accumulated in a
profile, you use the variant of the command:

```text
  profiler list
```
which lists current sorted profiling resuls. You can use this form to obtain
profiler results as a cell array

```text
  r=profiler('list')
```
If you want to see current profile
status issue a `profile` command with no arguments.

```text
   profiler
```
"#,
}

fm_doc::register_doc! {
    name: "quiet",
    aliases: [],
    section: "freemat",
    summary: "Control the Verbosity of the Interpreter",
    body: r#"
## Usage
The `quiet` function controls how verbose the interpreter
is when executing code.  The syntax for the function is

```text
   quiet flag
```
where `flag` is one of
- `'normal'` - normal output from the interpreter

- `'quiet'` - only intentional output (e.g. `printf` calls and
`disp` calls) is printed.  The output of expressions that are not
terminated in semicolons are not printed.

- `'silent'` - nothing is printed to the output.

The `quiet` command also returns the current quiet flag.
"#,
}

fm_doc::register_doc! {
    name: "quit",
    aliases: [],
    section: "freemat",
    summary: "Quit Program",
    body: r#"
## Usage
The `quit` statement is used to immediately exit the FreeMat
application.  The syntax for its use is

```text
   quit
```
"#,
}

fm_doc::register_doc! {
    name: "rehash",
    aliases: [],
    section: "freemat",
    summary: "Rehash Directory Caches",
    body: r#"
## Usage
Usually, FreeMat will automatically determine when M Files have
changed, and pick up changes you have made to M files.  Sometimes,
you have to force a refresh.  Use the `rehash` command for this
purpose.  The syntax for its use is

```text
  rehash
```
"#,
}

fm_doc::register_doc! {
    name: "rescan",
    aliases: [],
    section: "freemat",
    summary: "Rescan M Files for Changes",
    body: r#"
## Usage
Usually, FreeMat will automatically determine when M Files have
changed, and pick up changes you have made to M files.  Sometimes,
you have to force a refresh.  Use the `rescan` command for this
purpose.  The syntax for its use is

```text
  rescan
```
"#,
}

fm_doc::register_doc! {
    name: "rootpath",
    aliases: [],
    section: "freemat",
    summary: "Set FreeMat Root Path",
    body: r#"
## Usage
In order to function properly, FreeMat needs to know where to
find the `toolbox` directory as well as the `help` directory.
These directories are located on what is known as the `root path`.
Normally, FreeMat should know where these directories are located.
However under some circumstances (usually when FreeMat is installed
into a non-default location), it may be necessary to indicate
a different root path location, or to specify a particular one.
Note that on the Mac OS platform, FreeMat is installed as a bundle,
and will use the toolbox that is installed in the bundle regardless of
the setting for `rootpath`.
For Linux, FreeMat will typically use `/usr/local/share/FreeMat-\<Version\>/`
for the root path.  Installations from source code will generally work,
but binary installations (e.g., from an `RPM`) may need to have the
rootpath set.

The `rootpath` function has two forms.  The first form takes no arguments
and returns the current root path

```text
   rootpath
```
The second form will set a rootpath directly from the command line

```text
   rootpath(path)
```
where `path` is the full path to where the `toolbox` and `help`
directories are located.  For example, `rootpath('/usr/share/FreeMat-4.0')`.
The third form enables the GUI form

```text
   rootpath gui
```
which activates a dialog box to pick a directory that is the root directory
of the FreeMat installation (e.g., where `help` and `toolbox` are located.
Changes to `rootpath` are persistent (you do not need to run it every
time you start FreeMat).
"#,
}

fm_doc::register_doc! {
    name: "saveretvalue",
    aliases: [],
    section: "freemat",
    summary: "Save Return Value Of Function",
    body: r#"
## Usage
saves the given argument value for return when FreeMat (the application)
exits.
"#,
}

fm_doc::register_doc! {
    name: "simkeys",
    aliases: [],
    section: "freemat",
    summary: "Simulate Keypresses from the User",
    body: r#"
## Usage
This routine simulates keystrokes from the user on FreeMat.
The general syntax for its use is

```text
   otext = simkeys(text)
```
where `text` is a string to simulate as input to the console.
The output of the commands are captured and returned in the
string `otext`.  This is primarily used by the testing
infrastructure.
"#,
}

fm_doc::register_doc! {
    name: "sleep",
    aliases: [],
    section: "freemat",
    summary: "Sleep For Specified Number of Seconds",
    body: r#"
## Usage
Suspends execution of FreeMat for the specified number
of seconds.  The general syntax for its use is

```text
  sleep(n),
```
where `n` is the number of seconds to wait.
"#,
}

fm_doc::register_doc! {
    name: "source",
    aliases: [],
    section: "freemat",
    summary: "Execute an Arbitrary File",
    body: r#"
## Usage
The `source` function executes the contents of the given
filename one line at a time (as if it had been typed at
the `-->` prompt).  The `source` function syntax is

```text
  source(filename)
```
where `filename` is a `string` containing the name of
the file to process.

## Example
First, we write some commands to a file (note that it does
not end in the usual `.m` extension):

```fm-file:source_test
a = 32;
b = a;
printf('a is %d and b is %d\n',a,b);
```

```text
     source_test
```

Now we source the resulting file.

```fm-exec
clear a b
source source_test
```
"#,
}

fm_doc::register_doc! {
    name: "startup",
    aliases: [],
    section: "freemat",
    summary: "Startup Script",
    body: r#"
## Usage
Upon starting, FreeMat searches for a script names `startup.m`, and
if it finds it, it executes it.  This script can be in the current
directory, or on the FreeMat path (set using `setpath`).  The contents
of startup.m must be a valid script (not a function).
"#,
}

fm_doc::register_doc! {
    name: "tic",
    aliases: [],
    section: "freemat",
    summary: "Start Stopwatch Timer",
    body: r#"
## Usage
Starts the stopwatch timer, which can be used to time tasks in FreeMat.
The `tic` takes no arguments, and returns no outputs.  You must use
`toc` to get the elapsed time.  The usage is

```text
  tic
```

## Example
Here is an example of timing the solution of a large matrix equation.

```fm
A = rand(100);
b = rand(100,1);
tic; c = A\b; toc
```
"#,
}

fm_doc::register_doc! {
    name: "toc",
    aliases: [],
    section: "freemat",
    summary: "Stop Stopwatch Timer",
    body: r#"
## Usage
Stop the stopwatch timer, which can be used to time tasks in FreeMat.
The `toc` function takes no arguments, and returns no outputs.  You must use
`toc` to get the elapsed time.  The usage is

```text
  toc
```

## Example
Here is an example of timing the solution of a large matrix equation.

```fm
A = rand(100);
b = rand(100,1);
tic; c = A\b; toc
```
"#,
}

fm_doc::register_doc! {
    name: "version",
    aliases: [],
    section: "freemat",
    summary: "The Current Version Number",
    body: r#"
## Usage
The `version` function returns the current version number for
FreeMat (as a string).  The general syntax for its use is

```text
    v = version
```

## Example
The current version of FreeMat is

```fm
version
```
"#,
}

fm_doc::register_doc! {
    name: "verstring",
    aliases: [],
    section: "freemat",
    summary: "The Current Version String",
    body: r#"
## Usage
The `verstring` function returns the current version string for
FreeMat.  The general syntax for its use is

```text
    version = verstring
```

## Example
The current version of FreeMat is

```fm
verstring
```
"#,
}
