//! Migrated help docs for the `function` section (help-system P7).
//! GENERATED by `cargo xtask migrate-place` — do not edit by hand.

fm_doc::register_section! {
    id: "function",
    title: "Function Related Functions",
    summary: "Defining, querying, and manipulating functions.",
}

fm_doc::register_doc! {
    name: "inline",
    aliases: [],
    section: "function",
    summary: "Construct Inline Function",
    body: r#"
## Usage
Constructs an inline function object.  The syntax for its use is
either

```text
   y = inline(expr)
```
which uses the `symvar` function to identify the variables in the
expression, or the explicit form

```text
   y = inline(expr,var1,var2,...,varn)
```
where the variables are explicitly given.  Note that inline functions
are only partially supported in FreeMat.  If you need features of the
inline function that are not currently implemented, please file a
feature request at the FreeMat website.

## Example
Here we construct an inline expression using the autodetection
of `symvar`

```fm
a = inline('x^2')
a(3)
a(i)
```

In this case, we have multiple arguments (again, autodetected)

```fm
a = inline('x+y-cos(x+y)')
a(pi,-pi)
```

In this form, we specify which arguments we want to use (thereby
also specifying the order of the arguments

```fm
a = inline('x+t-sin(x)','x','t')
a(0.5,1)
```

Inline objects can also be used with `feval`

```fm
a = inline('cos(t)')
feval(a,pi/2)
```
"#,
}

fm_doc::register_doc! {
    name: "symvar",
    aliases: [],
    section: "function",
    summary: "Find Symbolic Variables in an Expression",
    body: r#"
## Usage
Finds the symbolic variables in an expression.  The syntax for its
use is

```text
  syms = symvar(expr)
```
where `expr` is a string containing an expression, such as
`'x^2 + cos(t+alpha)'`.  The result is a cell array of strings
containing the non-function identifiers in the expression.  Because
they are usually not used as identifiers in expressions, the strings
 `'pi','inf','nan','eps','i','j'` are ignored.

## Example
Here are some simple examples:

```fm
symvar('x^2+sqrt(x)')  % sqrt is eliminated as a function
symvar('pi+3')         % No identifiers here
symvar('x + t*alpha')  % x, t and alpha
```
"#,
}
