//! Migrated help docs for the `functions` section (help-system P7).
//! GENERATED by `cargo xtask migrate-place` — do not edit by hand.

fm_doc::register_section! {
    id: "functions",
    title: "Functions and Scripts",
    summary: "Writing functions and scripts in the FreeMat language.",
}

fm_doc::register_doc! {
    name: "anonymous",
    aliases: [],
    section: "functions",
    summary: "Anonymous Functions",
    body: r#"
## Usage
Anonymous functions are simple, nameless functions that can be defined
anywhere (in a script, function, or at the prompt).  They are intended
to supplant `inline` functions.  The syntax for an anonymous function
is simple:

```text
   y = @(arg1,arg2,...,argn) expression
```
where `arg1,arg2,...,argn` is a list of valid identifiers that define
the arguments to the function, and `expression` is the expression to
compute in the function.  The returned value `y` is a function handle
for the anonymous function that can then be used to evaluate the expression.
Note that `y` will capture the value of variables that are not indicated
in the argument list from the current scope or workspace at the time
it is defined.  So, for example, consider the simple anonymous function
definition

```text
   y = @(x) a*(x+b)
```
In order for this definition to work, the variables `a` and `b` need to
be defined in the current workspace.  Whatever value they have is captured
in the function handle `y`.  To change the values of `a` and `b` in the
anonymous function, you must recreate the handle using another call.  See
the examples section for more information.  In order to use the anonymous
function, you can use it just like any other function handle.  For example,

```text
   p = y(3)
   p = y()
   p = feval(y,3)
```
are all examples of using the `y` anonymous function to perform a calculation.

## Examples
Here are some examples of using an anonymous function

```fm-exec
a = 2; b = 4;    % define a and b (slope and intercept)
y = @(x) a*x+b   % create the anonymous function
y(2)             % evaluate it for x = 2
a = 5; b = 7;    % change a and b
y(2)             % the value did not change!  because a=2,b=4 are captured in y
y = @(x) a*x+b   % recreate the function
y(2)             % now the new values are used
```
"#,
}

fm_doc::register_doc! {
    name: "func2str",
    aliases: [],
    section: "functions",
    summary: "Function to String conversion",
    body: r#"
## Usage
The `func2str` function converts a function pointer into a
string.  The syntax is

```text
    y = func2str(funcptr)
```
where `funcptr` is a function pointer.  If `funcptr` is a
pointer to a function, then `y` is the name of the function.
On the other hand, if `funcptr` is an anonymous function then
`func2str` returns the definition of the anonymous function.

## Example
Here is a simple example of using `func2str`

```fm-exec
y = @sin
x = func2str(y)
```

If we use an anonymous function, then `func2str`
returns the definition of the anonymous function

```fm-exec
y = @(x) x.^2
x = func2str(y)
```
"#,
}

fm_doc::register_doc! {
    name: "function",
    aliases: [],
    section: "functions",
    summary: "Function Declarations",
    body: r#"
## Usage
There are several forms for function declarations in FreeMat.
The most general syntax for a function declaration is the
following:

```text
  function [out_1,...,out_M,varargout] = fname(in_1,...,in_N,varargin)
```
where `out_i` are the output parameters, `in_i` are the input
parameters, and `varargout` and `varargin` are special keywords
used for functions that have variable inputs or outputs.  For
functions with a fixed number of input or output parameters, the
syntax is somewhat simpler:

```text
  function [out_1,...,out_M] = fname(in_1,...,in_N)
```
Note that functions that have no return arguments can omit
the return argument list (of `out_i`) and the equals sign:

```text
  function fname(in_1,...,in_N)
```
Likewise, a function with no arguments can eliminate the list
of parameters in the declaration:

```text
  function [out_1,...,out_M] = fname
```
Functions that return only a single value can omit the brackets

```text
  function out_1 = fname(in_1,...,in_N)
```

In the body of the function `in_i` are initialized with the
values passed when the function is called.  Also, the function
must assign values for `out_i` to pass values to the caller.
Note that by default, FreeMat passes arguments by value, meaning
that if we modify the contents of `in_i` inside the function,
it has no effect on any variables used by the caller.  Arguments
can be passed by reference by prepending an ampersand `&`
before the name of the input, e.g.

```text
  function [out1,...,out_M] = fname(in_1,&in_2,in_3,...,in_N)
```
in which case `in_2` is passed by reference and not by value.
Also, FreeMat works like `C` in that the caller does not have
to supply the full list of arguments.  Also, when `keywords`
(see help `keywords`) are used, an arbitrary subset of the
parameters may be unspecified. To assist in deciphering
the exact parameters that were passed,
FreeMat also defines two variables inside the function context:
`nargin` and `nargout`, which provide the number of input
and output parameters of the caller, respectively. See help for
`nargin` and `nargout` for more details.  In some
circumstances, it is necessary to have functions that
take a variable number of arguments, or that return a variable
number of results.  In these cases, the last argument to the
parameter list is the special argument `varargin`.  Inside
the function, `varargin` is a cell-array that contains
all arguments passed to the function that have not already
been accounted for.  Similarly, the function can create a
cell array named `varargout` for variable length output lists.
See help `varargin` and `varargout` for more details.

The function name `fname` can be any legal FreeMat identifier.
Functions are stored in files with the `.m` extension.  Note
that the name of the file (and not the function name `fname`
used in the declaration) is how the function appears in FreeMat.
So, for example, if the file is named `foo.m`, but the declaration
uses `bar` for the name of the function, in FreeMat, it will
still appear as function `foo`.  Note that this is only true
for the first function that appears in a `.m` file.  Additional
functions that appear after the first function are known as
`helper functions` or `local` functions.  These are functions that
can only be called by other functions in the same `.m` file.  Furthermore
the names of these helper functions are determined by their declaration
and not by the name of the `.m` file.  An example of using
helper functions is included in the examples.

Another important feature of functions, as opposed to, say `scripts`,
is that they have their own `scope`.  That means that variables
defined or modified inside a function do not affect the scope of the
caller.  That means that a function can freely define and use variables
without unintentionally using a variable name reserved elsewhere.  The
flip side of this fact is that functions are harder to debug than
scripts without using the `keyboard` function, because the intermediate
calculations used in the function are not available once the function
exits.

## Examples
Here is an example of a trivial function that adds its
first argument to twice its second argument:

```fm-file:addtest.m
function c = addtest(a,b)
  c = a + 2*b;
```

```text
     addtest.m
```

```fm-exec
addtest(1,3)
addtest(3,0)
```

Suppose, however, we want to replace the value of the first
argument by the computed sum.  A first attempt at doing so
has no effect:

```fm-file:addtest2.m
function addtest2(a,b)
  a = a + 2*b;
```

```text
     addtest2.m
```

```fm-exec
arg1 = 1
arg2 = 3
addtest2(arg1,arg2)
arg1
arg2
```

The values of `arg1` and `arg2` are unchanged, because they are
passed by value, so that any changes to `a` and `b` inside
the function do not affect `arg1` and `arg2`.  We can change
that by passing the first argument by reference:

```fm-file:addtest3.m
function addtest3(&a,b)
  a = a + 2*b
```

```text
     addtest3.m
```

Note that it is now illegal to pass a literal value for `a` when
calling `addtest3`:

```fm-exec
# errors: 1
addtest3(3,4)
addtest3(arg1,arg2)
arg1
arg2
```

The first example fails because we cannot pass a literal like the
number `3` by reference.  However, the second call succeeds, and
note that `arg1` has now changed.  Note: please be careful when
passing by reference - this feature is not available in MATLAB
and you must be clear that you are using it.

As variable argument and return functions are covered elsewhere,
as are keywords, we include one final example that demonstrates
the use of helper functions, or local functions, where
multiple function declarations occur in the same file.

```fm-file:euclidlength.m
function y = foo(x,y)
  square_me(x);
  square_me(y);
  y = sqrt(x+y);

function square_me(&t)
  t = t^2;
```

```text
     euclidlength.m
```

```fm-exec
euclidlength(3,4)
euclidlength(2,0)
```
"#,
}

fm_doc::register_doc! {
    name: "keywords",
    aliases: [],
    section: "functions",
    summary: "Function Keywords",
    body: r#"
## Usage
A feature of IDL that FreeMat has adopted is a modified
form of `keywords`.  The purpose of `keywords` is to
allow you to call a function with the arguments to the
function specified in an arbitrary order.  To specify
the syntax of `keywords`, suppose there is a function
with prototype

```text
  function [out_1,...,out_M] = foo(in_1,...,in_N)
```
Then the general syntax for calling function `foo` using keywords
is

```text
  foo(val_1, val_2, /in_k=3)
```
which is exactly equivalent to

```text
  foo(val_1, val_2, [], [], ..., [], 3),
```
where the 3 is passed as the k-th argument, or alternately,

```text
  foo(val_1, val_2, /in_k)
```
which is exactly equivalent to

```text
  foo(val_1, val_2, [], [], ..., [], logical(1)),
```
Note that you can even pass reference arguments using keywords.

## Example
The most common use of keywords is in controlling options for
functions.  For example, the following function takes a number
of binary options that control its behavior.  For example,
consider the following function with two arguments and two
options.  The function has been written to properly use and
handle keywords.  The result is much cleaner than the MATLAB
approach involving testing all possible values of `nargin`,
and forcing explicit empty brackets for don't care parameters.

```fm-file:keyfunc.m
function c = keyfunc(a,b,operation,printit)
  if (~isset('a') | ~isset('b'))
    error('keyfunc requires at least the first two 2 arguments');
  end;
  if (~isset('operation'))
    % user did not define the operation, default to '+'
    operation = '+';
  end
  if (~isset('printit'))
    % user did not specify the printit flag, default is false
    printit = 0;
  end
  % simple operation...
  eval(['c = a ' operation ' b;']);
  if (printit)
    printf('%f %s %f = %f\n',a,operation,b,c);
  end
```

```text
     keyfunc.m
```

Now some examples of how this function can be called using
`keywords`.

```fm
keyfunc(1,3)                % specify a and b, defaults for the others
keyfunc(1,3,/printit)       % specify printit is true
keyfunc(/operation='-',2,3) % assigns a=2, b=3
keyfunc(4,/operation='*',/printit) % error as b is unspecified
```
"#,
}

fm_doc::register_doc! {
    name: "nargin",
    aliases: [],
    section: "functions",
    summary: "Number of Input Arguments",
    body: r#"
## Usage
The `nargin` function returns the number of arguments passed
to a function when it was called.  The general syntax for its
use is

```text
  y = nargin
```
FreeMat allows for
fewer arguments to be passed to a function than were declared,
and `nargin`, along with `isset` can be used to determine
exactly what subset of the arguments were defined.

You can also use `nargin` on a function handle to return the
number of input arguments expected by the function

```text
  y = nargin(fun)
```
where `fun` is the name of the function (e.g. `'sin'`) or
a function handle.

## Example
Here is a function that is declared to take five
arguments, and that simply prints the value of `nargin`
each time it is called.

```fm-file:nargintest.m
function nargintest(a1,a2,a3,a4,a5)
  printf('nargin = %d\n',nargin);
```

```text
     nargintest.m
```

```fm-exec
nargintest(3);
nargintest(3,'h');
nargintest(3,'h',1.34);
nargintest(3,'h',1.34,pi,e);
nargin('sin')
y = @sin
nargin(y)
```
"#,
}

fm_doc::register_doc! {
    name: "nargout",
    aliases: [],
    section: "functions",
    summary: "Number of Output Arguments",
    body: r#"
## Usage
The `nargout` function computes the number of return values requested from
a function when it was called.  The general syntax for its use

```text
   y = nargout
```
FreeMat allows for
fewer return values to be requested from a function than were declared,
and `nargout` can be used to determine exactly what subset of
the functions outputs are required.

You can also use `nargout` on a function handle to return the
number of input arguments expected by the function

```text
  y = nargout(fun)
```
where `fun` is the name of the function (e.g. `'sin'`) or
a function handle.

## Example
Here is a function that is declared to return five
values, and that simply prints the value of `nargout`
each time it is called.

```fm-file:nargouttest.m
function [a1,a2,a3,a4,a5] = nargouttest
  printf('nargout = %d\n',nargout);
  a1 = 1; a2 = 2; a3 = 3; a4 = 4; a5 = 5;
```

```text
     nargouttest.m
```

```fm-exec
a1 = nargouttest
[a1,a2] = nargouttest
[a1,a2,a3] = nargouttest
[a1,a2,a3,a4,a5] = nargouttest
nargout('sin')
y = @sin
nargout(y)
```
"#,
}

fm_doc::register_doc! {
    name: "script",
    aliases: [],
    section: "functions",
    summary: "Script Files",
    body: r#"
## Usage
A script is a sequence of FreeMat commands contained in a
`.m` file.  When the script is called (via the name of the
file), the effect is the same as if the commands inside the
script file were issued one at a time from the keyboard.
Unlike `function` files (which have the same extension,
but have a `function` declaration), script files share
the same environment as their callers.  Hence, assignments,
etc, made inside a script are visible to the caller (which
is not the case for functions.

## Example
Here is an example of a script that makes some simple
assignments and `printf` statements.

```fm-file:tscript.m
a = 13;
printf('a is %d\n',a);
b = a + 32
```

```text
     tscript.m
```

If we execute the script and then look at the defined variables

```fm-exec
tscript
who
```

we see that `a` and `b` are defined appropriately.
"#,
}

fm_doc::register_doc! {
    name: "special",
    aliases: [],
    section: "functions",
    summary: "Special Calling Syntax",
    body: r#"
## Usage
To reduce the effort to call certain functions, FreeMat supports
a special calling syntax for functions that take string arguments.
In particular, the three following syntaxes are equivalent, with
one caveat:

```text
   functionname('arg1','arg2',...,'argn')
```
or the parenthesis and commas can be removed

```text
   functionname 'arg1' 'arg2' ... 'argn'
```
The quotes are also optional (providing, of course, that the
argument strings have no spaces in them)

```text
   functionname arg1 arg2 ... argn
```
This special syntax enables you to type `hold on` instead of
the more cumbersome `hold('on')`.  The caveat is that FreeMat
currently only recognizes the special calling syntax as the
first statement on a line of input.  Thus, the following construction

```text
  for i=1:10; plot(vec(i)); hold on; end
```
would not work.  This limitation may be removed in a future
version.

## Example
Here is a function that takes two string arguments and
returns the concatenation of them.

```fm-file:strcattest.m
function strcattest(str1,str2)
  str3 = [str1,str2];
  printf('str1 = %s, str2 = %s, str3 = %s\n',str1,str2,str3);
```

```text
     strcattest.m
```

We call `strcattest` using all three syntaxes.

```fm-exec
strcattest('hi','ho')
strcattest 'hi' 'ho'
strcattest hi ho
```
"#,
}

fm_doc::register_doc! {
    name: "str2func",
    aliases: [],
    section: "functions",
    summary: "String to Function conversion",
    body: r#"
## Usage
The `str2func` function converts a function name into a
function pointer.  The syntax is

```text
    y = str2func('funcname')
```
where `funcname` is the name of the function. The return
variable `y` is a function handle that points to the given
function.

An alternate syntax is used to construct an anonymous function
given an expression.  They syntax is

```text
    y = str2func('anonymous def')
```
where `anonymous def` is an expression that defines an
anonymous function, for example `'@(x) x.^2'`.

## Example
Here is a simple example of using `str2func`.

```fm-exec
sin(.5)              % Calling the function directly
y = str2func('sin')  % Convert it into a function handle
y(.5)                % Calling 'sin' via the function handle
```

Here we use `str2func` to define an anonymous function

```fm-exec
y = str2func('@(x) x.^2')
y(2)
```
"#,
}

fm_doc::register_doc! {
    name: "varargin",
    aliases: [],
    section: "functions",
    summary: "Variable Input Arguments",
    body: r#"
## Usage
FreeMat functions can take a variable number of input arguments
by setting the last argument in the argument list to `varargin`.
This special keyword indicates that all arguments to the
function (beyond the last non-`varargin` keyword) are assigned
to a cell array named `varargin` available to the function.
Variable argument functions are usually used when writing
driver functions, i.e., functions that need to pass arguments
to another function.  The general syntax for a function that
takes a variable number of arguments is

```text
  function [out_1,...,out_M] = fname(in_1,..,in_M,varargin)
```
Inside the function body, `varargin` collects the arguments
to `fname` that are not assigned to the `in_k`.

## Example
Here is a simple wrapper to `feval` that demonstrates the
use of variable arguments functions.

```fm-file:wrapcall.m
function wrapcall(fname,varargin)
  feval(fname,varargin{:});
```

```text
     wrapcall.m
```

Now we show a call of the `wrapcall` function with a number
of arguments

```fm-exec
wrapcall('printf','%f...%f\n',pi,e)
```

A more serious driver routine could, for example, optimize
a one dimensional function that takes a number of auxilliary
parameters that are passed through `varargin`.
"#,
}

fm_doc::register_doc! {
    name: "varargout",
    aliases: [],
    section: "functions",
    summary: "Variable Output Arguments",
    body: r#"
## Usage
FreeMat functions can return a variable number of output arguments
by setting the last argument in the argument list to `varargout`.
This special keyword indicates that the number of return values
is variable.  The general syntax for a function that returns
a variable number of outputs is

```text
  function [out_1,...,out_M,varargout] = fname(in_1,...,in_M)
```
The function is responsible for ensuring that `varargout` is
a cell array that contains the values to assign to the outputs
beyond `out_M`.  Generally, variable output functions use
`nargout` to figure out how many outputs have been requested.

## Example
This is a function that returns a varying number of values
depending on the value of the argument.

```fm-file:varoutfunc.m
function [varargout] = varoutfunc
  switch(nargout)
    case 1
      varargout = {'one of one'};
    case 2
      varargout = {'one of two','two of two'};
    case 3
      varargout = {'one of three','two of three','three of three'};
  end
```

```text
     varoutfunc.m
```

Here are some examples of exercising `varoutfunc`:

```fm-exec
[c1] = varoutfunc
[c1,c2] = varoutfunc
[c1,c2,c3] = varoutfunc
```
"#,
}
