//! Migrated help docs for the `glwin` section (help-system P7).
//! GENERATED by `cargo xtask migrate-place` — do not edit by hand.

fm_doc::register_section! {
    id: "glwin",
    title: "OpenGL Models",
    summary: "OpenGL-based 3-D model display.",
}

fm_doc::register_doc! {
    name: "glassembly",
    aliases: [],
    section: "glwin",
    summary: "Create a GL Assembly",
    body: r#"
## Usage
Define a GL Assembly.  A GL Assembly consists of one or more
GL Nodes or GL Assemblies that are placed relative to the
coordinate system of the assembly.  For example, if we have
`glnode` definitions for `'bread'` and `'cheese'`, then
a `glassembly` of sandwich would consist of placements of
two `'bread'` nodes with a `'cheese'` node in between.
Furthermore, a `'lunch'` assembly could consist of a `'sandwich'`
a `'chips'` and `'soda'`.  Hopefully, you get the idea.  The
syntax for the `glassembly` command is

```text
   glassembly(name,part1,transform1,part2,transform2,...)
```
where `part1` is the name of the first part, and could be
either a `glnode` or itself be another `glassembly`.
Here `transform1` is the `4 x 4 matrix` that transforms
the part into the local reference coordinate system.

WARNING!! Currently FreeMat does not detect or gracefully handle
self-referential assemblies (i.e, if you try to make a `sandwich`
contain a `sandwich`, which you can do by devious methods that I
refuse to explain).  Do not do this!  You have been warned.
"#,
}

fm_doc::register_doc! {
    name: "glclump",
    aliases: [],
    section: "glwin",
    summary: "Create a GL Clump",
    body: r#"
## Usage
Defines an aggregate clump of objects that can be treated
as a node.  A GL Clump is defined by a vector consisting
of the following elements:

```text
   [r1 g1 b1 n1 p1 p2 p3 ... r2 g2 b2 n2 p1 p2 p3 ... ]
```
i.e., an RGB color spec, followed by a point count `ni`, followed
by a length `ni` vector of coordinates that are `x,y,z` triplets.
The usage of this function is

```text
   glclump(name,vector)
```
where `name` is the name of the clump and `vector` is the aforementioned
vector of points.
"#,
}

fm_doc::register_doc! {
    name: "gldefmaterial",
    aliases: [],
    section: "glwin",
    summary: "Defines a GL Material",
    body: r#"
## Usage
Define a material.  The syntax for its use is

```text
  gldefmaterial(name,ambient,diffuse,specular,shininess)
```
where `name` is the name of the material, and `ambient`
is a `4 x 1` vector containing the ambient component of
the material property, and `diffuse` is a `4 x 1` vector
and `specular` is a `4 x 1` vector containing the specular
component of the material properties and `shininess` is
the exponent that governs the shinines of the material.
"#,
}

fm_doc::register_doc! {
    name: "gllines",
    aliases: [],
    section: "glwin",
    summary: "Create a GL Lineset",
    body: r#"
## Usage
Defines a set of lines that can be treated as a node.
A GL Lines is defined by a vector consisting of the
following elements:

```text
   [m1 x1 y1 z1 ... xn yn zn m2 x1 y1 z1 .... ]
```
i.e., a point count followed by that number of triplets.
The usage of this function is

```text
  gllines(name,vector,color)
```
where `name` is the name of the lineset and `vector`
is the aforementioned vector of points.
"#,
}

fm_doc::register_doc! {
    name: "glnode",
    aliases: [],
    section: "glwin",
    summary: "Create a GL Node",
    body: r#"
## Usage
Define a GL Node.  A GL Node is an object that can be displayed
in a GL Window.  It is defined by a triangular mesh of vertices.
It must also have a material that defines its appearance (i.e.
color, shininess, etc.).  The syntax for the `glnode` command
is

```text
  glnode(name,material,pointset)  
```
where `material` is the name of a material that has already been
defined with `gldefmaterial`, `pointset` is a `3 x N` matrix
of points that define the geometry of the object.  Note that the points
are assumed to be connected in triangular facts, with the points
defined counter clock-wise as seen from the outside of the facet.
`FreeMat` will compute the normals.  The `name` argument must
be unique.  If you want multiple instances of a given `glnode`
in your GLWindow, that is fine, as instances of a `glnode` are
created through a `glassembly`.
"#,
}
