//! Migrated help docs for the `inspection` section (help-system P7).
//! GENERATED by `cargo xtask migrate-place` — do not edit by hand.

fm_doc::register_section! {
    id: "inspection",
    title: "Inspection Functions",
    summary: "Inspect variables, types, sizes, and the workspace.",
}

fm_doc::register_doc! {
    name: "clear",
    aliases: [],
    section: "inspection",
    summary: "Clear or Delete a Variable",
    body: r#"
## Usage
Clears a set of variables from the current context, or alternately,
delete all variables defined in the current context.  There are
several formats for the function call.  The first is the explicit form
in which a list of variables are provided:

```text
   clear a1 a2 ...
```
The variables can be persistent or global, and they will be deleted.
The second form

```text
   clear 'all'
```
clears all variables and libraries from the current context.  Alternately, you can
use the form:

```text
   clear 'libs'
```
which will unload any libraries or DLLs that have been `import`ed.
Optionally, you can specify that persistent variables should be cleared via:

```text
   clear 'persistent'
```
and similarly for global variables:

```text
   clear 'global'
```
You can use

```text
   clear 'classes'
```
to clear all definitions of user-defined classes.
With no arguments, `clear` defaults to clearing `'all'`.

## Example
Here is a simple example of using `clear` to delete a variable.  First, we create a variable called `a`:

```fm-exec
a = 53
```

Next, we clear `a` using the `clear` function, and verify that it is deleted.

```fm-exec
# errors: 1
clear a
a
```
"#,
}

fm_doc::register_doc! {
    name: "end",
    aliases: [],
    section: "inspection",
    summary: "End Function",
    body: r#"
## Usage
Computes the size of a variable along a given dimension.  The syntax
for its use is

```text
   y = end(x,dim,subindexes)
```
where `x` is the array to be analyzed, `dim` is the dimension along
which to compute the end, and `subindexes` indicates how many dimensions
are involved in the `end` calculation.
"#,
}

fm_doc::register_doc! {
    name: "exist",
    aliases: [],
    section: "inspection",
    summary: "Test for Existence",
    body: r#"
## Usage
Tests for the existence of a variable, function, directory or
file.  The general syntax for its use is

```text
  y = exist(item,kind)
```
where `item` is a string containing the name of the item
to look for, and `kind` is a string indicating the type
of the search.  The `kind` must be one of
- `'builtin'` checks for built-in functions

- `'dir'` checks for directories

- `'file'` checks for files

- `'var'` checks for variables

- `'all'` checks all possibilities (same as leaving out `kind`)

You can also leave the `kind` specification out, in which case
the calling syntax is

```text
  y = exist(item)
```
The return code is one of the following:
- 0 - if `item` does not exist

- 1 - if `item` is a variable in the workspace

- 2 - if `item` is an M file on the search path, a full pathname
 to a file, or an ordinary file on your search path

- 5 - if `item` is a built-in FreeMat function

- 7 - if `item` is a directory

Note: previous to version `1.10`, `exist` used a different notion
of existence for variables: a variable was said to exist if it
was defined and non-empty.  This test is now performed by `isset`.

## Example
Some examples of the `exist` function.  Note that generally `exist`
is used in functions to test for keywords.  For example,

```text
  function y = testfunc(a, b, c)
  if (~exist('c'))
    % c was not defined, so establish a default
    c = 13;
  end
  y = a + b + c;
```
An example of `exist` in action.

```fm-exec
a = randn(3,5,2)
b = []
who
exist('a')
exist('b')
exist('c')
```
"#,
}

fm_doc::register_doc! {
    name: "fieldnames",
    aliases: [],
    section: "inspection",
    summary: "Fieldnames of a Structure",
    body: r#"
## Usage
Returns a cell array containing the names of the fields in
a structure array.  The syntax for its use is

```text
   x = fieldnames(y)
```
where `y` is a structure array of object array.  The result
is a cell array, with one entry per field in `y`.

## Example
We define a simple structure array:

```fm-exec
y.foo = 3; y.goo = 'hello';
x = fieldnames(y)
```
"#,
}

fm_doc::register_doc! {
    name: "isa",
    aliases: [],
    section: "inspection",
    summary: "Test Type of Variable",
    body: r#"
## Usage
Tests the type of a variable.  The syntax for its
use is

```text
   y = isa(x,type)
```
where `x` is the variable to test, and `type` is
the type.  Supported built-in types are
- `'cell'` for cell-arrays

- `'struct'` for structure-arrays

- `'logical'` for logical arrays

- `'uint8'` for unsigned 8-bit integers

- `'int8'` for signed 8-bit integers

- `'uint16'` for unsigned 16-bit integers

- `'int16'` for signed 16-bit integers

- `'uint32'` for unsigned 32-bit integers

- `'int32'` for signed 32-bit integers

- `'uint64'` for unsigned 64-bit integers

- `'int64'` for signed 64-bit integers

- `'single'` for 32-bit floating point numbers

- `'double'` for 64-bit floating point numbers

- `'char'` for string arrays

If the argument is a user-defined type (via the `class` function), then
the name of that class is returned.

## Examples
Here are some examples of the `isa` call.

```fm-exec
a = {1}
isa(a,'char')
isa(a,'cell')
```

Here we use `isa` along with shortcut boolean evaluation to
safely determine if a variable contains the string `'hello'`

```fm-exec
a = 'hello'
isa(a,'char') && strcmp(a,'hello')
```
"#,
}

fm_doc::register_doc! {
    name: "iscell",
    aliases: [],
    section: "inspection",
    summary: "Test For Cell Array",
    body: r#"
## Usage
The syntax for `iscell` is

```text
   x = iscell(y)
```
and it returns a logical 1 if the argument is a cell array
and a logical 0 otherwise.

## Example
Here are some examples of `iscell`

```fm-exec
iscell('foo')
iscell(2)
iscell({1,2,3})
```
"#,
}

fm_doc::register_doc! {
    name: "iscellstr",
    aliases: [],
    section: "inspection",
    summary: "Test For Cell Array of Strings",
    body: r#"
## Usage
The syntax for `iscellstr` is

```text
   x = iscellstr(y)
```
and it returns a logical 1 if the argument is a cell array
in which every cell is a character array (or is empty), and
a logical 0 otherwise.

## Example
Here is a simple example

```fm-exec
A = {'Hello','Yellow';'Mellow','Othello'}
iscellstr(A)
```
"#,
}

fm_doc::register_doc! {
    name: "ischar",
    aliases: [],
    section: "inspection",
    summary: "Test For Character Array (string)",
    body: r#"
## Usage
The syntax for `ischar` is

```text
   x = ischar(y)
```
and it returns a logical 1 if the argument is a string
and a logical 0 otherwise.
"#,
}

fm_doc::register_doc! {
    name: "isempty",
    aliases: [],
    section: "inspection",
    summary: "Test For Variable Empty",
    body: r#"
## Usage
The `isempty` function returns a boolean that indicates
if the argument variable is empty or not.  The general
syntax for its use is

```text
  y = isempty(x).
```

## Examples
Here are some examples of the `isempty` function

```fm-exec
a = []
isempty(a)
b = 1:3
isempty(b)
```

Note that if the variable is not defined, `isempty`
does not return true.

```fm-exec
# errors: 1
clear x
isempty(x)
```
"#,
}

fm_doc::register_doc! {
    name: "isequal",
    aliases: [],
    section: "inspection",
    summary: "Test For Matrix Equality",
    body: r#"
## Usage
Test two arrays for equality.  The general format
for its use is

```text
   y = isequal(a,b)
```
This function returns true if the two arrays are
equal (compared element-wise).  Unlike `issame`
the `isequal` function will type convert where
possible to do the comparison.
"#,
}

fm_doc::register_doc! {
    name: "isequalwithequalnans",
    aliases: [],
    section: "inspection",
    summary: "Test For Matrix Equality",
    body: r#"
## Usage
Test two arrays for equality, with NaNs being equal.  The general format
for its use is

```text
   y = isequalwithequalnans(a,b)
```
This function returns true if the two arrays are
equal (compared element-wise).  Unlike `issame`
the `isequalwithequalnans` function will type convert where
possible to do the comparison.
"#,
}

fm_doc::register_doc! {
    name: "isfield",
    aliases: [],
    section: "inspection",
    summary: "Test for Existence of a Structure Field",
    body: r#"
## Usage
Given a structure array, tests to see if that structure
array contains a field with the given name.  The syntax
for its use is

```text
  y = isfield(x,field)
```
and returns a logical `1` if `x` has a field with the
name `field` and a logical `0` if not.  It also returns
a logical `0` if the argument `x` is not a structure array.

## Example
Here we define a simple struct, and then test for some
fields

```fm-exec
a.foo = 32
a.goo = 64
isfield(a,'goo')
isfield(a,'got')
isfield(pi,'round')
```
"#,
}

fm_doc::register_doc! {
    name: "ishandle",
    aliases: [],
    section: "inspection",
    summary: "Test for Graphics Handle",
    body: r#"
## Usage
Given a constant, this routine will test to see if the
constant is a valid graphics handle or not.  The syntax
for its use is

```text
  y = ishandle(h,type)
```
and returns a logical `1` if `x` is a handle of type `type`
and a logical `0` if not.
"#,
}

fm_doc::register_doc! {
    name: "isinf",
    aliases: [],
    section: "inspection",
    summary: "Test for infinities",
    body: r#"
## Usage
Returns true for entries of an array that are infs (i.e.,
infinities).  The usage is

```text
   y = isinf(x)
```
The result is a logical array of the same size as `x`,
which is true if `x` is not-a-number, and false otherwise.
Note that for `complex` or `dcomplex` data types that
the result is true if either the real or imaginary parts
are infinite.

## Example
Suppose we have an array of floats with one element that
is `inf`:

```fm-exec
a = [1.2 3.4 inf 5]
isinf(a)
b = 3./[2 5 0 3 1]
```
"#,
}

fm_doc::register_doc! {
    name: "isinttype",
    aliases: [],
    section: "inspection",
    summary: "Test For Integer-type Array",
    body: r#"
## Usage
The syntax for `isinttype` is

```text
   x = isinttype(y)
```
and it returns a logical 1 if the argument is an integer type
and a logical 0 otherwise.  Note that this function only tests
the type of the variable, not the value.  So if, for example,
`y` is a `float` array containing all integer values, it will
still return a logical 0.
"#,
}

fm_doc::register_doc! {
    name: "islogical",
    aliases: [],
    section: "inspection",
    summary: "Test for Logical Array",
    body: r#"
## Usage
The syntax for `islogical` is

```text
   x = islogical(y)
```
and it returns a logical 1 if the argument is a logical array
and a logical 0 otherwise.
"#,
}

fm_doc::register_doc! {
    name: "ismatrix",
    aliases: [],
    section: "inspection",
    summary: "Test For a 2D Matrix",
    body: r#"
## Usage
This function tests to see if the argument is a matrix.  The
syntax for `ismatrix` is

```text
   x = ismatrix(y)
```
and it returns a logical 1 if the argument is size `N x M` or
`M x N` and a logical 0 otherwise.
"#,
}

fm_doc::register_doc! {
    name: "isnan",
    aliases: [],
    section: "inspection",
    summary: "Test for Not-a-Numbers",
    body: r#"
## Usage
Returns true for entries of an array that are NaN's (i.e.,
Not-a-Numbers).  The usage is

```text
   y = isnan(x)
```
The result is a logical array of the same size as `x`,
which is true if `x` is not-a-number, and false otherwise.
Note that for complex data types that
the result is true if either the real or imaginary parts
are NaNs.

## Example
Suppose we have an array of floats with one element that
is `nan`:

```fm-exec
a = [1.2 3.4 nan 5]
isnan(a)
```
"#,
}

fm_doc::register_doc! {
    name: "isnumeric",
    aliases: [],
    section: "inspection",
    summary: "Test for Numeric Array",
    body: r#"
## Usage
The syntax for `isnumeric` is

```text
  x = isnumeric(y)
```
and it returns a logical 1 if the argument is a numeric
(i.e., not a structure array, cell array, string or user
defined class), and a logical 0 otherwise.
"#,
}

fm_doc::register_doc! {
    name: "isreal",
    aliases: [],
    section: "inspection",
    summary: "Test For Real Array",
    body: r#"
## Usage
The syntax for `isreal` is

```text
   x = isreal(y)
```
and it returns a logical 1 if the argument is real valued
and a logical 0 otherwise.
"#,
}

fm_doc::register_doc! {
    name: "issame",
    aliases: [],
    section: "inspection",
    summary: "Test If Two Arrays Are Identical",
    body: r#"
## Usage
Tests for two arrays to be identical.  The syntax
for its use is

```text
   y = issame(a,b)
```
where `a` and `b` are two arrays to compare.  This
comparison succeeds only if `a` and `b` are of the
same data type, size, and contents.  Unlike numerical
equivalence tests, the `issame` function considers
`NaN` to be equal in both arguments.
"#,
}

fm_doc::register_doc! {
    name: "isscalar",
    aliases: [],
    section: "inspection",
    summary: "Test For Scalar",
    body: r#"
## Usage
The syntax for `isscalar` is

```text
   x = isscalar(y)
```
and it returns a logical 1 if the argument is a scalar,
 and a logical 0 otherwise.
"#,
}

fm_doc::register_doc! {
    name: "isset",
    aliases: [],
    section: "inspection",
    summary: "Test If Variable Set",
    body: r#"
## Usage
Tests for the existence and non-emptiness of a variable.
the general syntax for its use is

```text
   y = isset('name')
```
where `name` is the name of the variable to test.  This
is functionally equivalent to

```text
   y = exist('name','var') & ~isempty(name)
```
It returns a `logical` 1 if the variable is defined
in the current workspace, and is not empty, and returns
a 0 otherwise.

## Example
Some simple examples of using `isset`

```fm-exec
who
isset('a')
a = [];
isset('a')
a = 2;
isset('a')
```
"#,
}

fm_doc::register_doc! {
    name: "issparse",
    aliases: [],
    section: "inspection",
    summary: "Test for Sparse Matrix",
    body: r#"
## Usage
Test a matrix to see if it is sparse or not.  The general
format for its use is

```text
   y = issparse(x)
```
This function returns true if `x` is encoded as a sparse
matrix, and false otherwise.

## Example
Here is an example of using `issparse`:

```fm-exec
a = [1,0,0,5;0,3,2,0]
issparse(a)
A = sparse(a)
issparse(A)
```
"#,
}

fm_doc::register_doc! {
    name: "issquare",
    aliases: [],
    section: "inspection",
    summary: "Test For a Square matrix",
    body: r#"
## Usage
This function tests to see if the argument is a square matrix.  The
syntax for `issquare` is

```text
   x = issquare(y)
```
and it returns a logical 1 if the argument is size `N x N`
logical 0 otherwise.
"#,
}

fm_doc::register_doc! {
    name: "isstr",
    aliases: [],
    section: "inspection",
    summary: "Test For Character Array (string)",
    body: r#"
## Usage
The syntax for `isstr` is

```text
   x = isstr(y)
```
and it returns a logical 1 if the argument is a string
and a logical 0 otherwise.
"#,
}

fm_doc::register_doc! {
    name: "isstruct",
    aliases: [],
    section: "inspection",
    summary: "Test For Structure Array",
    body: r#"
## Usage
The syntax for `isstruct` is

```text
   x = isstruct(y)
```
and it returns a logical 1 if the argument is a structure
array, and a logical 0 otherwise.
"#,
}

fm_doc::register_doc! {
    name: "isvector",
    aliases: [],
    section: "inspection",
    summary: "Test For a Vector",
    body: r#"
## Usage
This function tests to see if the argument is a vector.  The
syntax for `isvector` is

```text
   x = isvector(y)
```
and it returns a logical 1 if the argument is size `N x 1` or
`1 x N` and a logical 0 otherwise.
"#,
}

fm_doc::register_doc! {
    name: "length",
    aliases: [],
    section: "inspection",
    summary: "Length of an Array",
    body: r#"
## Usage
Returns the length of an array `x`.  The syntax for its use
is

```text
   y = length(x)
```
and is defined as the maximum length of `x` along any of its
dimensions, i.e., `max(size(x))`.  If you want to determine the
number of elements in `x`, use the `numel` function instead.

## Example
For a `4 x 4 x 3` matrix, the length is `4`, not `48`, as you
might expect.

```fm-exec
x = rand(4,4,3);
length(x)
```
"#,
}

fm_doc::register_doc! {
    name: "maxdim",
    aliases: [],
    section: "inspection",
    summary: "Maximum Dimension in Array",
    body: r#"
## Usage
The `maxdim` function returns the lowest order dimension
along which an array is largest.  The general syntax for its
use is

```text
  n = maxdim(x)
```
and is equivalent to min(find(size(x) == max(size(x)))).
"#,
}

fm_doc::register_doc! {
    name: "ndims",
    aliases: [],
    section: "inspection",
    summary: "Number of Dimensions in Array",
    body: r#"
## Usage
The `ndims` function returns the number of dimensions
allocated in an array.  The general syntax for its
use is

```text
  n = ndims(x)
```
and is equivalent to `length(size(x))`.
"#,
}

fm_doc::register_doc! {
    name: "nnz",
    aliases: [],
    section: "inspection",
    summary: "Number of Nonzeros",
    body: r#"
## Usage
Returns the number of nonzero elements in a matrix.
The general format for its use is

```text
   y = nnz(x)
```
This function returns the number of nonzero elements
in a matrix or array.  This function works for both
sparse and non-sparse arrays.  For

## Example

```fm-exec
a = [1,0,0,5;0,3,2,0]
nnz(a)
A = sparse(a)
nnz(A)
```
"#,
}

fm_doc::register_doc! {
    name: "numel",
    aliases: [],
    section: "inspection",
    summary: "Number of Elements in an Array",
    body: r#"
## Usage
Returns the number of elements in an array `x`, or in a subindex
expression.  The syntax for its use is either

```text
   y = numel(x)
```
or

```text
   y = numel(x,varargin)
```
Generally, `numel` returns `prod(size(x))`, the number of total
elements in `x`.  However, you can specify a number of indexing
expressions for `varagin` such as `index1, index2, ..., indexm`.
In that case, the output of `numel` is
`prod(size(x(index1,...,indexm)))`.

## Example
For a `4 x 4 x 3` matrix, the length is `4`, not `48`, as you
might expect, but `numel` is `48`.

```fm-exec
x = rand(4,4,3);
length(x)
numel(x)
```

Here is an example of using `numel` with indexing expressions.

```fm-exec
numel(x,1:3,1:2,2)
```
"#,
}

fm_doc::register_doc! {
    name: "size",
    aliases: [],
    section: "inspection",
    summary: "Size of a Variable",
    body: r#"
## Usage
Returns the size of a variable.  There are two syntaxes for its
use.  The first syntax returns the size of the array as a vector
of integers, one integer for each dimension

```text
  [d1,d2,...,dn] = size(x)
```
The other format returns the size of `x` along a particular
dimension:

```text
  d = size(x,n)
```
where `n` is the dimension along which to return the size.

## Example

```fm-exec
a = randn(23,12,5);
size(a)
```

Here is an example of the second form of `size`.

```fm-exec
size(a,2)
```
"#,
}

fm_doc::register_doc! {
    name: "typeof",
    aliases: [],
    section: "inspection",
    summary: "Determine the Type of an Argument",
    body: r#"
## Usage
Returns a string describing the type of an array.  The syntax for its use is

```text
   y = typeof(x),
```
The returned string is one of
- `'cell'` for cell-arrays

- `'struct'` for structure-arrays

- `'logical'` for logical arrays

- `'uint8'` for unsigned 8-bit integers

- `'int8'` for signed 8-bit integers

- `'uint16'` for unsigned 16-bit integers

- `'int16'` for signed 16-bit integers

- `'uint32'` for unsigned 32-bit integers

- `'int32'` for signed 32-bit integers

- `'float'` for 32-bit floating point numbers

- `'double'` for 64-bit floating point numbers

- `'string'` for string arrays

## Example
The following piece of code demonstrates the output of the `typeof`
command for each possible type.  The first example is with a simple cell array.

```fm-exec
typeof({1})
```

The next example uses the `struct` constructor to make a simple scalar struct.

```fm-exec
typeof(struct('foo',3))
```

The next example uses a comparison between two scalar integers to generate
a scalar logical type.

```fm-exec
typeof(3>5)
```

For the integers, the typecast operations are used to generate the arguments.

```fm-exec
typeof(uint8(3))
typeof(int8(8))
typeof(uint16(3))
typeof(int16(8))
typeof(uint32(3))
typeof(int32(3))
typeof(uint64(3))
typeof(int64(3))
```

Float, and double can be created using the suffixes.

```fm-exec
typeof(1.0f)
typeof(1.0D)
typeof(1.0f+i)
typeof(1.0D+2.0D*i)
```
"#,
}

fm_doc::register_doc! {
    name: "what",
    aliases: [],
    section: "inspection",
    summary: "List FreeMat Files In Directory",
    body: r#"
## Usage
Lists files in a directory (or the current directory if no
argument is supplied) that are relevant to FreeMat.  These
are `M`-files, `MAT`-files, and class directories.  There
are several syntaxes for its use.  The first is

```text
   what
```
which lists the aforementioned items.  If you provide a
path instead

```text
   what path-to-folder
```
then `what` will list the relevant FreeMat items in the specified
directory.
"#,
}

fm_doc::register_doc! {
    name: "where",
    aliases: [],
    section: "inspection",
    summary: "Get Information on Program Stack",
    body: r#"
## Usage
Returns information on the current stack.  The usage is

```text
   where
```
The result is a kind of stack trace that indicates the state
of the current call stack, and where you are relative to the
stack.

## Example
Suppose we have the following chain of functions.

```fm-file:chain1.m
function chain1
  a = 32;
  b = a + 5;
  chain2(b)
```

```text
     chain1.m
```

```fm-file:chain2.m
function chain2(d)
  d = d + 5;
  chain3
```

```text
     chain2.m
```

```fm-file:chain3.m
function chain3
  g = 54;
  f = g + 1;
  keyboard
```

```text
     chain3.m
```

The execution of the `where` command shows the stack trace.

```fm-exec
chain1
where
```
"#,
}

fm_doc::register_doc! {
    name: "which",
    aliases: [],
    section: "inspection",
    summary: "Get Information on Function",
    body: r#"
## Usage
Returns information on a function (if defined).  The usage is

```text
   which(fname)
```
where `fname` is a `string` argument that contains the name of the
function.  For functions and scripts defined
via `.m` files, the `which` command returns the location of the source
file:

```text
   y = which(fname)
```
will return the filename for the `.m` file corresponding to the given
function, and an empty string otherwise.

## Example
First, we apply the `which` command to a built in function.

```fm-exec
which fft
```

Next, we apply it to a function defined via a `.m` file.

```fm-exec
which fliplr
```
"#,
}

fm_doc::register_doc! {
    name: "who",
    aliases: [],
    section: "inspection",
    summary: "Describe Currently Defined Variables",
    body: r#"
## Usage
Reports information on either all variables in the current context
or on a specified set of variables.  For each variable, the `who`
function indicates the size and type of the variable as well as
if it is a global or persistent.  There are two formats for the
function call.  The first is the explicit form, in which a list
of variables are provided:

```text
  who a1 a2 ...
```
In the second form

```text
  who
```
the `who` function lists all variables defined in the current
context (as well as global and persistent variables). Note that
there are two alternate forms for calling the `who` function:

```text
  who 'a1' 'a2' ...
```
and

```text
  who('a1','a2',...)
```

## Example
Here is an example of the general use of `who`, which lists all of the variables defined.

```fm-exec
c = [1,2,3];
f = 'hello';
p = randn(1,256);
who
```

In the second case, we examine only a specific variable:

```fm-exec
who c
who('c')
```
"#,
}

fm_doc::register_doc! {
    name: "whos",
    aliases: [],
    section: "inspection",
    summary: "Describe Currently Defined Variables With Memory Usage",
    body: r#"
## Usage
Reports information on either all variables in the current context
or on a specified set of variables.  For each variable, the `who`
function indicates the size and type of the variable as well as
if it is a global or persistent.  There are two formats for the
function call.  The first is the explicit form, in which a list
of variables are provided:

```text
  whos a1 a2 ...
```
In the second form

```text
  whos
```
the `whos` function lists all variables defined in the current
context (as well as global and persistent variables). Note that
there are two alternate forms for calling the `whos` function:

```text
  whos 'a1' 'a2' ...
```
and

```text
  whos('a1','a2',...)
```
"#,
}
