//! Migrated help docs for the `mathfunctions` section (help-system P7).
//! GENERATED by `cargo xtask migrate-place` — do not edit by hand.

fm_doc::register_section! {
    id: "mathfunctions",
    title: "Mathematical Functions",
    summary: "Elementary and special mathematical functions.",
}

fm_doc::register_doc! {
    name: "acos",
    aliases: [],
    section: "mathfunctions",
    summary: "Inverse Trigonometric Arccosine Function",
    body: r#"
## Usage
Computes the `acos` function for its argument.  The general
syntax for its use is

```text
  y = acos(x)
```
where `x` is an `n`-dimensional array of numerical type.
Integer types are promoted to the `double` type prior to
calculation of the `acos` function.  Output `y` is of the
same size and type as the input `x`, (unless `x` is an
integer, in which case `y` is a `double` type).

## Function Internals
Mathematically, the `acos` function is defined for all
arguments `x` as

$$
 \mathrm{acos} x \equiv \frac{pi}{2} + i \log \left(i x +
  \sqrt{1-x^2}\right).
$$
For real valued variables `x` in the range `[-1,1]`, the function is
computed directly using the standard C library's numerical `acos`
function. For both real and complex arguments `x`, note that generally

$$
  \mathrm{acos}(\cos(x)) \neq x,
$$

## Example
The following code demonstates the `acos` function over the range
`[-1,1]`.

```fm-exec:figure
t = linspace(-1,1);
plot(t,acos(t))
```
"#,
}

fm_doc::register_doc! {
    name: "acosd",
    aliases: [],
    section: "mathfunctions",
    summary: "Inverse Cosine Degrees Function",
    body: r#"
## Usage
Computes the inverse cosine of the argument, but returns
the argument in degrees instead of radians (as is the case
for `acos`. The syntax for its use is

```text
   y = acosd(x)
```

## Examples
The inverse cosine of `sqrt(2)/2` should be 45 degrees:

```fm-exec
acosd(sqrt(2)/2)
```

and the inverse cosine of `0.5` should be 60 degrees:

```fm-exec
acosd(0.5)
```
"#,
}

fm_doc::register_doc! {
    name: "acosh",
    aliases: [],
    section: "mathfunctions",
    summary: "Inverse Hyperbolic Cosine Function",
    body: r#"
## Usage
Computes the inverse hyperbolic cosine of its argument.  The general
syntax for its use is

```text
  y = acosh(x)
```
where `x` is an `n`-dimensional array of numerical type.

## Function Internals
The `acosh` function is computed from the formula

$$
   \cosh^{-1}(x) = \log\left(x + (x^2 - 1)^0.5\right)
$$
where the `log` (and square root) is taken in its most general sense.

## Examples
Here is a simple plot of the inverse hyperbolic cosine function

```fm-exec:figure
x = linspace(1,pi);
plot(x,acosh(x)); grid('on');
```
"#,
}

fm_doc::register_doc! {
    name: "acot",
    aliases: [],
    section: "mathfunctions",
    summary: "Inverse Cotangent Function",
    body: r#"
## Usage
Computes the inverse cotangent of its argument.  The general
syntax for its use is

```text
  y = acot(x)
```
where `x` is an `n`-dimensional array of numerical type.

## Function Internals
The `acot` function is computed from the formula

$$
   \cot^{-1}(x) = \tan^{-1}\left(\frac{1}{x}\right)
$$

## Examples
Here is a simple plot of the inverse cotangent function

```fm-exec:figure
x1 = -2*pi:pi/30:-0.1;
x2 = 0.1:pi/30:2*pi;
plot(x1,acot(x1),x2,acot(x2)); grid('on');
```
"#,
}

fm_doc::register_doc! {
    name: "acotd",
    aliases: [],
    section: "mathfunctions",
    summary: "Inverse Cotangent Degrees Function",
    body: r#"
## Usage
Computes the inverse cotangent of its argument in degrees.  The general
syntax for its use is

```text
  y = acotd(x)
```
where `x` is an `n`-dimensional array of numerical type.
"#,
}

fm_doc::register_doc! {
    name: "acoth",
    aliases: [],
    section: "mathfunctions",
    summary: "Inverse Hyperbolic Cotangent Function",
    body: r#"
## Usage
Computes the inverse hyperbolic cotangent of its argument.  The general
syntax for its use is

```text
  y = acoth(x)
```
where `x` is an `n`-dimensional array of numerical type.

## Function Internals
The `acoth` function is computed from the formula

$$
   \coth^{-1}(x) = \tanh^{-1}\left(\frac{1}{x}\right)
$$

## Examples
Here is a simple plot of the inverse hyperbolic cotangent function

```fm-exec:figure
x = linspace(1,pi);
plot(x,acoth(x)); grid('on');
```
"#,
}

fm_doc::register_doc! {
    name: "acsc",
    aliases: [],
    section: "mathfunctions",
    summary: "Inverse Cosecant Function",
    body: r#"
## Usage
Computes the inverse cosecant of its argument.  The general
syntax for its use is

```text
  y = acsc(x)
```
where `x` is an `n`-dimensional array of numerical type.

## Function Internals
The `acosh` function is computed from the formula

$$
   \csc^{-1}(x) = \sin^{-1}\left(\frac{1}{x}\right)
$$

## Examples
Here is a simple plot of the inverse cosecant function

```fm-exec:figure
x1 = -10:.01:-1.01;
x2 = 1.01:.01:10;
plot(x1,acsc(x1),x2,acsc(x2)); grid('on');
```
"#,
}

fm_doc::register_doc! {
    name: "acscd",
    aliases: [],
    section: "mathfunctions",
    summary: "Inverse Cosecant Degrees Function",
    body: r#"
## Usage
Computes the inverse cosecant of the argument, but returns
the argument in degrees instead of radians (as is the case
for `acsc`. The syntax for its use is

```text
   y = acscd(x)
```

## Examples
The inverse cosecant of `2/sqrt(2)` should be 45 degrees:

```fm-exec
acscd(2/sqrt(2))
```

and the inverse cosecant of `2` should be 30 degrees:

```fm-exec
acscd(0.5)
```
"#,
}

fm_doc::register_doc! {
    name: "acsch",
    aliases: [],
    section: "mathfunctions",
    summary: "Inverse Hyperbolic Cosecant Function",
    body: r#"
## Usage
Computes the inverse hyperbolic cosecant of its argument.  The general
syntax for its use is

```text
  y = acsch(x)
```
where `x` is an `n`-dimensional array of numerical type.

## Function Internals
The `acsch` function is computed from the formula

$$
   \mathrm{csch}^{-1}(x) = \sinh^{-1}\left(\frac{1}{x}\right)
$$

## Examples
Here is a simple plot of the inverse hyperbolic cosecant function

```fm-exec:figure
x1 = -20:.01:-1;
x2 = 1:.01:20;
plot(x1,acsch(x1),x2,acsch(x2)); grid('on');
```
"#,
}

fm_doc::register_doc! {
    name: "angle",
    aliases: [],
    section: "mathfunctions",
    summary: "Phase Angle Function",
    body: r#"
## Usage
Compute the phase angle in radians of a complex matrix.  The general
syntax for its use is

```text
  p = angle(c)
```
where `c` is an `n`-dimensional array of numerical type.

## Function Internals
For a complex number `x`, its polar representation is
given by

$$
  x = |x| e^{j\theta}
$$
and we can compute

$$
  \theta = \mathrm{atan2}(\Im x, \Re x)
$$

## Example
Here are some examples of the use of `angle` in the polar decomposition
of a complex number.

```fm-exec
x = 3+4*i
a = abs(x)
t = angle(x)
a*exp(i*t)
```

   M version contributor: M.W. Vogel 01-30-06
"#,
}

fm_doc::register_doc! {
    name: "asec",
    aliases: [],
    section: "mathfunctions",
    summary: "Inverse Secant Function",
    body: r#"
## Usage
Computes the inverse secant of its argument.  The general
syntax for its use is

```text
  y = asec(x)
```
where `x` is an `n`-dimensional array of numerical type.

## Function Internals
The `acosh` function is computed from the formula

$$
   \sec^{-1}(x) = \cos^{-1}\left(\frac{1}{x}\right)
$$

## Examples
Here is a simple plot of the inverse secant function

```fm-exec:figure
x1 = -5:.01:-1;
x2 = 1:.01:5;
plot(x1,asec(x1),x2,asec(x2)); grid('on');
```
"#,
}

fm_doc::register_doc! {
    name: "asecd",
    aliases: [],
    section: "mathfunctions",
    summary: "Inverse Secant Degrees Function",
    body: r#"
## Usage
Computes the inverse secant of the argument, but returns
the argument in degrees instead of radians (as is the case
for `asec`. The syntax for its use is

```text
   y = asecd(x)
```

## Examples
The inverse secant of `2/sqrt(2)` should be 45 degrees:

```fm-exec
asecd(2/sqrt(2))
```

and the inverse secant of `2` should be 60 degrees:

```fm-exec
asecd(2)
```
"#,
}

fm_doc::register_doc! {
    name: "asech",
    aliases: [],
    section: "mathfunctions",
    summary: "Inverse Hyperbolic Secant Function",
    body: r#"
## Usage
Computes the inverse hyperbolic secant of its argument.  The general
syntax for its use is

```text
  y = asech(x)
```
where `x` is an `n`-dimensional array of numerical type.

## Function Internals
The `asech` function is computed from the formula

$$
   \mathrm{sech}^{-1}(x) = \cosh^{-1}\left(\frac{1}{x}\right)
$$

## Examples
Here is a simple plot of the inverse hyperbolic secant function

```fm-exec:figure
x1 = -20:.01:-1;
x2 = 1:.01:20;
plot(x1,imag(asech(x1)),x2,imag(asech(x2))); grid('on');
```
"#,
}

fm_doc::register_doc! {
    name: "asin",
    aliases: [],
    section: "mathfunctions",
    summary: "Inverse Trigonometric Arcsine Function",
    body: r#"
## Usage
Computes the `asin` function for its argument.  The general
syntax for its use is

```text
  y = asin(x)
```
where `x` is an `n`-dimensional array of numerical type.
Integer types are promoted to the `double` type prior to
calculation of the `asin` function.  Output `y` is of the
same size and type as the input `x`, (unless `x` is an
integer, in which case `y` is a `double` type).

## Function Internals
Mathematically, the `asin` function is defined for all
arguments `x` as

$$
   \mathrm{asin} x \equiv - i \log \left(i x +
   \sqrt{1-x^2}\right).
$$
For real valued variables `x` in the range `[-1,1]`, the function is
computed directly using the standard C library's numerical `asin`
function. For both real and complex arguments `x`, note that generally

$$
   \mathrm{asin}(\sin(x)) \neq x,
$$
due to the periodicity of `sin(x)`.

## Example
The following code demonstates the `asin` function over the range
`[-1,1]`.

```fm-exec:figure
t = linspace(-1,1);
plot(t,asin(t))
```
"#,
}

fm_doc::register_doc! {
    name: "asind",
    aliases: [],
    section: "mathfunctions",
    summary: "Inverse Sine Degrees Function",
    body: r#"
## Usage
Computes the inverse sine of the argument, but returns
the argument in degrees instead of radians (as is the case
for `asin`). The syntax for its use is

```text
   y = asind(x)
```

## Examples
The inverse sine of `sqrt(2)/2` should be 45 degrees:

```fm-exec
asind(sqrt(2)/2)
```

and the inverse sine of `0.5` should be 30 degrees:

```fm-exec
asind(0.5)
```
"#,
}

fm_doc::register_doc! {
    name: "asinh",
    aliases: [],
    section: "mathfunctions",
    summary: "Inverse Hyperbolic Sine Function",
    body: r#"
## Usage
Computes the inverse hyperbolic sine of its argument.  The general
syntax for its use is

```text
  y = asinh(x)
```
where `x` is an `n`-dimensional array of numerical type.

## Function Internals
The `asinh` function is computed from the formula

$$
   \sinh^{-1}(x) = \log\left(x + (x^2 + 1)^0.5\right)
$$
where the `log` (and square root) is taken in its most general sense.

## Examples
Here is a simple plot of the inverse hyperbolic sine function

```fm-exec:figure
x = -5:.01:5;
plot(x,asinh(x)); grid('on');
```
"#,
}

fm_doc::register_doc! {
    name: "atan",
    aliases: [],
    section: "mathfunctions",
    summary: "Inverse Trigonometric Arctangent Function",
    body: r#"
## Usage
Computes the `atan` function for its argument.  The general
syntax for its use is

```text
  y = atan(x)
```
where `x` is an `n`-dimensional array of numerical type.
Integer types are promoted to the `double` type prior to
calculation of the `atan` function.  Output `y` is of the
same size and type as the input `x`, (unless `x` is an
integer, in which case `y` is a `double` type).

## Function Internals
Mathematically, the `atan` function is defined for all
arguments `x` as

$$
   \mathrm{atan} x \equiv \frac{i}{2}\left(\log(1-i x) - \log(i x + 1)\right).
$$
For real valued variables `x`, the function is computed directly using
the standard C library's numerical `atan` function. For both
real and complex arguments `x`, note that generally

$$
    \mathrm{atan}(\tan(x)) \neq x,
$$
 due to the periodicity of `tan(x)`.

## Example
The following code demonstates the `atan` function over the range
`[-1,1]`.

```fm-exec:figure
t = linspace(-1,1);
plot(t,atan(t))
```
"#,
}

fm_doc::register_doc! {
    name: "atan2",
    aliases: [],
    section: "mathfunctions",
    summary: "Inverse Trigonometric 4-Quadrant Arctangent Function",
    body: r#"
## Usage
Computes the `atan2` function for its argument.  The general
syntax for its use is

```text
  z = atan2(y,x)
```
where `x` and `y` are `n`-dimensional arrays of numerical type.
Integer types are promoted to the `double` type prior to
calculation of the `atan2` function. The size of the output depends
on the size of `x` and `y`.  If `x` is a scalar, then `z`
is the same size as `y`, and if `y` is a scalar, then `z`
is the same size as `x`.  The type of the output is equal to the type of
|y/x|.

## Function Internals
The function is defined (for real values) to return an
angle between `-pi` and `pi`.  The signs of `x` and `y`
are used to find the correct quadrant for the solution.  For complex
arguments, the two-argument arctangent is computed via

$$
  \mathrm{atan2}(y,x) \equiv -i \log\left(\frac{x+i y}{\sqrt{x^2+y^2}} \right)
$$
For real valued arguments `x,y`, the function is computed directly using
the standard C library's numerical `atan2` function. For both
real and complex arguments `x`, note that generally

$$
  \mathrm{atan2}(\sin(x),\cos(x)) \neq x,
$$
due to the periodicities of  `cos(x)` and `sin(x)`.

## Example
The following code demonstates the difference between the `atan2`
function and the `atan` function over the range `[-pi,pi]`.

```fm-exec:figure
x = linspace(-pi,pi);
sx = sin(x); cx = cos(x);
plot(x,atan(sx./cx),x,atan2(sx,cx))
```

Note how the two-argument `atan2` function (green line)
correctly ``unwraps'' the phase of the angle, while the `atan`
function (red line) wraps the angle to the interval $ [-\pi/2,\pi/2] $.
"#,
}

fm_doc::register_doc! {
    name: "atand",
    aliases: [],
    section: "mathfunctions",
    summary: "Inverse Tangent Degrees Function",
    body: r#"
## Usage
Computes the inverse tangent of the argument, but returns
the argument in degrees instead of radians (as is the case
for `atan`. The syntax for its use is

```text
   y = atand(x)
```

## Examples
The inverse tangent of `1` should be 45 degrees:

```fm-exec
atand(1)
```
"#,
}

fm_doc::register_doc! {
    name: "atanh",
    aliases: [],
    section: "mathfunctions",
    summary: "Inverse Hyperbolic Tangent Function",
    body: r#"
## Usage
Computes the inverse hyperbolic tangent of its argument.  The general
syntax for its use is

```text
  y = atanh(x)
```
where `x` is an `n`-dimensional array of numerical type.

## Function Internals
The `atanh` function is computed from the formula

$$
   \tanh^{-1}(x) = \frac{1}{2}\log\left(\frac{1+x}{1-x}\right)
$$
where the `log` (and square root) is taken in its most general sense.

## Examples
Here is a simple plot of the inverse hyperbolic tangent function

```fm-exec:figure
x = -0.99:.01:0.99;
plot(x,atanh(x)); grid('on');
```
"#,
}

fm_doc::register_doc! {
    name: "betainc",
    aliases: [],
    section: "mathfunctions",
    summary: "Incomplete Beta Function",
    body: r#"
## Usage
Computes the incomplete beta function.  The `betainc`
function takes 3 or 4 arguments

```text
  A = betainc(X,Y,Z)
```

```text
  A = betainc(X,Y,Z,tail)
```
where `X` is either a `float` or `double` array with elements in [0,1] interval, `Y` and `Z` are real non-negative arrays.
`tail` specifies the tail of the incomplete beta function.
If `tail` is 'lower' (default) than the integral from 0 to x is computed. If `tail` is 'upper' than the integral from x to 1 is computed.
All arrays must be the same size or be scalar. The output
vector `A` is the same size (and type) as input arrays.

## Function Internals
The incomplete beta function is defined by the integral:

$$
  BetaI_x(a,b)=B_x(a,b)/B(a,b) where B_x(a,b) = \int_0^x t^{a-1} (1-t)^{b-1} dt
  for 0 <= x <= 1. For a > 0, b > 0
$$

## Example
Here is a plot of the betainc function over the range `[.2,.8]`.

```fm-exec:figure
x=.2:.01:.8;
y = betainc(x,5,3);
plot(x,y); xlabel('x'); ylabel('betainc(x,5,3)');
```

which results in the following plot.
"#,
}

fm_doc::register_doc! {
    name: "cos",
    aliases: [],
    section: "mathfunctions",
    summary: "Trigonometric Cosine Function",
    body: r#"
## Usage
Computes the `cos` function for its argument.  The general
syntax for its use is

```text
  y = cos(x)
```
where `x` is an `n`-dimensional array of numerical type.
Integer types are promoted to the `double` type prior to
calculation of the `cos` function.  Output `y` is of the
same size and type as the input `x`, (unless `x` is an
integer, in which case `y` is a `double` type).

## Function Internals
Mathematically, the `cos` function is defined for all real
valued arguments `x` by the infinite summation

$$
  \cos x \equiv \sum_{n=0}^{\infty} \frac{(-1)^n x^{2n}}{(2n)!}.
$$
For complex valued arguments `z`, the cosine is computed via

$$
  \cos z \equiv \cos \Re z \cosh \Im z - \sin \Re z
  \sinh \Im z.
$$

## Example
The following piece of code plots the real-valued `cos(2 pi x)`
function over one period of `[0,1]`:

```fm-exec:figure
x = linspace(0,1);
plot(x,cos(2*pi*x))
```
"#,
}

fm_doc::register_doc! {
    name: "cosd",
    aliases: [],
    section: "mathfunctions",
    summary: "Cosine Degrees Function",
    body: r#"
## Usage
Computes the cosine of the argument, but takes
the argument in degrees instead of radians (as is the case
for `cos`). The syntax for its use is

```text
   y = cosd(x)
```

## Examples
The cosine of 45 degrees should be `sqrt(2)/2`

```fm-exec
cosd(45)
```

and the cosine of `60` degrees should be 0.5:

```fm-exec
cosd(60)
```
"#,
}

fm_doc::register_doc! {
    name: "cosh",
    aliases: [],
    section: "mathfunctions",
    summary: "Hyperbolic Cosine Function",
    body: r#"
## Usage
Computes the hyperbolic cosine of the argument.
The syntax for its use is

```text
   y = cosh(x)
```

## Function Internals
The `cosh` function is computed from the formula

$$
   \cosh(x) = \frac{e^x+e^{-x}}{2}
$$
For `x` complex, it follows that

$$
   \cosh(a+i*b) = \frac{e^a(\cos(b)+i*\sin(b)) + e^{-a}(\cos(-b)+i*\sin(-b))}{2}
$$

## Examples
Here is a simple plot of the hyperbolic cosine function

```fm-exec:figure
x = linspace(-5,5);
plot(x,cosh(x)); grid('on');
```
"#,
}

fm_doc::register_doc! {
    name: "cot",
    aliases: [],
    section: "mathfunctions",
    summary: "Trigonometric Cotangent Function",
    body: r#"
## Usage
Computes the `cot` function for its argument.  The general
syntax for its use is

```text
  y = cot(x)
```
where `x` is an `n`-dimensional array of numerical type.
Integer types are promoted to the `double` type prior to
calculation of the `cot` function.  Output `y` is of the
same size and type as the input `x`, (unless `x` is an
integer, in which case `y` is a `double` type).

## Function Internals
Mathematically, the `cot` function is defined for all
arguments `x` as

$$
  \cot x \equiv \frac{\cos x}{\sin x}
$$
For complex valued arguments `z`, the cotangent is computed via

$$
  \cot z \equiv \frac{\cos 2 \Re z + \cosh 2 \Im z}{\sin 2 \Re z +
  i \sinh 2 \Im z}.
$$

## Example
The following piece of code plots the real-valued `cot(x)`
function over the interval `[-1,1]`:

```fm-exec:figure
t = linspace(-1,1);
plot(t,cot(t))
```
"#,
}

fm_doc::register_doc! {
    name: "cotd",
    aliases: [],
    section: "mathfunctions",
    summary: "Cotangent Degrees Function",
    body: r#"
## Usage
Computes the cotangent of the argument, but takes
the argument in degrees instead of radians (as is the case
for `cot`). The syntax for its use is

```text
   y = cotd(x)
```

## Examples
The cotangent of 45 degrees should be 1.

```fm-exec
cotd(45)
```
"#,
}

fm_doc::register_doc! {
    name: "coth",
    aliases: [],
    section: "mathfunctions",
    summary: "Hyperbolic Cotangent Function",
    body: r#"
## Usage
Computes the hyperbolic cotangent of the argument.
The syntax for its use is

```text
   y = coth(x)
```

## Function Internals
The `coth` function is computed from the formula

$$
   \coth(x) = \frac{1}{\tanh(x)}
$$

## Examples
Here is a simple plot of the hyperbolic cotangent function

```fm-exec:figure
x1 = -pi+.01:.01:-.01;
x2 = .01:.01:pi-.01;
plot(x1,coth(x1),x2,coth(x2)); grid('on');
```
"#,
}

fm_doc::register_doc! {
    name: "cross",
    aliases: [],
    section: "mathfunctions",
    summary: "Cross Product of Two Vectors",
    body: r#"
## Usage
Computes the cross product of two vectors.  The general syntax
for its use is

```text
    c = cross(a,b)
```
where `a` and `b` are 3-element vectors.
"#,
}

fm_doc::register_doc! {
    name: "csc",
    aliases: [],
    section: "mathfunctions",
    summary: "Trigonometric Cosecant Function",
    body: r#"
## Usage
Computes the `csc` function for its argument.  The general
syntax for its use is

```text
  y = csc(x)
```
where `x` is an `n`-dimensional array of numerical type.
Integer types are promoted to the `double` type prior to
calculation of the `csc` function.  Output `y` is of the
same size and type as the input `x`, (unless `x` is an
integer, in which case `y` is a `double` type).

## Function Internals
Mathematically, the `csc` function is defined for all arguments
as

$$
   \csc x \equiv \frac{1}{\sin x}.
$$

## Example
The following piece of code plots the real-valued `csc(2 pi x)`
function over the interval of `[-1,1]`:

```fm-exec:figure
t = linspace(-1,1,1000);
plot(t,csc(2*pi*t))
axis([-1,1,-10,10]);
```
"#,
}

fm_doc::register_doc! {
    name: "cscd",
    aliases: [],
    section: "mathfunctions",
    summary: "Cosecant Degrees Function",
    body: r#"
## Usage
Computes the cosecant of the argument, but takes
the argument in degrees instead of radians (as is the case
for `csc`). The syntax for its use is

```text
   y = cscd(x)
```
"#,
}

fm_doc::register_doc! {
    name: "csch",
    aliases: [],
    section: "mathfunctions",
    summary: "Hyperbolic Cosecant Function",
    body: r#"
## Usage
Computes the hyperbolic cosecant of the argument.
The syntax for its use is

```text
   y = csch(x)
```

## Function Internals
The `csch` function is computed from the formula

$$
   \mathrm{csch}(x) = \frac{1}{\sinh(x)}
$$

## Examples
Here is a simple plot of the hyperbolic cosecant function

```fm-exec:figure
x1 = -pi+.01:.01:-.01;
x2 = .01:.01:pi-.01;
plot(x1,csch(x1),x2,csch(x2)); grid('on');
```
"#,
}

fm_doc::register_doc! {
    name: "deg2rad",
    aliases: [],
    section: "mathfunctions",
    summary: "Convert From Degrees To Radians",
    body: r#"
## Usage
Converts the argument from degrees to radians.  The
syntax for its use is

```text
   y = deg2rad(x)
```
where `x` is a numeric array.  Conversion is done by
simply multiplying `x` by `pi/180`.

## Example
How many radians in a circle:

```fm-exec
deg2rad(360) - 2*pi
```
"#,
}

fm_doc::register_doc! {
    name: "erf",
    aliases: [],
    section: "mathfunctions",
    summary: "Error Function",
    body: r#"
## Usage
Computes the error function for real arguments.  The `erf`
function takes only a single argument

```text
  y = erf(x)
```
where `x` is either a `float` or `double` array.  The output
vector `y` is the same size (and type) as `x`.

## Function Internals
The erf function is defined by the integral:

$$
  \mathrm{erf}(x) = \frac{2}{\sqrt{\pi}}\int_{0}^{x} e^{-t^2} \, dt,
$$
and is the integral of the normal distribution.

## Example
Here is a plot of the erf function over the range `[-5,5]`.

```fm-exec:figure
x = linspace(-5,5);
y = erf(x);
plot(x,y); xlabel('x'); ylabel('erf(x)');
```

which results in the following plot.
"#,
}

fm_doc::register_doc! {
    name: "erfc",
    aliases: [],
    section: "mathfunctions",
    summary: "Complimentary Error Function",
    body: r#"
## Usage
Computes the complimentary error function for real arguments.  The `erfc`
function takes only a single argument

```text
  y = erfc(x)
```
where `x` is either a `float` or `double` array.  The output
vector `y` is the same size (and type) as `x`.

## Function Internals
The erfc function is defined by the integral:

$$
  \mathrm{erfc}(x) = \frac{2}{\sqrt{\pi}}\int_{x}^{\infty} e^{-t^2} \, dt,
$$
and is the integral of the normal distribution.

## Example
Here is a plot of the `erfc` function over the range `[-5,5]`.

```fm-exec:figure
x = linspace(-5,5);
y = erfc(x);
plot(x,y); xlabel('x'); ylabel('erfc(x)');
```

which results in the following plot.
"#,
}

fm_doc::register_doc! {
    name: "erfinv",
    aliases: [],
    section: "mathfunctions",
    summary: "Inverse Error Function",
    body: r#"
## Usage
Computes the inverse error function for each element of x.  The `erf`
function takes only a single argument

```text
  y = erfinv(x)
```
where `x` is either a `float` or `double` array.  The output
vector `y` is the same size (and type) as `x`. For values outside the interval [-1, 1] function returns NaN.

## Example
Here is a plot of the erf function over the range `[-.9,.9]`.

```fm-exec:figure
x = linspace(-.9,.9,100);
y = erfinv(x);
plot(x,y); xlabel('x'); ylabel('erfinv(x)');
```

which results in the following plot.
"#,
}

fm_doc::register_doc! {
    name: "exp",
    aliases: [],
    section: "mathfunctions",
    summary: "Exponential Function",
    body: r#"
## Usage
Computes the `exp` function for its argument.  The general
syntax for its use is

```text
   y = exp(x)
```
where `x` is an `n`-dimensional array of numerical type.
Integer types are promoted to the `double` type prior to
calculation of the `exp` function.  Output `y` is of the
same size and type as the input `x`, (unless `x` is an
integer, in which case `y` is a `double` type).

## Function Internals
Mathematically, the `exp` function is defined for all real
valued arguments `x` as

$$
  \exp x \equiv e^{x},
$$
where

$$
  e = \sum_{0}^{\infty} \frac{1}{k!}
$$
and is approximately `2.718281828459045` (returned by the function
`e`).  For complex values
`z`, the famous Euler formula is used to calculate the
exponential

$$
  e^{z} = e^{|z|} \left[ \cos \Re z + i \sin \Re z \right]
$$

## Example
The following piece of code plots the real-valued `exp`
function over the interval `[-1,1]`:

```fm-exec:figure
x = linspace(-1,1);
plot(x,exp(x))
```

In the second example, we plot the unit circle in the
complex plane `e^{i 2 pi x}` for `x in [-1,1]`.

```fm-exec:figure
x = linspace(-1,1);
plot(exp(-i*x*2*pi))
```
"#,
}

fm_doc::register_doc! {
    name: "expm1",
    aliases: [],
    section: "mathfunctions",
    summary: "Exponential Minus One Function",
    body: r#"
## Usage
Computes `exp(x)-1` function accurately for `x`
small.  The syntax for its use is

```text
   y = expm1(x)
```
where `x` is an `n`-dimensional array of numerical type.
"#,
}

fm_doc::register_doc! {
    name: "fix",
    aliases: [],
    section: "mathfunctions",
    summary: "Round Towards Zero",
    body: r#"
## Usage
Rounds the argument array towards zero.  The syntax for its use is

```text
   y = fix(x)
```
where `x` is a numeric array.  For positive elements of `x`, the output
is the largest integer smaller than `x`.  For negative elements of `x`
the output is the smallest integer larger than `x`.  For complex `x`,
the operation is applied seperately to the real and imaginary parts.

## Example
Here is a simple example of the `fix` operation on some values

```fm-exec
a = [-1.8,pi,8,-pi,-0.001,2.3+0.3i]
fix(a)
```
"#,
}

fm_doc::register_doc! {
    name: "gamma",
    aliases: [],
    section: "mathfunctions",
    summary: "Gamma Function",
    body: r#"
## Usage
Computes the gamma function for real arguments.  The `gamma`
function takes only a single argument

```text
  y = gamma(x)
```
where `x` is either a `float` or `double` array.  The output
vector `y` is the same size (and type) as `x`.

## Function Internals
The gamma function is defined by the integral:

$$
  \Gamma(x) = \int_{0}^{\infty} e^{-t} t^{x-1} \, dt
$$
The gamma function obeys the interesting relationship

$$
  \Gamma(x) = (x-1)\Gamma(x-1),
$$
and for integer arguments, is equivalent to the factorial function.

## Example
Here is a plot of the gamma function over the range `[-5,5]`.

```fm-exec:figure
x = linspace(-5,5);
y = gamma(x);
plot(x,y); xlabel('x'); ylabel('gamma(x)');
axis([-5,5,-5,5]);
```

which results in the following plot.
"#,
}

fm_doc::register_doc! {
    name: "gammaln",
    aliases: [],
    section: "mathfunctions",
    summary: "Log Gamma Function",
    body: r#"
## Usage
Computes the natural log of the gamma function for real arguments.  The `gammaln`
function takes only a single argument

```text
  y = gammaln(x)
```
where `x` is either a `float` or `double` array.  The output
vector `y` is the same size (and type) as `x`.

## Example
Here is a plot of the `gammaln` function over the range `[-5,5]`.

```fm-exec:figure
x = linspace(0,10);
y = gammaln(x);
plot(x,y); xlabel('x'); ylabel('gammaln(x)');
```

which results in the following plot.
"#,
}

fm_doc::register_doc! {
    name: "idiv",
    aliases: [],
    section: "mathfunctions",
    summary: "Integer Division Operation",
    body: r#"
## Usage
Computes the integer division of two arrays.  The syntax for its use is

```text
   y = idiv(a,b)
```
where `a` and `b` are arrays or scalars.  The effect of the `idiv`
is to compute the integer division of `b` into `a`.

## Example
The following examples show some uses of `idiv`
arrays.

```fm-exec
idiv(27,6)
idiv(4,-2)
idiv(15,3)
```
"#,
}

fm_doc::register_doc! {
    name: "legendre",
    aliases: [],
    section: "mathfunctions",
    summary: "Associated Legendre Polynomial",
    body: r#"
## Usage
Computes the associated Legendre function of degree n.

```text
  y = legendre(n,x)
```
where `x` is either a `float` or `double` array in range `[-1,1]`, `n` is integer scalar.  The output
vector `y` is the same size (and type) as `x`.

## Example
Here is a plot of the `legendre` function over the range `[-1,1]`.

```fm-exec:figure
x = linspace(-1,1,30);
y = legendre(4,x);
plot(x,y); xlabel('x'); ylabel('legendre(4,x)');
```

which results in the following plot.
"#,
}

fm_doc::register_doc! {
    name: "log",
    aliases: [],
    section: "mathfunctions",
    summary: "Natural Logarithm Function",
    body: r#"
## Usage
Computes the `log` function for its argument.  The general
syntax for its use is

```text
  y = log(x)
```
where `x` is an `n`-dimensional array of numerical type.
Integer types are promoted to the `double` type prior to
calculation of the `log` function.  Output `y` is of the
same size as the input `x`. For strictly positive, real inputs,
the output type is the same as the input.
For negative and complex arguments, the output is complex.

## Function Internals
Mathematically, the `log` function is defined for all real
valued arguments `x` by the integral

$$
  \log x \equiv \int_1^{x} \frac{d\,t}{t}.
$$
For complex-valued arguments, `z`, the complex logarithm is
defined as

$$
  \log z \equiv \log |z| + i \arg z,
$$
where `arg` is the complex argument of `z`.

## Example
The following piece of code plots the real-valued `log`
function over the interval `[1,100]`:

```fm-exec:figure
x = linspace(1,100);
plot(x,log(x))
xlabel('x');
ylabel('log(x)');
```
"#,
}

fm_doc::register_doc! {
    name: "log10",
    aliases: [],
    section: "mathfunctions",
    summary: "Base-10 Logarithm Function",
    body: r#"
## Usage
Computes the `log10` function for its argument.  The general
syntax for its use is

```text
  y = log10(x)
```
where `x` is an `n`-dimensional array of numerical type.
Integer types are promoted to the `double` type prior to
calculation of the `log10` function.  Output `y` is of the
same size as the input `x`. For strictly positive, real inputs,
the output type is the same as the input.
For negative and complex arguments, the output is complex.

## Example
The following piece of code plots the real-valued `log10`
function over the interval `[1,100]`:

```fm-exec:figure
x = linspace(1,100);
plot(x,log10(x))
xlabel('x');
ylabel('log10(x)');
```
"#,
}

fm_doc::register_doc! {
    name: "log1p",
    aliases: [],
    section: "mathfunctions",
    summary: "Natural Logarithm of 1+P Function",
    body: r#"
## Usage
Computes the `log` function for one plus its argument.  The general
syntax for its use is

```text
  y = log1p(x)
```
where `x` is an `n`-dimensional array of numerical type.
"#,
}

fm_doc::register_doc! {
    name: "log2",
    aliases: [],
    section: "mathfunctions",
    summary: "Base-2 Logarithm Function",
    body: r#"
## Usage
Computes the `log2` function for its argument.  The general
syntax for its use is

```text
  y = log2(x)
```
where `x` is an `n`-dimensional array of numerical type.
Integer types are promoted to the `double` type prior to
calculation of the `log2` function.  Output `y` is of the
same size as the input `x`. For strictly positive, real inputs,
the output type is the same as the input.
For negative and complex arguments, the output is complex.

## Example
The following piece of code plots the real-valued `log2`
function over the interval `[1,100]`:

```fm-exec:figure
x = linspace(1,100);
plot(x,log2(x))
xlabel('x');
ylabel('log2(x)');
```
"#,
}

fm_doc::register_doc! {
    name: "mod",
    aliases: [],
    section: "mathfunctions",
    summary: "Modulus Operation",
    body: r#"
## Usage
Computes the modulus of an array.  The syntax for its use is

```text
   y = mod(x,n)
```
where `x` is matrix, and `n` is the base of the modulus.  The
effect of the `mod` operator is to add or subtract multiples of `n`
to the vector `x` so that each element `x_i` is between `0` and `n`
(strictly).  Note that `n` does not have to be an integer.  Also,
`n` can either be a scalar (same base for all elements of `x`), or a
vector (different base for each element of `x`).

Note that the following are defined behaviors:
- `mod(x,0) = x`@

- `mod(x,x) = 0`@

- `mod(x,n)`@ has the same sign as `n` for all other cases.

## Example
The following examples show some uses of `mod`
arrays.

```fm-exec
mod(18,12)
mod(6,5)
mod(2*pi,pi)
```

Here is an example of using `mod` to determine if integers are even
 or odd:

```fm-exec
mod([1,3,5,2],2)
```

Here we use the second form of `mod`, with each element using a
separate base.

```fm-exec
mod([9 3 2 0],[1 0 2 2])
```
"#,
}

fm_doc::register_doc! {
    name: "rad2deg",
    aliases: [],
    section: "mathfunctions",
    summary: "Radians To Degrees Conversion Function",
    body: r#"
## Usage
Converts the argument array from radians to degrees.  The general
syntax for its use is

```text
   y = rad2deg(x)
```
Note that the output type will be the same as the input type, and that
complex arguments are allowed.  The output is not wrapped to `[0,360)`.

## Examples
Some known conversion factors

```fm-exec
rad2deg(1) % one radian is about 57 degrees
rad2deg(pi/4) % should be 45 degrees
rad2deg(2*pi) % Note that this is 360 not 0 degrees
```
"#,
}

fm_doc::register_doc! {
    name: "rem",
    aliases: [],
    section: "mathfunctions",
    summary: "Remainder After Division",
    body: r#"
## Usage
Computes the remainder after division of an array.  The syntax for its use is

```text
   y = rem(x,n)
```
where `x` is matrix, and `n` is the base of the modulus.  The
effect of the `rem` operator is to add or subtract multiples of `n`
to the vector `x` so that each element `x_i` is between `0` and `n`
(strictly).  Note that `n` does not have to be an integer.  Also,
`n` can either be a scalar (same base for all elements of `x`), or a
vector (different base for each element of `x`).

Note that the following are defined behaviors:
- `rem(x,0) = nan`@

- `rem(x,x) = 0`@ for nonzero `x`

- `rem(x,n)`@ has the same sign as `x` for all other cases.

Note that `rem` and `mod` return the same value if `x` and `n`
are of the same sign.  But differ by `n` if `x` and `y` have
different signs.

## Example
The following examples show some uses of `rem`
arrays.

```fm-exec
rem(18,12)
rem(6,5)
rem(2*pi,pi)
```

Here is an example of using `rem` to determine if integers are even
 or odd:

```fm-exec
rem([1,3,5,2],2)
```

Here we use the second form of `rem`, with each element using a
separate base.

```fm-exec
rem([9 3 2 0],[1 0 2 2])
```
"#,
}

fm_doc::register_doc! {
    name: "sec",
    aliases: [],
    section: "mathfunctions",
    summary: "Trigonometric Secant Function",
    body: r#"
## Usage
Computes the `sec` function for its argument.  The general
syntax for its use is

```text
  y = sec(x)
```
where `x` is an `n`-dimensional array of numerical type.
Integer types are promoted to the `double` type prior to
calculation of the `sec` function.  Output `y` is of the
same size and type as the input `x`, (unless `x` is an
integer, in which case `y` is a `double` type).

## Function Internals
Mathematically, the `sec` function is defined for all arguments
as

$$
   \sec x \equiv \frac{1}{\cos x}.
$$

## Example
The following piece of code plots the real-valued `sec(2 pi x)`
function over the interval of `[-1,1]`:

```fm-exec:figure
t = linspace(-1,1,1000);
plot(t,sec(2*pi*t))
axis([-1,1,-10,10]);
```
"#,
}

fm_doc::register_doc! {
    name: "secd",
    aliases: [],
    section: "mathfunctions",
    summary: "Secant Degrees Function",
    body: r#"
## Usage
Computes the secant of the argument, but takes
the argument in degrees instead of radians (as is the case
for `sec`). The syntax for its use is

```text
   y = secd(x)
```
"#,
}

fm_doc::register_doc! {
    name: "sech",
    aliases: [],
    section: "mathfunctions",
    summary: "Hyperbolic Secant Function",
    body: r#"
## Usage
Computes the hyperbolic secant of the argument.
The syntax for its use is

```text
   y = sech(x)
```

## Function Internals
The `sech` function is computed from the formula

$$
   \mathrm{sech}(x) = \frac{1}{\cosh(x)}
$$

## Examples
Here is a simple plot of the hyperbolic secant function

```fm-exec:figure
x = -2*pi:.01:2*pi;
plot(x,sech(x)); grid('on');
```
"#,
}

fm_doc::register_doc! {
    name: "sin",
    aliases: [],
    section: "mathfunctions",
    summary: "Trigonometric Sine Function",
    body: r#"
## Usage
Computes the `sin` function for its argument.  The general
syntax for its use is

```text
  y = sin(x)
```
where `x` is an `n`-dimensional array of numerical type.
Integer types are promoted to the `double` type prior to
calculation of the `sin` function.  Output `y` is of the
same size and type as the input `x`, (unless `x` is an
integer, in which case `y` is a `double` type).

## Function Internals
Mathematically, the `sin` function is defined for all real
valued arguments `x` by the infinite summation

$$
  \sin x \equiv \sum_{n=1}^{\infty} \frac{(-1)^{n-1} x^{2n-1}}{(2n-1)!}.
$$
For complex valued arguments `z`, the sine is computed via

$$
  \sin z \equiv \sin \Re z \cosh \Im z - i \cos \Re z
  \sinh \Im z.
$$

## Example
The following piece of code plots the real-valued `sin(2 pi x)`
function over one period of `[0,1]`:

```fm-exec:figure
x = linspace(0,1);
plot(x,sin(2*pi*x))
```
"#,
}

fm_doc::register_doc! {
    name: "sind",
    aliases: [],
    section: "mathfunctions",
    summary: "Sine Degrees Function",
    body: r#"
## Usage
Computes the sine of the argument, but takes
the argument in degrees instead of radians (as is the case
for `cos`). The syntax for its use is

```text
   y = sind(x)
```

## Examples
The sine of 45 degrees should be `sqrt(2)/2`

```fm-exec
sind(45)
```

and the sine of `30` degrees should be 0.5:

```fm-exec
sind(30)
```
"#,
}

fm_doc::register_doc! {
    name: "sinh",
    aliases: [],
    section: "mathfunctions",
    summary: "Hyperbolic Sine Function",
    body: r#"
## Usage
Computes the hyperbolic sine of the argument.
The syntax for its use is

```text
   y = sinh(x)
```

## Function Internals
The `sinh` function is computed from the formula

$$
   \sinh(x) = \frac{e^x-e^{-x}}{2}
$$

## Examples
Here is a simple plot of the hyperbolic sine function

```fm-exec:figure
x = linspace(-5,5);
plot(x,sinh(x)); grid('on');
```
"#,
}

fm_doc::register_doc! {
    name: "sqrt",
    aliases: [],
    section: "mathfunctions",
    summary: "Square Root of an Array",
    body: r#"
## Usage
Computes the square root of the argument matrix.  The general
syntax for its use is

```text
   y = sqrt(x)
```
where `x` is an N-dimensional numerical array.

## Example
Here are some examples of using `sqrt`

```fm-exec
sqrt(9)
sqrt(i)
sqrt(-1)
x = rand(4)
sqrt(x)
```
"#,
}

fm_doc::register_doc! {
    name: "tan",
    aliases: [],
    section: "mathfunctions",
    summary: "Trigonometric Tangent Function",
    body: r#"
## Usage
Computes the `tan` function for its argument.  The general
syntax for its use is

```text
  y = tan(x)
```
where `x` is an `n`-dimensional array of numerical type.
Integer types are promoted to the `double` type prior to
calculation of the `tan` function.  Output `y` is of the
same size and type as the input `x`, (unless `x` is an
integer, in which case `y` is a `double` type).

## Function Internals
Mathematically, the `tan` function is defined for all real
valued arguments `x` by the infinite summation

$$
  \tan x \equiv x + \frac{x^3}{3} + \frac{2x^5}{15} + \cdots,
$$
or alternately by the ratio

$$
  \tan x \equiv \frac{\sin x}{\cos x}
$$
For complex valued arguments `z`, the tangent is computed via

$$
  \tan z \equiv \frac{\sin 2 \Re z + i \sinh 2 \Im z}
                     {\cos 2 \Re z + \cosh 2 \Im z}.
$$

## Example
The following piece of code plots the real-valued `tan(x)`
function over the interval `[-1,1]`:

```fm-exec:figure
t = linspace(-1,1);
plot(t,tan(t))
```
"#,
}

fm_doc::register_doc! {
    name: "tand",
    aliases: [],
    section: "mathfunctions",
    summary: "Tangent Degrees Function",
    body: r#"
## Usage
Computes the tangent of the argument, but takes
the argument in degrees instead of radians (as is the case
for `cos`). The syntax for its use is

```text
   y = tand(x)
```

## Examples
The tangent of 45 degrees should be `1`

```fm-exec
tand(45)
```
"#,
}

fm_doc::register_doc! {
    name: "tanh",
    aliases: [],
    section: "mathfunctions",
    summary: "Hyperbolic Tangent Function",
    body: r#"
## Usage
Computes the hyperbolic tangent of the argument.
The syntax for its use is

```text
   y = tanh(x)
```

## Function Internals
The `tanh` function is computed from the formula

$$
   \tanh(x) = \frac{\sinh(x)}{\cosh(x)}
$$

## Examples
Here is a simple plot of the hyperbolic tangent function

```fm-exec:figure
x = linspace(-5,5);
plot(x,tanh(x)); grid('on');
```
"#,
}
