//! Migrated help docs for the `operators` section (help-system P7).
//! GENERATED by `cargo xtask migrate-place` — do not edit by hand.

fm_doc::register_section! {
    id: "operators",
    title: "Mathematical Operators",
    summary: "Arithmetic, comparison, and matrix operators.",
}

fm_doc::register_doc! {
    name: "comparisonops",
    aliases: [],
    section: "operators",
    summary: "Array Comparison Operators",
    body: r#"
## Usage
There are a total of six comparison operators available in FreeMat, all of which are binary operators with the following syntax

```text
  y = a < b
  y = a <= b
  y = a > b
  y = a >= b
  y = a ~= b
  y = a == b
```
where `a` and `b` are numerical arrays or scalars, and `y` is a `logical` array of the appropriate size.  Each of the operators has three modes of operation, summarized in the following list:
- `a` is a scalar, `b` is an n-dimensional array - the output is then the same size as `b`, and contains the result of comparing each element in `b` to the scalar `a`.

- `a` is an n-dimensional array, `b` is a scalar - the output is the same size as `a`, and contains the result of comparing each element in `a` to the scalar `b`.

- `a` and `b` are both n-dimensional arrays of the same size - the output is then the same size as both `a` and `b`, and contains the result of an element-wise comparison between `a` and `b`.

The operators behave the same way as in `C`, with unequal types being promoted using the standard type promotion rules prior to comparisons.  The only difference is that in FreeMat, the not-equals operator is `~=` instead of `!=`.

## Examples
Some simple examples of comparison operations.  First a comparison with a scalar:

```fm-exec
a = randn(1,5)
a>0
```

Next, we construct two vectors, and test for equality:

```fm-exec
a = [1,2,5,7,3]
b = [2,2,5,9,4]
c = a == b
```
"#,
}

fm_doc::register_doc! {
    name: "dotleftdivide",
    aliases: [],
    section: "operators",
    summary: "Element-wise Left-Division Operator",
    body: r#"
## Usage
Divides two numerical arrays (elementwise) - gets its name from the
fact that the divisor is on the left.  There are two forms
for its use, both with the same general syntax:

```text
  y = a .\ b
```
where `a` and `b` are `n`-dimensional arrays of numerical type.  In the
first case, the two arguments are the same size, in which case, the
output `y` is the same size as the inputs, and is the element-wise
division of `b` by `a`.  In the second case, either `a` or `b` is a scalar,
in which case `y` is the same size as the larger argument,
and is the division of the scalar with each element of the other argument.

The rules for manipulating types has changed in FreeMat 4.0.  See `typerules`
for more details.

## Function Internals
There are three formulae for the dot-left-divide operator, depending on the
sizes of the three arguments.  In the most general case, in which
the two arguments are the same size, the output is computed via:

$$
y(m_1,\ldots,m_d) = \frac{b(m_1,\ldots,m_d)}{a(m_1,\ldots,m_d)}
$$
If `a` is a scalar, then the output is computed via

$$
y(m_1,\ldots,m_d) = \frac{b(m_1,\ldots,m_d)}{a}
$$
On the other hand, if `b` is a scalar, then the output is computed via

$$
y(m_1,\ldots,m_d) = \frac{b}{a(m_1,\ldots,m_d)}.
$$

## Examples
Here are some examples of using the dot-left-divide operator.  First, a
straight-forward usage of the `.\\` operator.  The first example
is straightforward:

```fm-exec
3 .\ 8
```

We can also divide complex arguments:

```fm-exec
a = 3 + 4*i
b = 5 + 8*i
c = b .\ a
```

We can also demonstrate the three forms of the dot-left-divide operator.  First
the element-wise version:

```fm-exec
a = [1,2;3,4]
b = [2,3;6,7]
c = a .\ b
```

Then the scalar versions

```fm-exec
c = a .\ 3
c = 3 .\ a
```
"#,
}

fm_doc::register_doc! {
    name: "dotpower",
    aliases: [],
    section: "operators",
    summary: "Element-wise Power Operator",
    body: r#"
## Usage
Raises one numerical array to another array (elementwise).  There are three operators all with the same general syntax:

```text
  y = a .^ b
```
The result `y` depends on which of the following three situations applies to the arguments `a` and `b`:
- `a` is a scalar, `b` is an arbitrary `n`-dimensional numerical array, in which case the output is `a` raised to the power of each element of `b`, and the output is the same size as `b`.

- `a` is an `n`-dimensional numerical array, and `b` is a scalar, then the output is the same size as `a`, and is defined by each element of `a` raised to the power `b`.

- `a` and `b` are both `n`-dimensional numerical arrays of **the same size**.  In this case, each element of the output is the corresponding element of `a` raised to the power defined by the corresponding element of `b`.

The rules for manipulating types has changed in FreeMat 4.0.  See `typerules`
for more details.

## Function Internals
There are three formulae for this operator.  For the first form

$$
y(m_1,\ldots,m_d) = a^{b(m_1,\ldots,m_d)},
$$
and the second form

$$
y(m_1,\ldots,m_d) = a(m_1,\ldots,m_d)^b,
$$
and in the third form

$$
y(m_1,\ldots,m_d) = a(m_1,\ldots,m_d)^{b(m_1,\ldots,m_d)}.
$$

## Examples
We demonstrate the three forms of the dot-power operator using some simple examples.  First, the case of a scalar raised to a series of values.

```fm-exec
a = 2
b = 1:4
c = a.^b
```

The second case shows a vector raised to a scalar.

```fm-exec
c = b.^a
```

The third case shows the most general use of the dot-power operator.

```fm-exec
A = [1,2;3,2]
B = [2,1.5;0.5,0.6]
C = A.^B
```
"#,
}

fm_doc::register_doc! {
    name: "dotrightdivide",
    aliases: [],
    section: "operators",
    summary: "Element-wise Right-Division Operator",
    body: r#"
## Usage
Divides two numerical arrays (elementwise).  There are two forms
for its use, both with the same general syntax:

```text
  y = a ./ b
```
where `a` and `b` are `n`-dimensional arrays of numerical type.  In the
first case, the two arguments are the same size, in which case, the
output `y` is the same size as the inputs, and is the element-wise
division of `b` by `a`.  In the second case, either `a` or `b` is a scalar,
in which case `y` is the same size as the larger argument,
and is the division of the scalar with each element of the other argument.

The rules for manipulating types has changed in FreeMat 4.0.  See `typerules`
for more details.

## Function Internals
There are three formulae for the dot-right-divide operator, depending on the
sizes of the three arguments.  In the most general case, in which
the two arguments are the same size, the output is computed via:

$$
y(m_1,\ldots,m_d) = \frac{a(m_1,\ldots,m_d)}{b(m_1,\ldots,m_d)}
$$
If `a` is a scalar, then the output is computed via

$$
y(m_1,\ldots,m_d) = \frac{a}{b(m_1,\ldots,m_d)}
$$
On the other hand, if `b` is a scalar, then the output is computed via

$$
y(m_1,\ldots,m_d) = \frac{a(m_1,\ldots,m_d)}{b}.
$$

## Examples
Here are some examples of using the dot-right-divide operator.  First, a
straight-forward usage of the `./` operator.  The first example
is straightforward:

```fm-exec
3 ./ 8
```

We can also divide complex arguments:

```fm-exec
a = 3 + 4*i
b = 5 + 8*i
c = a ./ b
```

We can also demonstrate the three forms of the dot-right-divide operator.  First
the element-wise version:

```fm-exec
a = [1,2;3,4]
b = [2,3;6,7]
c = a ./ b
```

Then the scalar versions

```fm-exec
c = a ./ 3
c = 3 ./ a
```
"#,
}

fm_doc::register_doc! {
    name: "dottimes",
    aliases: [],
    section: "operators",
    summary: "Element-wise Multiplication Operator",
    body: r#"
## Usage
Multiplies two numerical arrays (elementwise).  There are two forms
for its use, both with the same general syntax:

```text
  y = a .* b
```
where `a` and `b` are `n`-dimensional arrays of numerical type.  In the
first case, the two arguments are the same size, in which case, the
output `y` is the same size as the inputs, and is the element-wise
product of `a` and `b`.  In the second case, either `a` or `b` is a scalar,
in which case `y` is the same size as the larger argument,
and is the product of the scalar with each element of the other argument.

The rules for manipulating types has changed in FreeMat 4.0.  See `typerules`
for more details.

## Function Internals
There are three formulae for the dot-times operator, depending on the
sizes of the three arguments.  In the most general case, in which
the two arguments are the same size, the output is computed via:

$$
y(m_1,\ldots,m_d) = a(m_1,\ldots,m_d) \times b(m_1,\ldots,m_d)
$$
If `a` is a scalar, then the output is computed via

$$
y(m_1,\ldots,m_d) = a \times b(m_1,\ldots,m_d).
$$
On the other hand, if `b` is a scalar, then the output is computed via

$$
y(m_1,\ldots,m_d) = a(m_1,\ldots,m_d) \times b.
$$

## Examples
Here are some examples of using the dottimes operator.  First, a
straight-forward usage of the `.*` operator.  The first example
is straightforward:

```fm-exec
3 .* 8
```

Next, we multiply a scalar by a vector of values:

```fm-exec
3.1 .* [2,4,5,6,7]
```

With complex values

```fm-exec
a = 3 + 4*i
b = a .* 2
```

Finally, the element-wise version:

```fm-exec
a = [1,2;3,4]
b = [2,3;6,7]
c = a .* b
```
"#,
}

fm_doc::register_doc! {
    name: "hermitian",
    aliases: [],
    section: "operators",
    summary: "Matrix Hermitian (Conjugate Transpose) Operator",
    body: r#"
## Usage
Computes the Hermitian of the argument (a 2D matrix).  The syntax for its use is

```text
  y = a';
```
where `a` is a `M x N` numerical matrix.  The output `y` is a numerical matrix
of the same type of size `N x M`.  This operator is the conjugating transpose,
which is different from the transpose operator `.'` (which does not
conjugate complex values).

## Function Internals
The Hermitian operator is defined simply as

$$
  y_{i,j} = \overline{a_{j,i}}
$$
where `y_ij` is the element in the `i`th row and `j`th column of the output matrix `y`.

## Examples
A simple transpose example:

```fm-exec
A = [1,2,0;4,1,-1]
A'
```

Here, we use a complex matrix to demonstrate how the Hermitian operator conjugates the entries.

```fm-exec
A = [1+i,2-i]
A.'
```
"#,
}

fm_doc::register_doc! {
    name: "leftdivide",
    aliases: [],
    section: "operators",
    summary: "Matrix Equation Solver/Divide Operator",
    body: r#"
## Usage
The divide operator `\` is really a combination of three
operators, all of which have the same general syntax:

```text
  Y = A \ B
```
where `A` and `B` are arrays of numerical type.  The result `Y` depends
on which of the following three situations applies to the arguments
`A` and `B`:
- `A` is a scalar, `B` is an arbitrary `n`-dimensional numerical array, in which case the output is each element of `B` divided by the scalar `A`.

- `A,B` are matrices with the same number of rows, i.e., `A` is of size `M x K`, and `B` is of size `M x L`, in which case the output is of size `K x L`.

The output follows the standard type promotion rules, although in the first two cases, if `A` and `B` are integers, the output is an integer also, while in the third case if `A` and `B` are integers, the output is of type `double`.

A few additional words about the third version, in which `A` and `B` are matrices.  Very loosely speaking, `Y` is the matrix that satisfies $ A * Y = B $.  In cases where such a matrix exists.  If such a matrix does not exist, then a matrix `Y` is returned that approximates $ A * Y \approx B $.

## Function Internals
There are three formulae for the times operator.  For the first form

$$
Y(m_1,\ldots,m_d) = \frac{B(m_1,\ldots,m_d)}{A}.
$$
In the second form, the calculation of the output depends on the size of `A`. Because each column of `B` is treated independantly, we can rewrite the equation $ A Y = B $ as

$$
  A [y_1, y_2,\ldots, y_l] = [b_1, b_2, \ldots, b_l]
$$
where `y_i` are the columns of `Y`, and `b_i` are the columns of the matrix `B`. If `A` is a square matrix, then the LAPACK routine `*gesvx` (where the `*` is replaced with `sdcz` depending on the type of the arguments) is used, which uses an LU decomposition of `A` to solve the sequence of equations sequentially.  If `A` is singular, then a warning is emitted.

On the other hand, if `A` is rectangular, then the LAPACK routine `*gelsy` is used.  Note that these routines are designed to work with matrices `A` that are full rank - either full column rank or full row rank.  If `A` fails to satisfy this assumption, a warning is emitted.  If `A` has full column rank (and thus necessarily has more rows than columns), then theoretically, this operator finds the columns `y_i` that satisfy:

$$
  y_i = \arg \min_y \| A y - b_i \|_2
$$
and each column is thus the Least Squares solution of `A y = b_i`.  On the other hand, if `A` has full row rank (and thus necessarily has more columns than rows), then theoretically, this operator finds the columns `y_i` that satisfy

$$
  y_i = \arg \min_{A y = b_i} \| y \|_2
$$
and each column is thus the Minimum Norm vector `y_i` that satisfies $ A y_i = b_i $.
In the event that the matrix `A` is neither full row rank nor full column rank, a solution is returned, that is the minimum norm least squares solution.  The solution is computed using an orthogonal factorization technique that is documented in the LAPACK User's Guide (see the References section for details).

## Examples
Here are some simple examples of the divide operator.  We start with a simple example of a full rank, square matrix:

```fm-exec
A = [1,1;0,1]
```

Suppose we wish to solve

$$
  \begin{bmatrix} 1 & 1 \\ 0 & 1 \end{bmatrix}
  \begin{bmatrix} y_1 \\ y_2 \end{bmatrix}
 =
  \begin{bmatrix} 3 \\ 2 \end{bmatrix}
$$
(which by inspection has the solution `y_1 = 1`, `y_2 = 2`).  Thus we compute:

```fm-exec
B = [3;2]
Y = A\B
```

Suppose we wish to solve a trivial Least Squares (LS) problem.  We want to find a simple scaling of the vector `[1;1]` that is closest to the point `[2,1]`.  This is equivalent to solving

$$
\begin{bmatrix} 1 \\ 1 \end{bmatrix} y = \begin{bmatrix} 2 \\ 1 \end{bmatrix}
$$
in a least squares sense.  For fun, we can calculate the solution using calculus by hand.  The error we wish to minimize is

$$
  \varepsilon(y) = (y - 2)^2 + (y-1)^2.
$$
Taking a derivative with respect to `y`, and setting to zero (which we must have for an extrema when `y` is unconstrained)

$$
  2 (y-2) + 2 (y-1) = 0
$$
which we can simplify to `4y = 6` or `y = 3/2` (we must, technically, check to make sure this is a minimum, and not a maximum or an inflection point).  Here is the same calculation performed using FreeMat:

```fm-exec
A = [1;1]
B = [2;1]
A\B
```

which is the same solution.
"#,
}

fm_doc::register_doc! {
    name: "logicalops",
    aliases: [],
    section: "operators",
    summary: "Logical Array Operators",
    body: r#"
## Usage
There are three Boolean operators available in FreeMat.  The syntax for their use is:

```text
  y = ~x
  y = a & b
  y = a | b
```
where `x`, `a` and `b` are `logical` arrays.  The operators are
- NOT (`~`) - output `y` is true if the corresponding element of `x` is false, and ouput `y` is false if the corresponding element of `x` is true.

- OR (``|) - output `y` is true if corresponding element of `a` is true or if corresponding element of `b` is true (or if both are true).

- AND (`\&`) - output `y` is true only if both the corresponding elements of `a` and `b` are both true.

The binary operators AND and OR can take scalar arguments as well as vector arguments, in which case, the scalar is operated on with each element of the vector.
As of version 1.10, FreeMat supports `shortcut` evaluation.  This means that
if we have two expressions

```text
  if (expr1 & expr2)
```
then if `expr1` evaluates to `false`, then `expr2` is not evaluated at all.
Similarly, for the expression

```text
  if (expr1 | expr2)
```
then if `expr1` evaluates to `true`, then `expr2` is not evaluated at all.
Shortcut evaluation is useful for doing a sequence of tests, each of which is
not valid unless the prior test is successful.  For example,

```text
  if isa(p,'string') & strcmp(p,'fro')
```
is not valid without shortcut evaluation (if `p` is an integer, for example,
the first test returns false, and an attempt to evaluate the second expression
would lead to an error).  Note that shortcut evaluation only works with scalar
expressions.

## Examples
Some simple examples of logical operators.  Suppose we want to calculate the exclusive-or (XOR) of two vectors of logical variables.  First, we create a pair of vectors to perform the XOR operation on:

```fm-exec
a = (randn(1,6)>0)
b = (randn(1,6)>0)
```

Next, we can compute the OR of `a` and `b`:

```fm-exec
c = a | b
```

However, the XOR and OR operations differ on the fifth entry - the XOR would be false, since it is true if and only if exactly one of the two inputs is true.  To isolate this case, we can AND the two vectors, to find exactly those entries that appear as true in both `a` and `b`:

```fm-exec
d = a & b
```

At this point, we can modify the contents of `c` in two ways -- the Boolean way is to AND $ \sim d $ with `c`, like so

```fm-exec
xor = c & (~d)
```

The other way to do this is simply force `c(d) = 0`, which uses the logical indexing mode of FreeMat (see the chapter on indexing for more details).  This, however, will cause `c` to become an `int32` type, as opposed to a logical type.

```fm-exec
c(d) = 0
```
"#,
}

fm_doc::register_doc! {
    name: "matrixpower",
    aliases: [],
    section: "operators",
    summary: "Matrix Power Operator",
    body: r#"
## Usage
The power operator for scalars and square matrices.  This operator is really a
combination of two operators, both of which have the same general syntax:

```text
  y = a ^ b
```
The exact action taken by this operator, and the size and type of the output,
depends on which of the two configurations of `a` and `b` is present:
- `a` is a scalar, `b` is a square matrix

- `a` is a square matrix, `b` is a scalar

## Function Internals
In the first case that `a` is a scalar, and `b` is a square matrix, the matrix power is defined in terms of the eigenvalue decomposition of `b`.  Let `b` have the following eigen-decomposition (problems arise with non-symmetric matrices `b`, so let us assume that `b` is symmetric):

$$
  b = E \begin{bmatrix} \lambda_1 & 0          & \cdots  & 0 \\                            0   & \lambda_2  &  \ddots & \vdots \\                                         \vdots & \ddots & \ddots & 0 \\                                                 0   & \hdots & 0 & \lambda_n \end{bmatrix}
      E^{-1}
$$
Then `a` raised to the power `b` is defined as

$$
  a^{b} = E \begin{bmatrix} a^{\lambda_1} & 0          & \cdots  & 0 \\                                0   & a^{\lambda_2}  &  \ddots & \vdots \\                                    \vdots & \ddots & \ddots & 0 \\                                             0   & \hdots & 0 & a^{\lambda_n} \end{bmatrix}
      E^{-1}
$$
Similarly, if `a` is a square matrix, then `a` has the following eigen-decomposition (again, suppose `a` is symmetric):

$$
  a = E \begin{bmatrix} \lambda_1 & 0          & \cdots  & 0 \\                                0   & \lambda_2  &  \ddots & \vdots \\                                         \vdots & \ddots & \ddots & 0 \\                                          0   & \hdots & 0 & \lambda_n \end{bmatrix}
      E^{-1}
$$
Then `a` raised to the power `b` is defined as

$$
  a^{b} = E \begin{bmatrix} \lambda_1^b & 0          & \cdots  & 0 \\                              0   & \lambda_2^b  &  \ddots & \vdots \\                              \vdots & \ddots & \ddots & 0 \\                              0   & \hdots & 0 & \lambda_n^b \end{bmatrix}
      E^{-1}
$$

## Examples
We first define a simple `2 x 2` symmetric matrix

```fm-exec
A = 1.5
B = [1,.2;.2,1]
```

First, we raise `B` to the (scalar power) `A`:

```fm-exec
C = B^A
```

Next, we raise `A` to the matrix power `B`:

```fm-exec
C = A^B
```
"#,
}

fm_doc::register_doc! {
    name: "rightdivide",
    aliases: [],
    section: "operators",
    summary: "Matrix Equation Solver/Divide Operator",
    body: r#"
## Usage
The divide operator `/` is really a combination of three
operators, all of which have the same general syntax:

```text
  Y = A / B
```
where `A` and `B` are arrays of numerical type.  The result `Y` depends
on which of the following three situations applies to the arguments
`A` and `B`:
- `A` is a scalar, `B` is an arbitrary `n`-dimensional numerical array, in which case the output is the scalar `A` divided into each element of `B`.

- `B` is a scalar, `A` is an arbitrary `n`-dimensional numerical array, in which case the output is each element of `A` divided by the scalar `B`.

- `A,B` are matrices with the same number of columns, i.e., `A` is of size `K x M`, and `B` is of size `L x M`, in which case the output is of size `K x L`.

The output follows the standard type promotion rules, although in the first two cases, if `A` and `B` are integers, the output is an integer also, while in the third case if `A` and `B` are integers, the output is of type `double`.

## Function Internals
There are three formulae for the times operator.  For the first form

$$
Y(m_1,\ldots,m_d) = \frac{A}{B(m_1,\ldots,m_d)},
$$
and the second form

$$
Y(m_1,\ldots,m_d) = \frac{A(m_1,\ldots,m_d)}{B}.
$$
In the third form, the output is defined as:

$$
  Y = (B' \backslash A')'
$$
and is used in the equation `Y B = A`.

## Examples
The right-divide operator is much less frequently used than the left-divide operator, but the concepts are similar.  It can be used to find least-squares and minimum norm solutions.  It can also be used to solve systems of equations in much the same way.  Here's a simple example:

```fm-exec
B = [1,1;0,1];
A = [4,5]
A/B
```
"#,
}

fm_doc::register_doc! {
    name: "typerules",
    aliases: [],
    section: "operators",
    summary: "Type Rules for Operators",
    body: r#"
## Usage
Starting with FreeMat 4.0, the type of `y` is determined according to the
same rules as Matlab.  These are the rules:
- Integer types of the same class can be combined.  The answer is
the same type as the inputs, and the operation is performed using
saturating arithmetic.  Integer types can also be combined with double
precision values (again, the result is of the integer type).

- Single precision floating point values can be combined with double
precision, logical and character array classes.  The result is of
class single.

- Double precision floating point values can be combined with all
other types.  Except as noted above, the output is of double precision.

These rules look strange, and they are.   In general, computations are
done in double precision in almost all cases.  When single precision
values are involved, the computations take place in single precision.
"#,
}
