//! Migrated help docs for the `os` section (help-system P7).
//! GENERATED by `cargo xtask migrate-place` — do not edit by hand.

fm_doc::register_section! {
    id: "os",
    title: "Operating System Functions",
    summary: "Operating-system and environment interaction.",
}

fm_doc::register_doc! {
    name: "cd",
    aliases: [],
    section: "os",
    summary: "Change Working Directory Function",
    body: r#"
## Usage
Changes the current working directory to the one specified as the argument.  The general syntax for its use is

```text
  cd('dirname')
```
but this can also be expressed as

```text
  cd 'dirname'
```
or

```text
  cd dirname
```
Examples of all three usages are given below.
Generally speaking, `dirname` is any string that would be accepted
by the underlying OS as a valid directory name.  For example, on most
systems, `'.'` refers to the current directory, and `'..'` refers
to the parent directory.  Also, depending on the OS, it may be necessary
to ``escape'' the directory seperators.  In particular, if directories
are seperated with the backwards-slash character `'\\'`, then the
path specification must use double-slashes `'\\\\'`. Note: to get
file-name completion to work at this time, you must use one of the
first two forms of the command.

## Example
The `pwd` command returns the current directory location.  First,
we use the simplest form of the `cd` command, in which the directory
name argument is given unquoted.

```fm
pwd
cd ..
pwd
```

Next, we use the ``traditional'' form of the function call, using
both the parenthesis and a variable to store the quoted string.

```fm
a = pwd;
cd(a)
pwd
```
"#,
}

fm_doc::register_doc! {
    name: "copyfile",
    aliases: [],
    section: "os",
    summary: "Copy Files",
    body: r#"
## Usage
Copies a file or files from one location to another.  There are
several syntaxes for this function that are acceptable:

```text
   copyfile(file_in,file_out)
```
copies the file from `file_in` to `file_out`.  Also, the second
argument can be a directory name:

```text
   copyfile(file_in,directory_out)
```
in which case `file_in` is copied into the directory specified by
`directory_out`.  You can also use `copyfile` to copy entire directories
as in

```text
   copyfile(dir_in,dir_out)
```
in which case the directory contents are copied to the destination directory
(which is created if necessary).  Finally, the first argument to `copyfile` can
contain wildcards

```text
   copyfile(pattern,directory_out)
```
in which case all files that match the given pattern are copied to the output
directory.   Note that to remain compatible with the MATLAB API, this function
will delete/replace destination files that already exist, unless they are marked
as read-only.  If you want to force the copy to succeed, you can append a `'f'`
argument to the `copyfile` function:

```text
   copyfile(arg1,arg2,'f')
```
or equivalently

```text
   copyfile arg1 arg2 f
```
"#,
}

fm_doc::register_doc! {
    name: "delete",
    aliases: [],
    section: "os",
    summary: "Delete a File",
    body: r#"
## Usage
Deletes a file.  The general syntax for its use is

```text
  delete('filename')
```
or alternately

```text
  delete filename
```
which removes the file described by `filename` which must
be relative to the current path.
"#,
}

fm_doc::register_doc! {
    name: "dir",
    aliases: [],
    section: "os",
    summary: "List Files Function",
    body: r#"
## Usage
In some versions of FreeMat (pre 3.1), the `dir` function was aliased
to the `ls` function.  Starting with version `3.1`, the `dir` function
has been rewritten to provide compatibility with MATLAB.  The general syntax
for its use is

```text
  dir
```
in which case, a listing of the files in the current directory are output to the
console.  Alternately, you can specify a target via

```text
  dir('name')
```
or using the string syntax

```text
  dir name
```
If you want to capture the output of the `dir` command, you can assign the output
to an array

```text
  result = dir('name')
```
(or you can omit `'name'` to get a directory listing of the current directory.  The
resulting array `result` is a structure array containing the fields:
- `name` the filename as a string

- `date` the modification date and time stamp as a string

- `bytes` the size of the file in bytes as a `uint64`

- `isdir` a logical that is `1` if the file corresponds to a directory.

Note that `'name'` can also contain wildcards (e.g., `dir *.m` to get a listing of
all FreeMat scripts in the current directory.
"#,
}

fm_doc::register_doc! {
    name: "dirsep",
    aliases: [],
    section: "os",
    summary: "Director Seperator",
    body: r#"
## Usage
Returns the directory seperator character for the current platform.  The
general syntax for its use is

```text
   y = dirsep
```
This function can be used to build up paths (or see `fullfile` for another
way to do this.
"#,
}

fm_doc::register_doc! {
    name: "fileattrib",
    aliases: [],
    section: "os",
    summary: "Get and Set File or Directory Attributes",
    body: r#"
## Usage
Retrieves information about a file or directory. The first version
uses the syntax

```text
   y = fileattrib(filename)
```
where `filename` is the name of a file or directory.  The returned
structure contains several entries, corresponding to the attributes
of the file.  Here is a list of the entries, and their meaning:
- `Name` - the full pathname for the file

- `archive` - not used, set to `0`

- `system` - not used, set to `0`

- `hidden` - set to `1` for a hidden file, and `0` else.

- `directory` - set to `1` for a directory, and `0` for a file.

- `UserRead` - set to `1` if the user has read permission, `0` otherwise.

- `UserWrite` - set to `1` if the user has write permission, `0` otherwise.

- `UserExecute` - set to `1` if the user has execute permission, `0` otherwise.

- `GroupRead` - set to `1` if the group has read permission, `0` otherwise.

- `GroupWrite` - set to `1` if the group has write permission, `0` otherwise.

- `GroupExecute` - set to `1` if the group has execute permission, `0` otherwise.

- `OtherRead` - set to `1` if the world has read permission, `0` otherwise.

- `OtherWrite` - set to `1` if the world has write permission, `0` otherwise.

- `OtherExecute` - set to `1` if the world has execute permission, `0` otherwise.

You can also provide a wildcard filename to get the attributes for a set of files
e.g.,

```text
   y = fileattrib('foo*')
```

You can also use `fileattrib` to change the attributes of a file and/or directories.
To change attributes, use one of the following syntaxes

```text
   y = fileattrib(filename,attributelist)
   y = fileattrib(filename,attributelist,userlist)
   y = fileattrib(filename,attributelist,userlist,'s')
```
where `attributelist` is a string that consists of a list of attributes, each preceeded by
a `+` to enable the attribute, and `-` to disable the attribute. The valid list of
attributes that can be changed are
- `'w'` - change write permissions

- `'r'` - change read permissions

- `'x'` - change execute permissions

for example, `'-w +r'` would indicate removal of write permissions and addition of read
permissions.  The `userlist` is a string that lists the realm of the permission changes.
If it is not specified, it defaults to `'u'`.
- `'u'` - user or owner permissions

- `'g'` - group permissions

- `'o'` - other permissions ("world" in normal Unix terminology)

- `'a'` - equivalent to 'ugo'.

Finally, if you specify a `'s'` for the last argument, the attribute change is applied
recursively, so that setting the attributes for a directory will apply to all the entries
within the directory.
"#,
}

fm_doc::register_doc! {
    name: "fileparts",
    aliases: [],
    section: "os",
    summary: "Extract Filename Parts",
    body: r#"
## Usage
The `fileparts` takes a filename, and returns the path, filename, extension, and
(for MATLAB-compatibility) an empty version number of the file.  The syntax for its use is

```text
    [path,name,extension,version] = fileparts(filename)
```
where `filename` is a string containing the description of the file, and `path`
is the `path` to the file,
"#,
}

fm_doc::register_doc! {
    name: "fullfile",
    aliases: [],
    section: "os",
    summary: "Build a Full Filename From Pieces",
    body: r#"
## Usage
The `fullfile` routine constructs a full filename from a set of
pieces, namely, directory names and a filename.  The syntax is:

```text
  x = fullfile(dir1,dir2,...,dirn,filename)
```
where each of the arguments are strings.  The `fullfile` function
is equivalent to `[dir1 dirsep dir2 dirsep ... dirn dirsep filename]`.

## Example

```fm
fullfile('path','to','my','file.m')
```
"#,
}

fm_doc::register_doc! {
    name: "getenv",
    aliases: [],
    section: "os",
    summary: "Get the Value of an Environment Variable",
    body: r#"
## Usage
The `getenv` function returns the value for an environment
variable from the underlying OS.  The syntax for the `getenv`
function is

```text
   y = getenv(environment_variable)
```
where `environment_variable` is the name of the environment
variable to return.  The return is a string.

## Example
Here is an example of using the `getenv` function to
get the value for the `HOME` variable

```fm
getenv('HOME')
```
"#,
}

fm_doc::register_doc! {
    name: "getpath",
    aliases: [],
    section: "os",
    summary: "Get Current Search Path",
    body: r#"
## Usage
Returns a `string` containing the current FreeMat search path.  The general syntax for
its use is

```text
  y = getpath
```
The delimiter between the paths depends on the system being used.  For Win32, the
delimiter is a semicolon.  For all other systems, the delimiter is a colon.

## Example
The `getpath` function is straightforward.

```fm
getpath
```
"#,
}

fm_doc::register_doc! {
    name: "ls",
    aliases: [],
    section: "os",
    summary: "List Files Function",
    body: r#"
## Usage
Lists the files in a directory or directories.  The general syntax for its use is

```text
  ls('dirname1','dirname2',...,'dirnameN')
```
but this can also be expressed as

```text
  ls 'dirname1' 'dirname2' ... 'dirnameN'
```
or

```text
  ls dirname1 dirname2 ... dirnameN
```
For compatibility with some environments, the function `dir` can also be used instead of `ls`.  Generally speaking, `dirname` is any string that would be accepted by the underlying OS as a valid directory name.  For example, on most systems, `'.'` refers to the current directory, and `'..'` refers to the parent directory.  Also, depending on the OS, it may be necessary to ``escape'' the directory seperators.  In particular, if directories are seperated with the backwards-slash character `'\\'`, then the path specification must use double-slashes `'\\\\'`. Two points worth mentioning about the `ls` function:
- To get file-name completion to work at this time, you must use one of the first two forms of the command.

- If you want to capture the output of the `ls` command, use the `system` function instead.

## Example
First, we use the simplest form of the `ls` command, in which the directory name argument is given unquoted.

```fm
ls m*.m
```

Next, we use the ``traditional'' form of the function call, using both the parenthesis and the quoted string.

```fm
ls('m*.m')
```

In the third version, we use only the quoted string argument without parenthesis.

```fm
ls 'm*.m'
```
"#,
}

fm_doc::register_doc! {
    name: "mkdir",
    aliases: [],
    section: "os",
    summary: "Make Directory",
    body: r#"
## Usage
Creates a directory.  The general syntax for its use is

```text
  mkdir('dirname')
```
which creates the directory `dirname` if it does not exist.  The argument
`dirname` can be either a relative path or an absolute path.  For compatibility
with MATLAB, the following syntax is also allowed

```text
  mkdir('parentdir','dirname')
```
which attempts to create a directory `dirname` in the directory given by `parentdir`.
However, this simply calls `mkdir([parentdir dirsep dirname])`, and if this is not
the required behavior, please file an enhancement request to have it changed.  Note that
`mkdir` returns a logical `1` if the call succeeded, and a logical `0` if not.
"#,
}

fm_doc::register_doc! {
    name: "pwd",
    aliases: [],
    section: "os",
    summary: "Print Working Directory Function",
    body: r#"
## Usage
Returns a `string` describing the current working directory.  The general syntax for its use is

```text
  y = pwd
```

## Example
The `pwd` function is fairly straightforward.

```fm
pwd
```
"#,
}

fm_doc::register_doc! {
    name: "rmdir",
    aliases: [],
    section: "os",
    summary: "Remove Directory",
    body: r#"
## Usage
Deletes a directory.  The general syntax for its use is

```text
  rmdir('dirname')
```
which removes the directory `dirname` if it is empty.  If you
want to delete the directory and all subdirectories and files
in it, use the syntax

```text
  rmdir('dirname','s')
```
"#,
}

fm_doc::register_doc! {
    name: "setpath",
    aliases: [],
    section: "os",
    summary: "Set Current Search Path",
    body: r#"
## Usage
Changes the current FreeMat search path.  The general syntax for
its use is

```text
  setpath(y)
```
where `y` is a `string` containing a delimited list of directories
to be searched for M files and libraries.
The delimiter between the paths depends on the system being used.  For Win32, the
delimiter is a semicolon.  For all other systems, the delimiter is a colon.

## Example
The `setpath` function is straightforward.

```fm
getpath
setpath('/usr/local/FreeMat/MFiles:/localhome/basu/MFiles')
getpath
```
"#,
}

fm_doc::register_doc! {
    name: "system",
    aliases: [],
    section: "os",
    summary: "Call an External Program",
    body: r#"
## Usage
The `system` function allows you to call an external
program from within FreeMat, and capture the output.
The syntax of the `system` function is

```text
  y = system(cmd)
```
where `cmd` is the command to execute.  The return
array `y` is of type `cell-array`, where each entry
in the array corresponds to a line from the output.

## Example
Here is an example of calling the `ls` function (the
list files function under Un*x-like operating system).

```fm
y = system('ls a*.m')
y{1}
```
"#,
}
