//! Migrated help docs for the `random` section (help-system P7).
//! GENERATED by `cargo xtask migrate-place` — do not edit by hand.

fm_doc::register_section! {
    id: "random",
    title: "Random Number Generation",
    summary: "Random number generation and seeding.",
}

fm_doc::register_doc! {
    name: "rand",
    aliases: [],
    section: "random",
    summary: "Uniform Random Number Generator",
    body: r#"
## Usage
Creates an array of pseudo-random numbers of the specified size.
The numbers are uniformly distributed on `[0,1)`.
Two seperate syntaxes are possible.  The first syntax specifies the array
dimensions as a sequence of scalar dimensions:

```text
  y = rand(d1,d2,...,dn).
```
The resulting array has the given dimensions, and is filled with
random numbers.  The type of `y` is `double`, a 64-bit floating
point array.  To get arrays of other types, use the typecast
functions.

The second syntax specifies the array dimensions as a vector,
where each element in the vector specifies a dimension length:

```text
  y = rand([d1,d2,...,dn]).
```
This syntax is more convenient for calling `rand` using a
variable for the argument.

Finally, `rand` supports two additional forms that allow
you to manipulate the state of the random number generator.
The first retrieves the state

```text
  y = rand('state')
```
which is a 625 length integer vector.  The second form sets
the state

```text
  rand('state',y)
```
or alternately, you can reset the random number generator with

```text
  rand('state',0)
```

## Example
The following example demonstrates an example of using the first form of the `rand` function.

```fm
rand(2,2,2)
```

The second example demonstrates the second form of the `rand` function.

```fm
rand([2,2,2])
```

The third example computes the mean and variance of a large number of uniform random numbers.  Recall that the mean should be `1/2`, and the variance should be `1/12 ~ 0.083`.

```fm
x = rand(1,10000);
mean(x)
var(x)
```

Now, we use the state manipulation functions of `rand` to exactly reproduce
a random sequence.  Note that unlike using `seed`, we can exactly control where
the random number generator starts by saving the state.

```fm
rand('state',0)    % restores us to startup conditions
a = rand(1,3)      % random sequence 1
b = rand('state'); % capture the state vector
c = rand(1,3)      % random sequence 2  
rand('state',b);   % restart the random generator so...
c = rand(1,3)      % we get random sequence 2 again
```
"#,
}

fm_doc::register_doc! {
    name: "randbeta",
    aliases: [],
    section: "random",
    summary: "Beta Deviate Random Number Generator",
    body: r#"
## Usage
Creates an array of beta random deviates based on the supplied
two parameters. The general syntax for `randbeta` is

```text
   y = randbeta(alpha, beta)
```
where `alpha` and `beta` are the two parameters of the
random deviate.  There are three forms for calling `randbeta`.
The first uses two vectors `alpha` and `beta` of the same
size, in which case the output `y` is the same size as both
inputs, and each deviate uses the corresponding values of `alpha`
and `beta` from the arguments.  In the other forms, either
`alpha` or `beta` are scalars.

## Function Internals
The probability density function (PDF) of a beta random variable
is

$$
f(x) = x^(a-1) * (1-x)^(b-1) / B(a,b)
$$
for `x` between 0 and 1.  The function `B(a,b)` is defined so
that the integral of `f(x)` is 1.

## Example
Here is a plot of the PDF of a beta random variable with `a=3`,
`b=7`.

```fm
a = 3; b = 7;
x = (0:100)/100; t = x.^(a-1).*(1-x).^(b-1); 
t = t/(sum(t)*.01);
plot(x,t);
```

which is plotted as
If we generate a few random deviates with these values,
we see they are distributed around the peak of roughly
`0.25`.

```fm
randbeta(3*ones(1,5),7*ones(1,5))
```
"#,
}

fm_doc::register_doc! {
    name: "randbin",
    aliases: [],
    section: "random",
    summary: "Generate Binomial Random Variables",
    body: r#"
## Usage
Generates random variables with a binomial distribution.
The general syntax for its use is

```text
   y = randbin(N,p)
```
where `N` is a vector representing the number of Bernoulli
trials, and `p` is the success probability associated with each
trial.

## Function Internals
A Binomial random variable describes the number of successful
outcomes from `N` Bernoulli trials, with the probability of
success in each trial being `p`.  The probability distribution
is

$$
   P(n) = \frac{N!}{n!(N-n)!}p^n(1-p)^{N-n}
$$

## Example
Here we generate `10` binomial random variables, corresponding
to `N=100` trials, each with probability `p=0.1`, using
both `randbin` and then again using `rand` (to simulate the trials):

```fm
randbin(100,.1*ones(1,10))
sum(rand(100,10)<0.1)
```
"#,
}

fm_doc::register_doc! {
    name: "randchi",
    aliases: [],
    section: "random",
    summary: "Generate Chi-Square Random Variable",
    body: r#"
## Usage
Generates a vector of chi-square random variables with the
given number of degrees of freedom.  The general syntax for
its use is

```text
   y = randchi(n)
```
where `n` is an array containing the degrees of freedom for
each generated random variable.

## Function Internals
A chi-square random variable is essentially distributed as
the squared Euclidean norm of a vector of standard Gaussian random
variables.  The number of degrees of freedom is generally the
number of elements in the vector.  In general, the PDF of
a chi-square random variable is

$$
 f(x) = \frac{x^{r/2-1}e^{-x/2}}{\Gamma(r/2)2^{r/2}}
$$

## Example
First, a plot of the PDF for a family of chi-square random variables

```fm
f = zeros(7,100);
x = (1:100)/10;
for n=1:7;t=x.^(n/2-1).*exp(-x/2);f(n,:)=10*t/sum(t);end
plot(x,f');
```

The PDF is below:
Here is an example of using `randchi` and `randn` to compute
some chi-square random variables with four degrees of freedom.

```fm
randchi(4*ones(1,6))
sum(randn(4,6).^2)
```
"#,
}

fm_doc::register_doc! {
    name: "randexp",
    aliases: [],
    section: "random",
    summary: "Generate Exponential Random Variable",
    body: r#"
## Usage
Generates a vector of exponential random variables with
the specified parameter.  The general syntax for its use is

```text
   y = randexp(lambda)
```
where `lambda` is a vector containing the parameters for
the generated random variables.

## Function Internals
The exponential random variable is usually associated with
the waiting time between events in a Poisson random process.
The PDF of an exponential random variable is:

$$
   f(x) = \lambda e^{-\lambda x}
$$

## Example
Here is an example of using the `randexp` function to generate
some exponentially distributed random variables

```fm
randexp(ones(1,6))
```
"#,
}

fm_doc::register_doc! {
    name: "randf",
    aliases: [],
    section: "random",
    summary: "Generate F-Distributed Random Variable",
    body: r#"
## Usage
Generates random variables with an F-distribution.  The general
syntax for its use is

```text
   y = randf(n,m)
```
where `n` and `m` are vectors of the number of degrees of freedom
in the numerator and denominator of the chi-square random variables
whose ratio defines the statistic.

## Function Internals
The statistic `F_{n,m}` is defined as the ratio of two chi-square
random variables:

$$
  F_{n,m} = \frac{\chi_n^2/n}{\chi_m^2/m}
$$
The PDF is given by

$$
  f_{n,m} = \frac{m^{m/2}n^{n/2}x^{n/2-1}}{(m+nx)^{(n+m)/2}B(n/2,m/2)},
$$
where `B(a,b)` is the beta function.

## Example
Here we use `randf` to generate some F-distributed random variables,
and then again using the `randchi` function:

```fm
randf(5*ones(1,9),7)
randchi(5*ones(1,9))./randchi(7*ones(1,9))
```
"#,
}

fm_doc::register_doc! {
    name: "randgamma",
    aliases: [],
    section: "random",
    summary: "Generate Gamma-Distributed Random Variable",
    body: r#"
## Usage
Generates random variables with a gamma distribution.  The general
syntax for its use is

```text
   y = randgamma(a,r),
```
where `a` and `r` are vectors describing the parameters of the
gamma distribution.  Roughly speaking, if `a` is the mean time between
changes of a Poisson random process, and we wait for the `r` change,
the resulting wait time is Gamma distributed with parameters `a`
and `r`.

## Function Internals
The Gamma distribution arises in Poisson random processes.  It represents
the waiting time to the occurance of the `r`-th event in a process with
mean time `a` between events.  The probability distribution of a Gamma
random variable is

$$
   P(x) = \frac{a^r x^{r-1} e^{-ax}}{\Gamma(r)}.
$$
Note also that for integer values of `r` that a Gamma random variable
is effectively the sum of `r` exponential random variables with parameter
`a`.

## Example
Here we use the `randgamma` function to generate Gamma-distributed
random variables, and then generate them again using the `randexp`
function.

```fm
randgamma(1,15*ones(1,9))
sum(randexp(ones(15,9)))
```
"#,
}

fm_doc::register_doc! {
    name: "randi",
    aliases: [],
    section: "random",
    summary: "Uniformly Distributed Integer",
    body: r#"
## Usage
Generates an array of uniformly distributed integers between
the two supplied limits.  The general syntax for `randi` is

```text
   y = randi(low,high)
```
where `low` and `high` are arrays of integers.  Scalars
can be used for one of the arguments.  The output `y` is
a uniformly distributed pseudo-random number between `low`
and `high` (inclusive).

## Example
Here is an example of a set of random integers between
zero and 5:

```fm-exec
randi(zeros(1,6),5*ones(1,6))
```
"#,
}

fm_doc::register_doc! {
    name: "randmulti",
    aliases: [],
    section: "random",
    summary: "Generate Multinomial-distributed Random Variables",
    body: r#"
## Usage
This function generates samples from a multinomial distribution
given the probability of each outcome.  The general syntax for
its use is

```text
   y = randmulti(N,pvec)
```
where `N` is the number of experiments to perform, and `pvec`
is the vector of probabilities describing the distribution of
outcomes.

## Function Internals
A multinomial distribution describes the number of times each
of `m` possible outcomes occurs out of `N` trials, where each
outcome has a probability `p_i`.  More generally, suppose that
the probability of a Bernoulli random variable `X_i` is `p_i`,
and that

$$
   \sum_{i=1}^{m} p_i = 1.
$$
Then the probability that `X_i` occurs `x_i` times is

$$
   P_N(x_1,x_2,\ldots,x_n) = \frac{N!}{x_1!\cdots x_n!} p_1^{x_1}\cdots p_n^{x_n}.
$$

## Example
Suppose an experiment has three possible outcomes, say heads,
tails and edge, with probabilities `0.4999`, `0.4999` and
`0.0002`, respectively.  Then if we perform ten thousand coin
flips we get

```fm
randmulti(10000,[0.4999,0.4999,0.0002])
```
"#,
}

fm_doc::register_doc! {
    name: "randn",
    aliases: [],
    section: "random",
    summary: "Gaussian (Normal) Random Number Generator",
    body: r#"
## Usage
Creates an array of pseudo-random numbers of the specified size.
The numbers are normally distributed with zero mean and a unit
standard deviation (i.e., `mu = 0, sigma = 1`).
 Two seperate syntaxes are possible.  The first syntax specifies the array
dimensions as a sequence of scalar dimensions:

```text
  y = randn(d1,d2,...,dn).
```
The resulting array has the given dimensions, and is filled with
random numbers.  The type of `y` is `double`, a 64-bit floating
point array.  To get arrays of other types, use the typecast
functions.

The second syntax specifies the array dimensions as a vector,
where each element in the vector specifies a dimension length:

```text
  y = randn([d1,d2,...,dn]).
```
This syntax is more convenient for calling `randn` using a
variable for the argument.

Finally, `randn` supports two additional forms that allow
you to manipulate the state of the random number generator.
The first retrieves the state

```text
  y = randn('state')
```
which is a 625 length integer vector.  The second form sets
the state

```text
  randn('state',y)
```
or alternately, you can reset the random number generator with

```text
  randn('state',0)
```

## Function Internals
Recall that the
probability density function (PDF) of a normal random variable is

$$
f(x) = \frac{1}{\sqrt{2\pi \sigma^2}} e^{\frac{-(x-\mu)^2}{2\sigma^2}}.
$$
The Gaussian random numbers are generated from pairs of uniform random numbers using a transformation technique.

## Example
The following example demonstrates an example of using the first form of the `randn` function.

```fm
randn(2,2,2)
```

The second example demonstrates the second form of the `randn` function.

```fm
randn([2,2,2])
```

In the next example, we create a large array of 10000  normally distributed pseudo-random numbers.  We then shift the mean to 10, and the variance to 5.  We then numerically calculate the mean and variance using `mean` and `var`, respectively.

```fm
x = 10+sqrt(5)*randn(1,10000);
mean(x)
var(x)
```

Now, we use the state manipulation functions of `randn` to exactly reproduce
a random sequence.  Note that unlike using `seed`, we can exactly control where
the random number generator starts by saving the state.

```fm
randn('state',0)    % restores us to startup conditions
a = randn(1,3)      % random sequence 1
b = randn('state'); % capture the state vector
c = randn(1,3)      % random sequence 2  
randn('state',b);   % restart the random generator so...
c = randn(1,3)      % we get random sequence 2 again
```
"#,
}

fm_doc::register_doc! {
    name: "randnbin",
    aliases: [],
    section: "random",
    summary: "Generate Negative Binomial Random Variables",
    body: r#"
## Usage
Generates random variables with a negative binomial distribution.
The general syntax for its use is

```text
   y = randnbin(r,p)
```
where `r` is a vector of integers representing the number of
successes, and `p` is the probability of success.

## Function Internals
A negative binomial random variable describes the number of failures
`x` that occur in `x+r` bernoulli trials, with a success on the
`x+r` trial.  The pdf is given by

$$
  P_{r,p}(x)=\left(\begin{matrix} x+r-1 \\ r-1 \end{matrix}\right)p^r(1-p)^x.
$$

## Example
Here we generate some negative binomial random variables:

```fm
randnbin(3*ones(1,4),.01)
randnbin(6*ones(1,4),.01)
```
"#,
}

fm_doc::register_doc! {
    name: "randnchi",
    aliases: [],
    section: "random",
    summary: "Generate Noncentral Chi-Square Random Variable",
    body: r#"
## Usage
Generates a vector of non-central chi-square random variables
with the given number of degrees of freedom and the given
non-centrality parameters.  The general syntax for its use is

```text
   y = randnchi(n,mu)
```
where `n` is an array containing the degrees of freedom for
each generated random variable (with each element of `n` >= 1),
and `mu` is the non-centrality shift (must be positive).

## Function Internals
A non-central chi-square random variable is the sum of a chisquare
deviate with `n-1` degrees of freedom plus the square of a normal
deviate with mean `mu` and standard deviation 1.

## Examples
Here is an example of a non-central chi-square random variable:

```fm
randnchi(5*ones(1,9),0.3)
```
"#,
}

fm_doc::register_doc! {
    name: "randnf",
    aliases: [],
    section: "random",
    summary: "Generate Noncentral F-Distribution Random Variable",
    body: r#"
## Usage
Generates a vector of non-central F-distributed random variables
with the specified parameters.  The general syntax for its use is

```text
   y = randnf(n,m,c)
```
where `n` is the number of degrees of freedom in the numerator,
and `m` is the number of degrees of freedom in the denominator.
The vector `c` determines the non-centrality shift of the numerator.

## Function Internals
A non-central F-distributed random variable is the ratio of a
non-central chi-square random variable and a central chi-square random
variable, i.e.,

$$
   F_{n,m,c} = \frac{\chi_{n,c}^2/n}{\chi_m^2/m}.
$$

## Example
Here we use the `randf` to generate some non-central F-distributed
random variables:

```fm
randnf(5*ones(1,9),7,1.34)
```
"#,
}

fm_doc::register_doc! {
    name: "randp",
    aliases: [],
    section: "random",
    summary: "Generate Poisson Random Variable",
    body: r#"
## Usage
Generates a vector Poisson random variables with the given
parameters.  The general syntax for its use is

```text
   y = randp(nu),
```
where `nu` is an array containing the rate parameters
for the generated random variables.

## Function Internals
A Poisson random variable is generally defined by taking the
limit of a binomial distribution as the sample size becomes
large, with the expected number of successes being fixed (so
that the probability of success decreases as `1/N`).
The Poisson distribution is given by

$$
  P_{\nu}(n) = \frac{\nu^n e^{-nu}}{n!}.
$$

## Example
Here is an exmaple of using `randp` to generate some Poisson
random variables, and also using `randbin` to do the same
using `N=1000` trials to approximate the Poisson result.

```fm
randp(33*ones(1,10))
randbin(1000*ones(1,10),33/1000*ones(1,10))
```
"#,
}

fm_doc::register_doc! {
    name: "randperm",
    aliases: [],
    section: "random",
    summary: "Random permutation",
    body: r#"
## Usage

```text
   y = randperm(n)
```
`y` is a random permutation of integers from 1 to `n`.
`randperm` calls `rand` and changes its state.

## Example

```fm
y = randperm(10)
```
"#,
}

fm_doc::register_doc! {
    name: "seed",
    aliases: [],
    section: "random",
    summary: "Seed the Random Number Generator",
    body: r#"
## Usage
Seeds the random number generator using the given integer seeds.
Changing the seed allows you to choose which pseudo-random
sequence is generated.  The seed takes two `uint32` values:

```text
  seed(s,t)
```
where `s` and `t` are the seed values.  Note that due to limitations
in `ranlib`, the values of `s,t` must be between `0 <= s,t <= 2^30`.

## Example
Here's an example of how the seed value can be used to reproduce
a specific random number sequence.

```fm-exec
seed(32,41);
rand(1,5)
seed(32,41);
rand(1,5)
```
"#,
}
