//! Migrated help docs for the `sparse` section (help-system P7).
//! GENERATED by `cargo xtask migrate-place` — do not edit by hand.

fm_doc::register_section! {
    id: "sparse",
    title: "Sparse Matrix Support",
    summary: "Sparse matrix construction and operations.",
}

fm_doc::register_doc! {
    name: "eigs",
    aliases: [],
    section: "sparse",
    summary: "Sparse Matrix Eigendecomposition",
    body: r#"
## Usage
Computes the eigendecomsition of a sparse square matrix.  The
`eigs` function has several forms.  The most general form is

```text
  [V,D] = eigs(A,k,sigma)
```
where `A` is the matrix to analyze, `k` is the number of
eigenvalues to compute and `sigma` determines which eigenvallues
to solve for.  Valid values for `sigma` are
   'lm' - largest magnitude
   'sm' - smallest magnitude
   'la' - largest algebraic (for real symmetric problems)
   'sa' - smallest algebraic (for real symmetric problems)
   'be' - both ends (for real symmetric problems)
   'lr' - largest real part
   'sr' - smallest real part
   'li' - largest imaginary part
   'si' - smallest imaginary part
 scalar - find the eigenvalues closest to `sigma`.
The returned matrix `V` contains the eigenvectors, and `D`
stores the eigenvalues.  The related form

```text
   d = eigs(A,k,sigma)
```
computes only the eigenvalues and not the eigenvectors.  If `sigma`
is omitted, as in the forms

```text
  [V,D] = eigs(A,k)
```
and

```text
  d = eigs(A,k)
```
then `eigs` returns the largest magnitude eigenvalues (and optionally
the associated eigenvectors).  As an even simpler form, the forms

```text
  [V,D] = eigs(A)
```
and

```text
  d = eigs(A)
```
then `eigs` returns the six largest magnitude eigenvalues of `A` and
optionally the eigenvectors.  The `eigs` function uses ARPACK to
compute the eigenvectors and/or eigenvalues.  Note that due to a
limitation in the interface into ARPACK from FreeMat, the number of
eigenvalues that are to be computed must be strictly smaller than the
number of columns (or rows) in the matrix.

## Example
Here is an example of using `eigs` to calculate eigenvalues
of a matrix, and a comparison of the results with `eig`

```fm-exec
a = sparse(rand(9));
eigs(a)
eig(full(a))
```

Next, we exercise some of the variants of `eigs`:

```fm-exec
eigs(a,4,'sm')
eigs(a,4,'lr')
eigs(a,4,'sr')
```
"#,
}

fm_doc::register_doc! {
    name: "full",
    aliases: [],
    section: "sparse",
    summary: "Convert Sparse Matrix to Full Matrix",
    body: r#"
## Usage
Converts a sparse matrix to a full matrix.  The syntax for
its use is

```text
   y = full(x)
```
The type of `x` is preserved.  Be careful with the function.
As a general rule of thumb, if you can work with the `full`
representation of a function, you probably do not need the
sparse representation.

## Example
Here we convert a full matrix to a sparse one, and back again.

```fm-exec
a = [1,0,4,2,0;0,0,0,0,0;0,1,0,0,2]
A = sparse(a)
full(A)
```
"#,
}

fm_doc::register_doc! {
    name: "sparse",
    aliases: [],
    section: "sparse",
    summary: "Construct a Sparse Matrix",
    body: r#"
## Usage
Creates a sparse matrix using one of several formats.  The
first creates a sparse matrix from a full matrix

```text
   y = sparse(x).
```
The second form creates a sparse matrix containing all zeros
that is of the specified size (the sparse equivalent of
`zeros`).

```text
   y = sparse(m,n)
```
where `m` and `n` are integers.  Just like the `zeros` function,
the sparse matrix returned is of type `float`.  The third form
constructs a sparse matrix from the IJV syntax.  It has two forms.  The
first version autosizes the sparse matrix

```text
   y = sparse(i,j,v)
```
while the second version uses an explicit size specification

```text
   y = sparse(i,j,v,m,n)
```
"#,
}

fm_doc::register_doc! {
    name: "speye",
    aliases: [],
    section: "sparse",
    summary: "Sparse Identity Matrix",
    body: r#"
## Usage
Creates a sparse identity matrix of the given size.  The syntax for
its use is

```text
  y = speye(m,n)
```
which forms an `m x n` sparse matrix with ones on the main diagonal,
or

```text
  y = speye(n)
```
which forms an `n x n` sparse matrix with ones on the main diagonal.  The
matrix type is a `float` single precision matrix.

## Example
The following creates a 5000 by 5000 identity matrix, which would be
difficult to do using `sparse(eye(5000))` because of the large amount
of intermediate storage required.

```fm
I = speye(5000);
who I
full(I(1:10,1:10))
```
"#,
}

fm_doc::register_doc! {
    name: "spones",
    aliases: [],
    section: "sparse",
    summary: "Sparse Ones Function",
    body: r#"
## Usage
Returns a sparse `float` matrix with ones where the argument
matrix has nonzero values.  The general syntax for it is

```text
  y = spones(x)
```
where `x` is a matrix (it may be full or sparse).  The output
matrix `y` is the same size as `x`, has type `float`, and contains
ones in the nonzero positions of `x`.

## Examples
Here are some examples of the `spones` function

```fm-exec
a = [1,0,3,0,5;0,0,2,3,0;1,0,0,0,1]
b = spones(a)
full(b)
```
"#,
}

fm_doc::register_doc! {
    name: "sprand",
    aliases: [],
    section: "sparse",
    summary: "Sparse Uniform Random Matrix",
    body: r#"
## Usage
Creates a sparse matrix with uniformly distributed random entries (on [0,1]).  The
syntax for its use is

```text
  y = sprand(x)
```
where `x` is a sparse matrix, where `y` is a sparse matrix that has
random entries where `x` is nonzero.  The second form specifies the
size of the matrix and the density

```text
  y = sprand(m,n,density)
```
where `m` is the number of rows in the output, `n` is the number of
columns in the output, and `density` (which is between 0 and 1) is
the density of nonzeros in the resulting matrix.  Note that for very
high densities the actual density of the output matrix may differ from
the density you specify.  This difference is a result of the way the
random entries into the matrix are generated.  If you need a very dense
random matrix, it is better to generate a full matrix and zero out the
entries you do not need.

## Examples
Here we seed `sprand` with a full matrix (to demonstrate how the structure
of the output is determined by the input matrix when using the first form).

```fm
x = [1,0,0;0,0,1;1,0,0]
y = sprand(x)
full(y)
```

The more generic version with a density of `0.001`.  On many systems the
following is impossible using full matrices

```fm
y = sprand(10000,10000,.001);
nnz(y)/10000^2
```
"#,
}

fm_doc::register_doc! {
    name: "sprandn",
    aliases: [],
    section: "sparse",
    summary: "Sparse Normal Random Matrix",
    body: r#"
## Usage
Creates a sparse matrix with normally distributed random entries (mean 0, sigma 1).  The
syntax for its use is

```text
  y = sprandn(x)
```
where `x` is a sparse matrix, where `y` is a sparse matrix that has
random entries where `x` is nonzero.  The second form specifies the
size of the matrix and the density

```text
  y = sprandn(m,n,density)
```
where `m` is the number of rows in the output, `n` is the number of
columns in the output, and `density` (which is between 0 and 1) is
the density of nonzeros in the resulting matrix.  Note that for very
high densities the actual density of the output matrix may differ from
the density you specify.  This difference is a result of the way the
random entries into the matrix are generated.  If you need a very dense
random matrix, it is better to generate a full matrix and zero out the
entries you do not need.

## Examples
Here we seed `sprandn` with a full matrix (to demonstrate how the structure
of the output is determined by the input matrix when using the first form).

```fm
x = [1,0,0;0,0,1;1,0,0]
y = sprandn(x)
full(y)
```

The more generic version with a density of `0.001`.  On many systems the
following is impossible using full matrices

```fm
y = sprandn(10000,10000,.001);
nnz(y)/10000^2
```
"#,
}

fm_doc::register_doc! {
    name: "spy",
    aliases: [],
    section: "sparse",
    summary: "Visualize Sparsity Pattern of a Sparse Matrix",
    body: r#"
## Usage
Plots the sparsity pattern of a sparse matrix.  The syntax for its use is

```text
   spy(x)
```
which uses a default color and symbol.  Alternately, you can use

```text
   spy(x,colspec)
```
where `colspec` is any valid color and symbol spec accepted by `plot`.

## Example
First, an example of a random sparse matrix.

```fm-exec:figure
y = sprand(1000,1000,.001);
spy(y,'ro')
```

which is shown here
Here is a sparse matrix with a little more structure.  First we build a
sparse matrix with block diagonal structure, and then use `spy` to
visualize the structure.

```fm-exec:figure
A = sparse(1000,1000);
for i=1:25; A((1:40) + 40*(i-1),(1:40) + 40*(i-1)) = 1; end;
spy(A,'gx')
```

with the result shown here
"#,
}
