//! Migrated help docs for the `string` section (help-system P7).
//! GENERATED by `cargo xtask migrate-place` — do not edit by hand.

fm_doc::register_section! {
    id: "string",
    title: "String Functions",
    summary: "String creation, formatting, and manipulation.",
}

fm_doc::register_doc! {
    name: "blanks",
    aliases: [],
    section: "string",
    summary: "Create a blank string",
    body: r#"
## Usage

```text
    str = blanks(n)
```
Create a string `str` containing `n` blank charaters.

## Example
A simple example:

```fm-exec
sprintf(['x0123456789y\n','x',blanks(10),'y\n'])
```
"#,
}

fm_doc::register_doc! {
    name: "cellstr",
    aliases: [],
    section: "string",
    summary: "Convert character array to cell array of strings",
    body: r#"
## Usage
The `cellstr` converts a character array matrix into a
a cell array of individual strings.  Each string in
the matrix is placed in a different cell, and extra spaces
are removed.  The syntax for the command is

```text
   y = cellstr(x)
```
where `x` is an `N x M` array of characters as a string.

## Example
Here is an example of how to use `cellstr`

```fm
a = ['quick';'brown';'fox  ';'is   ']
cellstr(a)
```
"#,
}

fm_doc::register_doc! {
    name: "deblank",
    aliases: [],
    section: "string",
    summary: "Remove trailing blanks from a string",
    body: r#"
## Usage
The `deblank` function removes spaces at the end of a string
when used with the syntax

```text
   y = deblank(x)
```
where `x` is a string, in which case, all of the extra spaces
in `x` are stripped from the end of the string.  Alternately,
you can call `deblank` with a cell array of strings

```text
   y = deblank(c)
```
in which case each string in the cell array is deblanked.

## Example
A simple example

```fm-exec
deblank('hello   ')
```

and a more complex example with a cell array of strings

```fm-exec
deblank({'hello  ','there ','  is  ','  sign  '})
```
"#,
}

fm_doc::register_doc! {
    name: "isalpha",
    aliases: [],
    section: "string",
    summary: "Test for Alpha Characters in a String",
    body: r#"
## Usage
The `isalpha` functions returns a logical array that is 1
for characters in the argument string that are letters, and
is a logical 0 for characters in the argument that are not
letters.  The syntax for its use is

```text
   x = isalpha(s)
```
where `s` is a `string`.  Note that this function is not
locale sensitive, and returns a logical 1 for letters in the
classic ASCII sense (a through z, and A through Z).

## Example
A simple example of `isalpha`:

```fm
isalpha('numb3r5')
```
"#,
}

fm_doc::register_doc! {
    name: "isdigit",
    aliases: [],
    section: "string",
    summary: "Test for Digit Characters in a String",
    body: r#"
## Usage
The `isdigit` functions returns a logical array that is 1
for characters in the argument string that are digits, and
is a logical 0 for characters in the argument that are not
digits.  The syntax for its use is

```text
   x = isdigit(s)
```
where `s` is a `string`.

## Example
A simple example of `isdigit`:

```fm
isdigit('numb3r5')
```
"#,
}

fm_doc::register_doc! {
    name: "isspace",
    aliases: [],
    section: "string",
    summary: "Test for Space Characters in a String",
    body: r#"
## Usage
The `isspace` functions returns a logical array that is 1
for characters in the argument string that are spaces, and
is a logical 0 for characters in the argument that are not
spaces.  The syntax for its use is

```text
   x = isspace(s)
```
where `s` is a `string`.  A blank character is considered
a space, newline, tab, carriage return, formfeed, and vertical
tab.

## Example
A simple example of `isspace`:

```fm
isspace('  hello there world ')
```
"#,
}

fm_doc::register_doc! {
    name: "lower",
    aliases: [],
    section: "string",
    summary: "Convert strings to lower case",
    body: r#"
## Usage
The `lower` function converts a string to lower case with
the syntax

```text
   y = lower(x)
```
where `x` is a string, in which case all of the upper case
characters in `x` (defined as the range `'A'-'Z'`) are
converted to lower case.  Alternately, you can call `lower`
with a cell array of strings

```text
   y = lower(c)
```
in which case each string in the cell array is converted to lower case.

## Example
A simple example:

```fm-exec
lower('this Is Strange CAPitalizaTion')
```

and a more complex example with a cell array of strings

```fm-exec
lower({'This','Is','Strange','CAPitalizaTion'})
```
"#,
}

fm_doc::register_doc! {
    name: "regexp",
    aliases: [],
    section: "string",
    summary: "Regular Expression Matching Function",
    body: r#"
## Usage
Matches regular expressions in the provided string.  This function is
complicated, and compatibility with MATLABs syntax is not perfect.  The
syntax for its use is

```text
  regexp('str','expr')
```
which returns a row vector containing the starting index of each substring
of `str` that matches the regular expression described by `expr`.  The
second form of `regexp` returns six outputs in the following order:

```text
  [start stop tokenExtents match tokens names] = regexp('str','expr')
```
where the meaning of each of the outputs is defined below.
- `start` is a row vector containing the starting index of each
substring that matches the regular expression.

- `stop` is a row vector containing the ending index of each
substring that matches the regular expression.

- `tokenExtents` is a cell array containing the starting and ending
indices of each substring that matches the `tokens` in the regular
expression.  A token is a captured part of the regular expression.
If the `'once'` mode is used, then this output is a `double` array.

- `match` is a cell array containing the text for each substring
that matches the regular expression.  In `'once'` mode, this is a
string.

- `tokens` is a cell array of cell arrays of strings that correspond
to the tokens in the regular expression.  In `'once'` mode, this is a
cell array of strings.

- `named` is a structure array containing the named tokens captured
in a regular expression. Each named token is assigned a field in the resulting
structure array, and each element of the array corresponds to a different
match.

If you want only some of the the outputs,  you can use the
following variant of `regexp`:

```text
  [o1 o2 ...] = regexp('str','expr', 'p1', 'p2', ...)
```
where `p1` etc. are the names of the outputs (and the order we want
the outputs in).  As a final variant, you can supply some mode
flags to `regexp`

```text
  [o1 o2 ...] = regexp('str','expr', p1, p2, ..., 'mode1', 'mode2')
```
where acceptable `mode` flags are:
- `'once'` - only the first match is returned.

- `'matchcase'` - letter case must match (selected by default for `regexp`)

- `'ignorecase'` - letter case is ignored (selected by default for `regexpi`)

- `'dotall'` - the `'.'` operator matches any character (default)

- `'dotexceptnewline'` - the `'.'` operator does not match the newline character

- `'stringanchors'` - the `^` and `$` operators match at the beginning and
end (respectively) of a string.

- `'lineanchors'` - the `^` and `$` operators match at the beginning and
end (respectively) of a line.

- `'literalspacing'` - the space characters and comment characters `#` are matched
as literals, just like any other ordinary character (default).

- `'freespacing'` - all spaces and comments are ignored in the regular expression.
You must use '\ ' and '\#' to match spaces and comment characters, respectively.

Note the following behavior differences between MATLABs regexp and FreeMats:
- If you have an old version of `pcre` installed, then named tokens must use the
older `<?P\<name\>` syntax, instead of the new `<?\<name\>` syntax.

- The `pcre` library is pickier about named tokens and their appearance in
expressions.  So, for example, the regexp from the MATLAB
manual `'(?\<first\>\\w+)\\s+(?\<last\>\\w+)`(?\<last\>\[[unknown: \w]]+),\[[unknown: \s]]+(?\<first\>\[[unknown: \w]]+)'|
does not work correctly (as of this writing) because the same named
tokens appear multiple
times.  The workaround is to assign different names to each token, and then collapse
the results later.

## Example
Some examples of using the `regexp` function

```fm-exec
[start,stop,tokenExtents,match,tokens,named] = regexp('quick down town zoo','(.)own')
```
"#,
}

fm_doc::register_doc! {
    name: "regexprep",
    aliases: [],
    section: "string",
    summary: "Regular Expression Replacement Function",
    body: r#"
## Usage
Replaces regular expressions in the provided string.  The syntax for its
use is

```text
  outstring = regexprep(instring,pattern,replacement,modes)
```
Here `instring` is the string to be operated on.  And `pattern` is a regular
expression of the type accepted by `regexp`.  For each match, the contents
of the matched string are replaced with the replacement text.  Tokens in the
regular expression can be used in the replacement text using `$N` where `N`
is the number of the token to use.  You can also specify the same `mode`
flags that are used by `regexp`.
"#,
}

fm_doc::register_doc! {
    name: "strcmp",
    aliases: [],
    section: "string",
    summary: "String Compare Function",
    body: r#"
## Usage
Compares two strings for equality.  The general
syntax for its use is

```text
  p = strcmp(x,y)
```
where `x` and `y` are two strings.  Returns `true` if `x`
and `y` are the same size, and are equal (as strings).  Otherwise,
it returns `false`.
In the second form, `strcmp` can be applied to a cell array of
strings.  The syntax for this form is

```text
  p = strcmp(cellstra,cellstrb)
```
where `cellstra` and `cellstrb` are cell arrays of a strings
to compare.  Also, you can also supply a character matrix as
an argument to `strcmp`, in which case it will be converted
via `cellstr` (so that trailing spaces are removed), before being
compared.

## Example
The following piece of code compares two strings:

```fm-exec
x1 = 'astring';
x2 = 'bstring';
x3 = 'astring';
strcmp(x1,x2)
strcmp(x1,x3)
```

Here we use a cell array strings

```fm-exec
x = {'astring','bstring',43,'astring'}
p = strcmp(x,'astring')
```

Here we compare two cell arrays of strings

```fm-exec
strcmp({'this','is','a','pickle'},{'what','is','to','pickle'})
```

Finally, the case where one of the arguments is a matrix
string

```fm-exec
strcmp({'this','is','a','pickle'},['peter ';'piper ';'hated ';'pickle'])
```
"#,
}

fm_doc::register_doc! {
    name: "strcmpi",
    aliases: [],
    section: "string",
    summary: "String Compare Case Insensitive Function",
    body: r#"
## Usage
Compares two strings for equality ignoring case.  The general
syntax for its use is

```text
   p = strcmpi(x,y)
```
where `x` and `y` are two strings, or cell arrays of strings.
See `strcmp` for more help.
"#,
}

fm_doc::register_doc! {
    name: "strfind",
    aliases: [],
    section: "string",
    summary: "Find Substring in a String",
    body: r#"
## Usage
Searches through a string for a pattern, and returns the starting
positions of the pattern in an array.  There are two forms for
the `strfind` function.  The first is for single strings

```text
   ndx = strfind(string, pattern)
```
the resulting array `ndx` contains the starting indices in `string`
for the pattern `pattern`.  The second form takes a cell array of
strings

```text
   ndx = strfind(cells, pattern)
```
and applies the search operation to each string in the cell array.

## Example
Here we apply `strfind` to a simple string

```fm-exec
a = 'how now brown cow?'
b = strfind(a,'ow')
```

Here we search over multiple strings contained in a cell array.

```fm-exec
a = {'how now brown cow','quick brown fox','coffee anyone?'}
b = strfind(a,'ow')
```
"#,
}

fm_doc::register_doc! {
    name: "strncmp",
    aliases: [],
    section: "string",
    summary: "String Compare Function To Length N",
    body: r#"
## Usage
Compares two strings for equality, but only looks at the
first N characters from each string.  The general syntax
for its use is

```text
  p = strncmp(x,y,n)
```
where `x` and `y` are two strings.  Returns `true` if `x`
and `y` are each at least `n` characters long, and if the
first `n` characters from each string are the same.  Otherwise,
it returns `false`.
In the second form, `strncmp` can be applied to a cell array of
strings.  The syntax for this form is

```text
  p = strncmp(cellstra,cellstrb,n)
```
where `cellstra` and `cellstrb` are cell arrays of a strings
to compare.  Also, you can also supply a character matrix as
an argument to `strcmp`, in which case it will be converted
via `cellstr` (so that trailing spaces are removed), before being
compared.

## Example
The following piece of code compares two strings:

```fm-exec
x1 = 'astring';
x2 = 'bstring';
x3 = 'astring';
strncmp(x1,x2,4)
strncmp(x1,x3,4)
```

Here we use a cell array strings

```fm-exec
x = {'ast','bst',43,'astr'}
p = strncmp(x,'ast',3)
```

Here we compare two cell arrays of strings

```fm-exec
strncmp({'this','is','a','pickle'},{'think','is','to','pickle'},3)
```

Finally, the case where one of the arguments is a matrix
string

```fm-exec
strncmp({'this','is','a','pickle'},['peter ';'piper ';'hated ';'pickle'],4);
```
"#,
}

fm_doc::register_doc! {
    name: "strrep",
    aliases: [],
    section: "string",
    summary: "String Replace Function",
    body: r#"
## Usage
Replace every occurance of one string with another.  The
general syntax for its use is

```text
  p = strrep(source,find,replace)
```
Every instance of the string `find` in the string `source` is
replaced with the string `replace`.  Any of `source`, `find`
and `replace` can be a cell array of strings, in which case
each entry has the replace operation applied.

## Example
Here are some examples of the use of `strrep`.  First the case
where are the arguments are simple strings

```fm-exec
strrep('Matlab is great','Matlab','FreeMat')
```

And here we have the replace operation for a number of strings:

```fm-exec
strrep({'time is money';'A stitch in time';'No time for games'},'time','money')
```
"#,
}

fm_doc::register_doc! {
    name: "strstr",
    aliases: [],
    section: "string",
    summary: "String Search Function",
    body: r#"
## Usage
Searches for the first occurance of one string inside another.
The general syntax for its use is

```text
   p = strstr(x,y)
```
where `x` and `y` are two strings.  The returned integer `p`
indicates the index into the string `x` where the substring `y`
occurs.  If no instance of `y` is found, then `p` is set to
zero.

## Example
Some examples of `strstr` in action

```fm
strstr('hello','lo')
strstr('quick brown fox','own')
strstr('free stuff','lunch')
```
"#,
}

fm_doc::register_doc! {
    name: "strtrim",
    aliases: [],
    section: "string",
    summary: "Trim Spaces from a String",
    body: r#"
## Usage
Removes the white-spaces at the beginning and end of a string (or a
cell array of strings). See `isspace` for a definition of a white-space.
There are two forms for the `strtrim` function.  The first is for
single strings

```text
   y = strtrim(strng)
```
where `strng` is a string.  The second form operates on a cell array
of strings

```text
   y = strtrim(cellstr)
```
and trims each string in the cell array.

## Example
Here we apply `strtrim` to a simple string

```fm-exec
strtrim('  lot of blank spaces    ');
```

and here we apply it to a cell array

```fm-exec
strtrim({'  space','enough ',' for ',''})
```
"#,
}

fm_doc::register_doc! {
    name: "upper",
    aliases: [],
    section: "string",
    summary: "Convert strings to upper case",
    body: r#"
## Usage
The `upper` function converts a string to upper case with
the syntax

```text
   y = upper(x)
```
where `x` is a string, in which case all of the lower case
characters in `x` (defined as the range `'a'-'z'`) are
converted to upper case.  Alternately, you can call `upper`
with a cell array of strings

```text
   y = upper(c)
```
in which case each string in the cell array is converted to upper case.

## Example
A simple example:

```fm-exec
upper('this Is Strange CAPitalizaTion')
```

and a more complex example with a cell array of strings

```fm-exec
upper({'This','Is','Strange','CAPitalizaTion'})
```
"#,
}
