//! Migrated help docs for the `thread` section (help-system P7).
//! GENERATED by `cargo xtask migrate-place` — do not edit by hand.

fm_doc::register_section! {
    id: "thread",
    title: "FreeMat Threads",
    summary: "Multithreading and concurrent execution.",
}

fm_doc::register_doc! {
    name: "threadcall",
    aliases: [],
    section: "thread",
    summary: "Call Function In A Thread",
    body: r#"
## Usage
The `threadcall` function is a convenience function for executing
a function call in a thread.  The syntax for its use is

```text
   [val1,...,valn] = threadcall(threadid,timeout,funcname,arg1,arg2,...)
```
where `threadid` is the ID of the thread (as returned by the
`threadnew` function), `funcname` is the name of the function to call,
and `argi` are the arguments to the function, and `timeout` is the
amount of time (in milliseconds) that the function is allowed to take.

## Example
Here is an example of executing a simple function in a different thread.

```fm
id = threadnew
d = threadcall(id,1000,'cos',1.02343)
threadfree(id)
```
"#,
}

fm_doc::register_doc! {
    name: "threadfree",
    aliases: [],
    section: "thread",
    summary: "Free thread resources",
    body: r#"
## Usage
The `threadfree` is a function to free the resources claimed
by a thread that has finished.  The syntax for its use is

```text
   threadfree(handle)
```
where `handle` is the handle returned by the call to `threadnew`.
The `threadfree` function requires that the thread be completed.
Otherwise it will wait for the thread to complete, potentially
for an arbitrarily long period of time.  To fix this, you can
either call `threadfree` only on threads that are known to have
completed, or you can call it using the syntax

```text
   threadfree(handle,timeout)
```
where `timeout` is a time to wait in milliseconds.  If the thread
fails to complete before the timeout expires, an error occurs.
"#,
}

fm_doc::register_doc! {
    name: "threadid",
    aliases: [],
    section: "thread",
    summary: "Get Current Thread Handle",
    body: r#"
## Usage
The `threadid` function in FreeMat tells you which thread
is executing the context you are in.  Normally, this is thread
1, the main thread.  However, if you start a new thread using
`threadnew`, you will be operating in a new thread, and functions
that call `threadid` from the new thread will return their
handles.

## Example
From the main thread, we have

```fm
threadid
```

But from a launched auxilliary thread, we have

```fm
t_id = threadnew
id = threadcall(t_id,1000,'threadid')
threadfree(t_id);
```
"#,
}

fm_doc::register_doc! {
    name: "threadkill",
    aliases: [],
    section: "thread",
    summary: "Halt execution of a thread",
    body: r#"
## Usage
The `threadkill` function stops (or attempts to stop) execution
of the given thread.  It works only for functions defined in M-files
(i.e., not for built in or imported functions), and it works by
setting a flag that causes the thread to stop execution at the next
available statement.  The syntax for this function is

```text
  threadkill(handle)
```
where `handle` is the value returned by a `threadnew` call.
Note that the `threadkill` function returns immediately.  It
is still your responsibility to call `threadfree` to free
the thread you have halted.

You cannot kill the main thread (thread id `1`).

## Example
Here is an example of stopping a runaway thread using `threadkill`.
Note that the thread function in this case is an M-file function.
We start by setting up a free running counter, where we can access
the counter from the global variables.

```fm-file:freecount.m
function freecount
  global count
  if (~exist('count')) count = 0; end  % Initialize the counter
  while (1)
    count = count + 1;                 % Update the counter
  end
```

```text
     freecount.m
```

We now launch this function in a thread, and use `threadkill` to
stop it:

```fm
a = threadnew;
global count                   % register the global variable count
count = 0;
threadstart(a,'freecount',0)   % start the thread
count                          % it is counting
sleep(1)                       % Wait a bit
count                          % it is still counting
threadkill(a)                  % kill the counter
threadwait(a,1000)             % wait for it to finish
count                          % The count will no longer increase
sleep(1)
count
threadfree(a)
```
"#,
}

fm_doc::register_doc! {
    name: "threadnew",
    aliases: [],
    section: "thread",
    summary: "Create a New Thread",
    body: r#"
## Usage
The `threadnew` function creates a new FreeMat thread, and
returns a handle to the resulting thread.   The `threadnew`
function takes no arguments.  They general syntax for the
`threadnew` function is

```text
   handle = threadnew
```
Once you have a handle to a thread, you can start the thread
on a computation using the `threadstart` function.  The
threads returned by `threadnew` are in a dormant state (i.e.,
not running).  Once you are finished with the thread you
must call `threadfree` to free the resources associated with
that thread.

Some additional important information.  Thread functions operate
in their own context or workspace, which means that data cannot
be shared between threads.  The exception is `global` variables,
which provide a thread-safe way for multiple threads to share data.
Accesses to global variables are serialized so that they can
be used to share data.  Threads and FreeMat are a new feature, so
there is room for improvement in the API and behavior.  The best
way to improve threads is to experiment with them, and send feedback.
"#,
}

fm_doc::register_doc! {
    name: "threadstart",
    aliases: [],
    section: "thread",
    summary: "Start a New Thread Computation",
    body: r#"
## Usage
The `threadstart` function starts a new computation on a
FreeMat thread, and you must provide a function (no scripts
are allowed) to run inside the thread, pass any parameters that
the thread function requires, as well as the number of output
arguments expected.  The general syntax for the
`threadstart` function is

```text
   threadstart(threadid,function,nargout,arg1,arg2,...)
```
where `threadid` is a thread handle (returned by `threadnew`),
where `function` is a valid function name (it can be a built-in
imported or M-function), `nargout` is the number of output arguments
expected from the function, and `arg1` is the first argument that
is passed to the function.  Because the function runs in its
own thread, the return values of the function are not available
imediately.  Instead, execution of that function will continue
in parallel with the current thread.  To retrieve the output
of the thread function, you must wait for the thread to complete
using the `threadwait` function, and then call `threadvalue`
 to retrieve the result.  You can also stop the running thread
prematurely by using the `threadkill` function.  It is important
to call `threadfree` on the handle you get from `threadnew`
when you are finished with the thread to ensure that the resoures
are properly freed.

It is also perfectly reasonable to use a single thread multiple
times, calling `threadstart` and `threadreturn` multiple times
on a single thread.  The context is preserved between threads.
When calling `threadstart` on a pre-existing thread, FreeMat
will attempt to wait on the thread.  If the wait fails, then
an error will occur.

Some additional important information.  Thread functions operate
in their own context or workspace, which means that data cannot
be shared between threads.  The exception is `global` variables,
which provide a thread-safe way for multiple threads to share data.
Accesses to global variables are serialized so that they can
be used to share data.  Threads and FreeMat are a new feature, so
there is room for improvement in the API and behavior.  The best
way to improve threads is to experiment with them, and send feedback.

## Example
Here we do something very simple.  We want to obtain a listing of
all files on the system, but do not want the results to stop our
computation.  So we run the `system` call in a thread.

```fm
a = threadnew;                         % Create the thread
threadstart(a,'system',1,'ls -lrt /'); % Start the thread
b = rand(100)\rand(100,1);             % Solve some equations simultaneously
c = threadvalue(a);                    % Retrieve the file list
size(c)                                % It is large!
threadfree(a);
```

The possibilities for threads are significant.  For example,
we can solve equations in parallel, or take Fast Fourier Transforms
on multiple threads.  On multi-processor machines or multicore CPUs,
these threaded calculations will execute in parallel.  Neat.

The reason for the  `nargout` argument is best illustrated with
an example.  Suppose we want to compute the Singular Value
Decomposition `svd` of a matrix `A` in a thread.
The documentation for the `svd` function tells us that
the behavior depends on the number of output arguments we request.
For example, if we want a full decomposition, including the left
and right singular vectors, and a diagonal singular matrix, we
need to use the three-output syntax, instead of the single output
syntax (which returns only the singular values in a column vector):

```fm
A = float(rand(4))
[u,s,v] = svd(A)    % Compute the full decomposition
sigmas = svd(A)     % Only want the singular values
```

Normally, FreeMat uses the left hand side of an assignment to calculate
the number of outputs for the function.  When running a function in a
thread, we separate the assignment of the output from the invokation
of the function.  Hence, we have to provide the number of arguments at the
time we invoke the function.  For example, to compute a full decomposition
in a thread, we specify that we want 3 output arguments:

```fm
a = threadnew;               % Create the thread
threadstart(a,'svd',3,A);    % Start a full decomposition 
[u1,s1,v1] = threadvalue(a); % Retrieve the function values
threadfree(a);
```

If we want to compute just the singular values, we start the thread
function with only one output argument:

```fm
a = threadnew;
threadstart(a,'svd',1,A);
sigmas = threadvalue(a);
threadfree(a)
```
"#,
}

fm_doc::register_doc! {
    name: "threadvalue",
    aliases: [],
    section: "thread",
    summary: "Retrieve the return values from a thread",
    body: r#"
## Usage
The `threadvalue` function retrieves the values returned
by the function specified in the `threadnew` call.  The
syntax for its use is

```text
   [arg1,arg2,...,argN] = threadvalue(handle)
```
where `handle` is the value returned by a `threadnew` call.
Note that there are issues with `nargout`.  See the examples
section of `threadnew` for details on how to work around this
limitation.  Because the function you have spawned with `threadnew`
may still be executing, `threadvalue` must first `threadwait`
for the function to complete before retrieving the output values.
This wait may take an arbitrarily long time if the thread function
is caught in an infinite loop.  Hence, you can also specify
a timeout parameter to `threadvalue` as

```text
   [arg1,arg2,...,argN] = threadvalue(handle,timeout)
```
where the `timeout` is specified in milliseconds.  If the
wait times out, an error is raised (that can be caught with a
`try` and `catch` block.

In either case, if the thread function itself caused an error
and ceased execution abruptly, then calling `threadvalue` will
cause that function to raise an error, allowing you to retrieve
the error that was caused and correct it.  See the examples section
for more information.

## Example
Here we do something very simple.  We want to obtain a listing of
all files on the system, but do not want the results to stop our
computation.  So we run the `system` call in a thread.

```fm
a = threadnew;                         % Create the thread
threadstart(a,'system',1,'ls -lrt /'); % Start the thread
b = rand(100)\rand(100,1);             % Solve some equations simultaneously
c = threadvalue(a);                    % Retrieve the file list
size(c)                                % It is large!
threadfree(a);
```

In this example, we force the threaded function to cause an
exception (by calling the `error` function as the thread
function).  When we call `threadvalue`, we get an error, instead
of the return value of the function

```fm
a = threadnew
threadstart(a,'error',0,'Hello world!'); % Will immediately stop due to error
c = threadvalue(a)                     % The error comes to us
threadfree(a)
```

Note that the error has the text `Thread:` prepended to the message
to help you identify that this was an error in a different thread.
"#,
}

fm_doc::register_doc! {
    name: "threadwait",
    aliases: [],
    section: "thread",
    summary: "Wait on a thread to complete execution",
    body: r#"
## Usage
The `threadwait` function waits for the given thread to complete
execution, and stops execution of the current thread (the one calling
`threadwait`) until the given thread completes.  The syntax for its
use is

```text
   success = threadwait(handle)
```
where `handle` is the value returned by `threadnew` and `success`
is a `logical` vaariable that will be `1` if the wait was successful
or `0` if the wait times out.  By default, the wait is indefinite.  It
is better to use the following form of the function

```text
   success = threadwait(handle,timeout)
```
where `timeout` is the amount of time (in milliseconds) for
the `threadwait` function to wait before a timeout occurs.
If the `threadwait` function succeeds, then the return
value is a logical `1`, and if it fails, the return value
is a logical `0`.  Note that you can call `threadwait` multiple
times on a thread, and if the thread is completed, each one
will succeed.

## Example
Here we lauch the `sleep` function in a thread with a time delay of
10 seconds.  This means that the thread function will not complete
until 10 seconds have elapsed.  When we call `threadwait` on this
thread with a short timeout, it fails, but not when the timeout
is long enough to capture the end of the function call.

```fm
a = threadnew;
threadstart(a,'sleep',0,10);  % start a thread that will sleep for 10
threadwait(a,2000)            % 2 second wait is not long enough
threadwait(a,10000)           % 10 second wait is long enough
threadfree(a)
```
"#,
}
