//! Migrated help docs for the `typecast` section (help-system P7).
//! GENERATED by `cargo xtask migrate-place` — do not edit by hand.

fm_doc::register_section! {
    id: "typecast",
    title: "Type Conversion Functions",
    summary: "Convert between numeric and data types.",
}

fm_doc::register_doc! {
    name: "bin2dec",
    aliases: [],
    section: "typecast",
    summary: "Convert Binary String to Decimal",
    body: r#"
## Usage
Converts a binary string to an integer.  The syntax for its
use is

```text
   y = bin2dec(x)
```
where `x` is a binary string. If `x` is a matrix, then the resulting
`y` is a column vector.

## Example
Here we convert some numbers to bits

```fm-exec
bin2dec('101110')
bin2dec('010')
```
"#,
}

fm_doc::register_doc! {
    name: "bin2int",
    aliases: [],
    section: "typecast",
    summary: "Convert Binary Arrays to Integer",
    body: r#"
## Usage
Converts the binary decomposition of an integer array back
to an integer array.  The general syntax for its use is

```text
   y = bin2int(x)
```
where `x` is a multi-dimensional logical array, where the last
dimension indexes the bit planes (see `int2bin` for an example).
By default, the output of `bin2int` is unsigned `uint32`.  To
get a signed integer, it must be typecast correctly.  A second form for
`bin2int` takes a `'signed'` flag

```text
   y = bin2int(x,'signed')
```
in which case the output is signed.

## Example
The following piece of code demonstrates various uses of the int2bin
function.  First the simplest example:

```fm-exec
A = [2;5;6;2]
B = int2bin(A,8)
bin2int(B)
A = [1;2;-5;2]
B = int2bin(A,8)
bin2int(B)
int32(bin2int(B))
```

## Tets
"#,
}

fm_doc::register_doc! {
    name: "cast",
    aliases: [],
    section: "typecast",
    summary: "Typecast Variable to Specified Type",
    body: r#"
## Usage
The `cast` function allows you to typecast a variable from one
type to another.  The syntax for its use is

```text
    y = cast(x,toclass)
```
where `toclass` is the name of the class to cast `x` to.  Note
that the typecast must make sense, and that `toclass` must be
one of the builtin types.  The current list of supported types is
- `'cell'` for cell-arrays

- `'struct'` for structure-arrays

- `'logical'` for logical arrays

- `'uint8'` for unsigned 8-bit integers

- `'int8'` for signed 8-bit integers

- `'uint16'` for unsigned 16-bit integers

- `'int16'` for signed 16-bit integers

- `'uint32'` for unsigned 32-bit integers

- `'int32'` for signed 32-bit integers

- `'uint64'` for unsigned 64-bit integers

- `'int64'` for signed 64-bit integers

- `'float'` for 32-bit floating point numbers

- `'single'` is a synonym for `'float'`

- `'double'` for 64-bit floating point numbers

- `'char'` for string arrays

## Example
Here is an example of a typecast from a float to an 8-bit integer

```fm-exec
cast(pi,'uint8')
```

and here we cast an array of arbitrary integers to a logical array

```fm-exec
cast([1 0 3 0],'logical')
```
"#,
}

fm_doc::register_doc! {
    name: "char",
    aliases: [],
    section: "typecast",
    summary: "Convert to character array or string",
    body: r#"
## Usage
The `char` function can be used to convert an array
into a string.  It has several forms.  The first form
is

```text
   y = char(x)
```
where `x` is a numeric array containing character codes.
FreeMat does not currently support Unicode, so the
character codes must be in the range of `[0,255]`.  The
output is a string of the same size as `x`.  A second
form is

```text
   y = char(c)
```
where `c` is a cell array of strings, creates a matrix string
where each row contains a string from the corresponding cell array.
The third form is

```text
   y = char(s1, s2, s3, ...)
```
where `si` are a character arrays.  The result is a matrix string
where each row contains a string from the corresponding argument.

## Example
Here is an example of the first technique being used to generate
a string containing some ASCII characters

```fm-exec
char([32:64;65:97])
```

In the next example, we form a character array from a set of
strings in a cell array.  Note that the character array is padded
with spaces to make the rows all have the same length.

```fm-exec
char({'hello','to','the','world'})
```

In the last example, we pass the individual strings as explicit
arguments to `char`

```fm-exec
char('hello','to','the','world')
```
"#,
}

fm_doc::register_doc! {
    name: "complex",
    aliases: [],
    section: "typecast",
    summary: "Create a Complex Number",
    body: r#"
## Usage
Converts the two real input arguments into the real and imaginary part
(respectively) of a complex number.  The syntax
for its use is

```text
   y = complex(x,z)
```
where `x` and `z` are `n`-dimensional numerical arrays.  The usual rules
for binary operators apply (i.e., one of the arguments can be a scalar,
if either is of type `single` the output is single, etc.).
"#,
}

fm_doc::register_doc! {
    name: "dcomplex",
    aliases: [],
    section: "typecast",
    summary: "Convert to Double Precision (deprecated)",
    body: r#"
## Usage
The `dcomplex` function used to convert variables into 64-bit
complex data types in prior versions of FreeMat.  Starting with FreeMat 4,
the type rules are the same as Matlab, hence, there is no distinction
between a 64-bit complex type and and 64-bit real type.  Thus, the `dcomplex`
function is just a synonym for `double`.
"#,
}

fm_doc::register_doc! {
    name: "dec2bin",
    aliases: [],
    section: "typecast",
    summary: "Convert Decimal to Binary String",
    body: r#"
## Usage
Converts an integer to a binary string.  The syntax for its
use is

```text
   y = dec2bin(x,n)
```
where `x` is the positive integer, and `n` is the number of
bits to use in the representation.  Alternately, if you leave
`n` unspecified,

```text
   y = dec2bin(x)
```
the minimum number of bits needed to represent `x` are used.
If `x` is a vector, then the resulting `y` is a character
matrix.

## Example
Here we convert some numbers to bits

```fm-exec
dec2bin(56)
dec2bin(1039456)
dec2bin([63,73,32],5)
```
"#,
}

fm_doc::register_doc! {
    name: "double",
    aliases: [],
    section: "typecast",
    summary: "Convert to 64-bit Floating Point",
    body: r#"
## Usage
Converts the argument to a 64-bit floating point number.  The syntax
for its use is

```text
   y = double(x)
```
where `x` is an `n`-dimensional numerical array.  Conversion follows the
saturation rules.  Note that both `NaN` and `Inf` are both preserved under type conversion.

## Example
The following piece of code demonstrates several uses of `double`.  First,
we convert from an integer (the argument is an integer because no decimal is present):

```fm-exec
double(200)
```

In the next example, a single precision argument is passed in (the presence of
the `f` suffix implies single precision).

```fm-exec
double(400.0f)
```

In the next example, a complex argument is passed in.

```fm-exec
double(3.0+4.0*i)
```

In the next example, a string argument is passed in.  The string argument
is converted into an integer array corresponding to the ASCII values of each character.

```fm-exec
double('helo')
```

In the last example, a cell-array is passed in.  For cell-arrays
and structure arrays, the result is an error.

```fm-exec
# errors: 1
double({4})
```
"#,
}

fm_doc::register_doc! {
    name: "float",
    aliases: [],
    section: "typecast",
    summary: "Convert to 32-bit Floating Point",
    body: r#"
## Usage
Converts the argument to a 32-bit floating point number.  The syntax
for its use is

```text
   y = float(x)
```
where `x` is an `n`-dimensional numerical array.
Conversion follows the saturation rules.  Note that both
`NaN` and `Inf` are both preserved under type conversion.

## Example
The following piece of code demonstrates several uses of `float`.
First, we convert from an integer (the argument is an integer
because no decimal is present):

```fm-exec
float(200)
```

In the next example, a double precision argument is passed
in

```fm-exec
float(400.0)
```

In the next example, a complex argument is passed in.

```fm-exec
float(3.0+4.0*i)
```

In the next example, a string argument is passed in.  The string
argument is converted into an integer array corresponding to the
ASCII values of each character.

```fm-exec
float('helo')
```

In the last example, a cell-array is passed in.  For cell-arrays
and structure arrays, the result is an error.

```fm-exec
# errors: 1
float({4})
```
"#,
}

fm_doc::register_doc! {
    name: "int16",
    aliases: [],
    section: "typecast",
    summary: "Convert to Signed 16-bit Integer",
    body: r#"
## Usage
Converts the argument to an signed 16-bit Integer.  The syntax
for its use is

```text
   y = int16(x)
```
where `x` is an `n`-dimensional numerical array.  Conversion
follows the saturation rules (e.g., if `x` is outside the normal
range for a signed 16-bit integer of `[-32767,32767]`, it is truncated
to that range).  Note that both `NaN` and `Inf` both map to 0.

## Example
The following piece of code demonstrates several uses of `int16`.  First, the routine uses

```fm-exec
int16(100)
int16(-100)
```

In the next example, an integer outside the range  of the type is passed in.
The result is truncated to the range of the data type.

```fm-exec
int16(40000)
```

In the next example, a positive double precision argument is passed in.
The result is the signed integer that is closest to the argument.

```fm-exec
int16(pi)
```

In the next example, a complex argument is passed in.  The result is the
signed complex integer that is closest to the argument.

```fm-exec
int16(5+2*i)
```

In the next example, a string argument is passed in.  The string argument is
converted into an integer array corresponding to the ASCII values of each character.

```fm-exec
int16('helo')
```

In the last example, a cell-array is passed in.  For cell-arrays and
structure arrays, the result is an error.

```fm-exec
# errors: 1
int16({4})
```
"#,
}

fm_doc::register_doc! {
    name: "int2bin",
    aliases: [],
    section: "typecast",
    summary: "Convert Integer Arrays to Binary",
    body: r#"
## Usage
Computes the binary decomposition of an integer array to the specified
number of bits.  The general syntax for its use is

```text
   y = int2bin(x,n)
```
where `x` is a multi-dimensional integer array, and `n` is the number
of bits to expand it to.  The output array `y` has one extra dimension
to it than the input.  The bits are expanded along this extra dimension.

## Example
The following piece of code demonstrates various uses of the int2bin
function.  First the simplest example:

```fm-exec
A = [2;5;6;2]
int2bin(A,8)
A = [1;2;-5;2]
int2bin(A,8)
```
"#,
}

fm_doc::register_doc! {
    name: "int32",
    aliases: [],
    section: "typecast",
    summary: "Convert to Signed 32-bit Integer",
    body: r#"
## Usage
Converts the argument to an signed 32-bit Integer.  The syntax
for its use is

```text
   y = int32(x)
```
where `x` is an `n`-dimensional numerical array.  Conversion
follows the saturation rules (e.g., if `x` is outside the normal
range for a signed 32-bit integer of `[-2147483647,2147483647]`,
it is truncated to that range).  Note that both `NaN` and `Inf` both map to 0.

## Example
The following piece of code demonstrates several uses of `int32`.  First, the routine uses

```fm-exec
int32(100)
int32(-100)
```

In the next example, an integer outside the range  of the type is passed in.  The
result is truncated to the range of the data type.

```fm-exec
int32(40e9)
```

In the next example, a positive double precision argument is passed in.  The
result is the signed integer that is closest to the argument.

```fm-exec
int32(pi)
```

In the next example, a complex argument is passed in.  The result is the signed
complex integer that is closest to the argument.

```fm-exec
int32(5+2*i)
```

In the next example, a string argument is passed in.  The string argument is
converted into an integer array corresponding to the ASCII values of each character.

```fm-exec
int32('helo')
```

In the last example, a cell-array is passed in.  For cell-arrays and structure
arrays, the result is an error.

```fm-exec
# errors: 1
int32({4})
```
"#,
}

fm_doc::register_doc! {
    name: "int64",
    aliases: [],
    section: "typecast",
    summary: "Convert to Signed 64-bit Integer",
    body: r#"
## Usage
Converts the argument to an signed 64-bit Integer.  The syntax
for its use is

```text
   y = int64(x)
```
where `x` is an `n`-dimensional numerical array.  Conversion
follows the saturation rules (e.g., if `x` is outside the normal
range for a signed 64-bit integer of `[-2^63+1,2^63-1]`, it is
truncated to that range).  Note that both `NaN` and `Inf` both map to 0.

## Example
The following piece of code demonstrates several uses of `int64`.  First, the routine uses

```fm-exec
int64(100)
int64(-100)
```

In the next example, an integer outside the range  of the type is passed in.
The result is truncated to the range of the data type.

```fm-exec
int64(40e9)
```

In the next example, a positive double precision argument is passed in.  The
result is the signed integer that is closest to the argument.

```fm-exec
int64(pi)
```

In the next example, a complex argument is passed in.  The result is the
complex signed integer that is closest to the argument.

```fm-exec
int64(5+2*i)
```

In the next example, a string argument is passed in.  The string argument is
converted into an integer array corresponding to the ASCII values of each character.

```fm-exec
int64('helo')
```

In the last example, a cell-array is passed in.  For cell-arrays and structure
arrays, the result is an error.

```fm-exec
# errors: 1
int64({4})
```
"#,
}

fm_doc::register_doc! {
    name: "int8",
    aliases: [],
    section: "typecast",
    summary: "Convert to Signed 8-bit Integer",
    body: r#"
## Usage
Converts the argument to an signed 8-bit Integer.  The syntax
for its use is

```text
   y = int8(x)
```
where `x` is an `n`-dimensional numerical array.  Conversion
follows the saturation rules (e.g., if `x` is outside the normal
range for a signed 8-bit integer of `[-127,127]`, it is truncated to that
range.  Note that
both `NaN` and `Inf` both map to 0.

## Example
The following piece of code demonstrates several uses of `int8`.  First, the routine uses

```fm-exec
int8(100)
int8(-100)
```

In the next example, an integer outside the range  of the type is passed in.
The result is truncated to the range of the type.

```fm-exec
int8(400)
```

In the next example, a positive double precision argument is passed in.
The result is the signed integer that is closest to the argument.

```fm-exec
int8(pi)
```

In the next example, a complex argument is passed in.  The result is the
signed complex integer that is closest to the argument.

```fm-exec
int8(5+2*i)
```

In the next example, a string argument is passed in.  The string argument
is converted into an integer array corresponding to the ASCII values of each character.

```fm-exec
int8('helo')
```

In the last example, a cell-array is passed in.  For cell-arrays and
structure arrays, the result is an error.

```fm-exec
# errors: 1
int8({4})
```
"#,
}

fm_doc::register_doc! {
    name: "logical",
    aliases: [],
    section: "typecast",
    summary: "Convert to Logical",
    body: r#"
## Usage
Converts the argument to a logical array.  The syntax
for its use is

```text
   y = logical(x)
```
where `x` is an `n`-dimensional numerical array.  Any nonzero
element maps to a logical 1.

## Example
Here we convert an integer array to `logical`:

```fm-exec
logical([1,2,3,0,0,0,5,2,2])
```

The same example with double precision values:

```fm-exec
logical([pi,pi,0,e,0,-1])
```
"#,
}

fm_doc::register_doc! {
    name: "single",
    aliases: [],
    section: "typecast",
    summary: "Convert to 32-bit Floating Point",
    body: r#"
## Usage
A synonym for the `float` function, converts the argument to
a 32-bit floating point number.  The syntax
for its use is

```text
   y = single(x)
```
where `x` is an `n`-dimensional numerical array.  Conversion
follows the general C rules.  Note that both `NaN` and `Inf`
are both preserved under type conversion.
"#,
}

fm_doc::register_doc! {
    name: "string",
    aliases: [],
    section: "typecast",
    summary: "Convert Array to String",
    body: r#"
## Usage
Converts the argument array into a string.  The syntax for its
use is

```text
   y = string(x)
```
where `x` is an `n`-dimensional numerical array.

## Example
Here we take an array containing ASCII codes for a string, and
convert it into a string.

```fm-exec
a = [104,101,108,108,111]
string(a)
```
"#,
}

fm_doc::register_doc! {
    name: "uint16",
    aliases: [],
    section: "typecast",
    summary: "Convert to Unsigned 16-bit Integer",
    body: r#"
## Usage
Converts the argument to an unsigned 16-bit Integer.  The syntax
for its use is

```text
   y = uint16(x)
```
where `x` is an `n`-dimensional numerical array.  Conversion
follows saturation rules (e.g., if `x` is outside the normal
range for an unsigned 16-bit integer of `[0,65535]`, it is truncated
to that range.  Note that
both `NaN` and `Inf` both map to 0.

## Example
The following piece of code demonstrates several uses of `uint16`.

```fm-exec
uint16(200)
```

In the next example, an integer outside the range  of the type is passed in.
The result is truncated to the maximum value of the data type.

```fm-exec
uint16(99400)
```

In the next example, a negative integer is passed in.  The result is
truncated to zero.

```fm-exec
uint16(-100)
```

In the next example, a positive double precision argument is passed in.
The result is the unsigned integer that is closest to the argument.

```fm-exec
uint16(pi)
```

In the next example, a complex argument is passed in.  The result is the
complex unsigned integer that is closest to the argument.

```fm-exec
uint16(5+2*i)
```

In the next example, a string argument is passed in.  The string argument is converted into an integer array corresponding to the ASCII values of each character.

```fm-exec
uint16('helo')
```

In the last example, a cell-array is passed in.  For cell-arrays and structure arrays, the result is an error.

```fm-exec
# errors: 1
uint16({4})
```
"#,
}

fm_doc::register_doc! {
    name: "uint32",
    aliases: [],
    section: "typecast",
    summary: "Convert to Unsigned 32-bit Integer",
    body: r#"
## Usage
Converts the argument to an unsigned 32-bit Integer.  The syntax
for its use is

```text
   y = uint32(x)
```
where `x` is an `n`-dimensional numerical array.  Conversion
follows saturation rules (e.g., if `x` is outside the normal
range for an unsigned 32-bit integer of `[0,4294967295]`, it is
truncated to that range. Note that both `NaN` and `Inf` both map to 0.

## Example
The following piece of code demonstrates several uses of `uint32`.

```fm-exec
uint32(200)
```

In the next example, an integer outside the range of the type is passed in.
The result is truncated to the maximum value of the data type.

```fm-exec
uint32(40e9)
```

In the next example, a negative integer is passed in.  The result is
truncated to zero.

```fm-exec
uint32(-100)
```

In the next example, a positive double precision argument is passed in.
The result is the unsigned integer that is closest to the argument.

```fm-exec
uint32(pi)
```

In the next example, a complex argument is passed in.  The result is the
complex unsigned integer that is closest to the argument.

```fm-exec
uint32(5+2*i)
```

In the next example, a string argument is passed in.  The string argument
is converted into an integer array corresponding to the ASCII values of each character.

```fm-exec
uint32('helo')
```

In the last example, a cell-array is passed in.  For cell-arrays and
structure arrays, the result is an error.

```fm-exec
# errors: 1
uint32({4})
```
"#,
}

fm_doc::register_doc! {
    name: "uint64",
    aliases: [],
    section: "typecast",
    summary: "Convert to Unsigned 64-bit Integer",
    body: r#"
## Usage
Converts the argument to an unsigned 64-bit Integer.  The syntax
for its use is

```text
   y = uint64(x)
```
where `x` is an `n`-dimensional numerical array.  Conversion
follows saturation rules (e.g., if `x` is outside the normal
range for an unsigned 64-bit integer of `[0,2^64-1]`, it is
truncated to that range.  Note that both `NaN` and `Inf` both map to 0.

## Example
The following piece of code demonstrates several uses of `uint64`.

```fm-exec
uint64(200)
```

In the next example, an integer outside the range  of the type is passed in.
The result is truncated to the maximum value of the data type.

```fm-exec
uint64(40e9)
```

In the next example, a negative integer is passed in.  The result is zero.

```fm-exec
uint64(-100)
```

In the next example, a positive double precision argument is passed in.
The result is the unsigned integer that is closest to the argument.

```fm-exec
uint64(pi)
```

In the next example, a complex argument is passed in.  The result is the
complex unsigned integer that is closest to the argument.

```fm-exec
uint64(5+2*i)
```

In the next example, a string argument is passed in.  The string argument is
converted into an integer array corresponding to the ASCII values of each character.

```fm-exec
uint64('helo')
```

In the last example, a cell-array is passed in.  For cell-arrays and structure
arrays, the result is an error.

```fm-exec
# errors: 1
uint64({4})
```
"#,
}

fm_doc::register_doc! {
    name: "uint8",
    aliases: [],
    section: "typecast",
    summary: "Convert to Unsigned 8-bit Integer",
    body: r#"
## Usage
Converts the argument to an unsigned 8-bit Integer.  The syntax
for its use is

```text
   y = uint8(x)
```
where `x` is an `n`-dimensional numerical array.  Conversion
follows saturation rules (e.g., if `x` is outside the normal
range for an unsigned 8-bit integer of `[0,255]`, it is truncated
to that range. Note that
both `NaN` and `Inf` both map to 0.

## Example
The following piece of code demonstrates several uses of `uint8`.

```fm-exec
uint8(200)
```

In the next example, an integer outside the range  of the type is passed in.
The result is truncated to the maximum value of the data type.

```fm-exec
uint8(400)
```

In the next example, a negative integer is passed in.  The result is
trunated to zero.

```fm-exec
uint8(-100)
```

In the next example, a positive double precision argument is passed in.
The result is the unsigned integer that is closest to the argument.

```fm-exec
uint8(pi)
```

In the next example, a complex argument is passed in.  The result is
complex unsigned integer that is closest to the argument.

```fm-exec
uint8(5+2*i)
```

In the next example, a string argument is passed in.  The string argument
is converted into an integer array corresponding to the ASCII values of each character.

```fm-exec
uint8('helo')
```

In the last example, a cell-array is passed in.  For cell-arrays and
structure arrays, the result is an error.

```fm-exec
# errors: 1
uint8({4})
```
"#,
}
