//! Migrated help docs for the `variables` section (help-system P7).
//! GENERATED by `cargo xtask migrate-place` — do not edit by hand.

fm_doc::register_section! {
    id: "variables",
    title: "Variables and Arrays",
    summary: "Create, assign, and manage variables and arrays.",
}

fm_doc::register_doc! {
    name: "functionhandles",
    aliases: [],
    section: "variables",
    summary: "Function Handles",
    body: r#"
## Usage
Starting with version 1.11, FreeMat now supports `function handles`,
or `function pointers`.  A `function handle` is an alias for a function
or script that is stored in a variable.  First, the way to assign
a function handle is to use the notation

```text
    handle = @func
```
where `func` is the name to point to.  The function `func` must exist
at the time we make the call.  It can be a local function (i.e., a
subfunction).  To use the `handle`, we can either pass it to `feval`
via

```text
   [x,y] = feval(handle,arg1,arg2).
```
Alternately, you can the function directly using the notation

```text
   [x,y] = handle(arg1,arg2)
```
"#,
}

fm_doc::register_doc! {
    name: "global",
    aliases: [],
    section: "variables",
    summary: "Global Variables",
    body: r#"
## Usage
Global variables are shared variables that can be
seen and modified from any function or script that
declares them.  The syntax for the `global` statement
is

```text
  global variable_1 variable_2 ...
```
The `global` statement must occur before the variables
appear.

## Example
Here is an example of two functions that use a global
variable to communicate an array between them.  The
first function sets the global variable.

```fm-file:set_global.m
function set_global(x)
  global common_array
  common_array = x;
```

```text
     set_global.m
```

The second function retrieves the value from the global
variable

```fm-file:get_global.m
function x = get_global
  global common_array
  x = common_array;
```

```text
     get_global.m
```

Here we exercise the two functions

```fm-exec
set_global('Hello')
get_global
```
"#,
}

fm_doc::register_doc! {
    name: "indexing",
    aliases: [],
    section: "variables",
    summary: "Indexing Expressions",
    body: r#"
## Usage
There are three classes of indexing expressions available
in FreeMat: `()`, `{}`, and `.`  Each is explained below
in some detail, and with its own example section.

## Array Indexing
We start with array indexing `()`,
which is the most general indexing expression, and can be
used on any array.  There are two general forms for the
indexing expression - the N-dimensional form, for which
the general syntax is

```text
  variable(index_1,index_2,...,index_n)
```
and the vector form, for which the general syntax is

```text
  variable(index)
```
Here each index expression is either a scalar, a range
of integer values, or the special token `:`, which is
shorthand for `1:end`.  The keyword `end`, when included
in an indexing expression, is assigned the length of the
array in that dimension.  The concept is easier to demonstrate
than explain.  Consider the following examples:

```fm-exec
A = zeros(4)
B = float(randn(2))
A(2:3,2:3) = B
```

Here the array indexing was used on the left hand side only.
It can also be used for right hand side indexing, as in

```fm-exec
C = A(2:3,1:end)
```

Note that we used the `end` keyword to avoid having to know
that `A` has 4 columns.  Of course, we could also use the
`:` token instead:

```fm-exec
C = A(2:3,:)
```

An extremely useful example of `:` with array indexing is for
slicing.  Suppose we have a 3-D array, that is `2 x 2 x 3`,
and we want to set the middle slice:

```fm-exec
D = zeros(2,2,3)
D(:,:,2) = int32(10*rand(2,2))
```

In another level of nuance, the assignment expression will
automatically fill in the indexed rectangle on the left using
data from the right hand side, as long as the lengths match.
So we can take a vector and roll it into a matrix using this
approach:

```fm-exec
A = zeros(4)
v = [1;2;3;4]
A(2:3,2:3) = v
```

The N-dimensional form of the variable index is limited
to accessing only (hyper-) rectangular regions of the
array.  You cannot, for example, use it to access only
the diagonal elements of the array.  To do that, you use
the second form of the array access (or a loop).  The
vector form treats an arbitrary N-dimensional array as though
it were a column vector.  You can then access arbitrary
subsets of the arrays elements (for example, through a `find`
expression) efficiently.  Note that in vector form, the `end`
keyword takes the meaning of the total length of the array
(defined as the product of its dimensions), as opposed to the
size along the first dimension.

## Cell Indexing
The second form of indexing operates, to a large extent, in
the same manner as the array indexing, but it is by no means
interchangable.  As the name implies, `cell`-indexing applies
only to `cell` arrays.  For those familiar with `C`, cell-
indexing is equivalent to pointer derefencing in `C`.  First,
the syntax:

```text
  variable{index_1,index_2,...,index_n}
```
and the vector form, for which the general syntax is

```text
  variable{index}
```
The rules and interpretation for N-dimensional and vector indexing
are identical to `()`, so we will describe only the differences.
In simple terms, applying `()` to a cell-array returns another
cell array that is a subset of the original array.  On the other
hand, applying `{}` to a cell-array returns the contents of that
cell array.  A simple example makes the difference quite clear:

```fm-exec
A = {1, 'hello', [1:4]}
A(1:2)
A{1:2}
```

You may be surprised by the response to the last line.  The output
is multiple assignments to `ans`!.  The output of a cell-array
dereference can be used anywhere a list of expressions is required.
This includes arguments and returns for function calls, matrix
construction, etc.  Here is an example of using cell-arrays to pass
parameters to a function:

```fm-exec
A = {[1,3,0],[5,2,7]}
max(A{1:end})
```

And here, cell-arrays are used to capture the return.

```fm-exec
[K{1:2}] = max(randn(1,4))
```

Here, cell-arrays are used in the matrix construction process:

```fm-exec
C = [A{1};A{2}]
```

Note that this form of indexing is used to implement variable
length arguments to function.  See `varargin` and `varargout`
for more details.

## Structure Indexing
The third form of indexing is structure indexing.  It can only
be applied to structure arrays, and has the general syntax

```text
  variable.fieldname
```
where `fieldname` is one of the fields on the structure.  Note that
in FreeMat, fields are allocated dynamically, so if you reference
a field that does not exist in an assignment, it is created automatically
for you.  If variable is an array, then the result of the `.`
reference is an expression list, exactly like the `{}` operator.  Hence,
we can use structure indexing in a simple fashion:

```fm-exec
clear A
A.color = 'blue'
B = A.color
```

Or in more complicated ways using expression lists for function arguments

```fm-exec
clear A
A(1).maxargs = [1,6,7,3]
A(2).maxargs = [5,2,9,0]
max(A.maxargs)
```

or to store function outputs

```fm-exec
clear A
A(1).maxreturn = [];
A(2).maxreturn = [];
[A.maxreturn] = max(randn(1,4))
```

FreeMat now also supports the so called dynamic-field indexing
expressions.  In this mode, the fieldname is supplied through
an expression instead of being explicitly provided.  For example,
suppose we have a set of structure indexed by color,

```fm-exec
x.red = 430;
x.green = 240;
x.blue = 53;
x.yello = 105
```

Then we can index into the structure `x` using a dynamic field
reference:

```fm-exec
y = 'green'
a = x.(y)
```

Note that the indexing expression has to resolve to a string for
dynamic field indexing to work.

## Complex Indexing
The indexing expressions described above can be freely combined
to affect complicated indexing expressions.  Here is an example
that exercises all three indexing expressions in one assignment.

```fm-exec
Z{3}.foo(2) = pi
```

From this statement, FreeMat infers that Z is a cell-array of
length 3, that the third element is a structure array (with one
element), and that this structure array contains a field named
'foo' with two double elements, the second of which is assigned
a value of pi.
"#,
}

fm_doc::register_doc! {
    name: "matrix",
    aliases: [],
    section: "variables",
    summary: "Matrix Definitions",
    body: r#"
## Usage
The matrix is the basic datatype of FreeMat.  Matrices can be
defined using the following syntax

```text
  A = [row_def1;row_def2;...,row_defN]
```
where each row consists of one or more elements, seperated by
commas

```text
  row_defi = element_i1,element_i2,...,element_iM
```
Each element can either be a scalar value or another matrix,
provided that the resulting matrix definition makes sense.
In general this means that all of the elements belonging
to a row have the same number of rows themselves, and that
all of the row definitions have the same number of columns.
Matrices are actually special cases of N-dimensional arrays
where `N<=2`.  Higher dimensional arrays cannot be constructed
using the bracket notation described above.  The type of a
matrix defined in this way (using the bracket notation) is
determined by examining the types of the elements.  The resulting
type is chosen so no information is lost on any of the elements
(or equivalently, by choosing the highest order type from those
present in the elements).

## Examples
Here is an example of a matrix of `int32` elements (note that
untyped integer constants default to type `int32`).

```fm-exec
A = [1,2;5,8]
```

Now we define a new matrix by adding a column to the right of
`A`, and using float constants.

```fm-exec
B = [A,[3.2f;5.1f]]
```

Next, we add extend `B` by adding a row at the bottom.  Note
how the use of an untyped floating point constant forces the
result to be of type `double`

```fm-exec
C = [B;5.2,1.0,0.0]
```

If we instead add a row of `complex` values (recall that `i` is
a `complex` constant, not a `dcomplex` constant)

```fm-exec
D = [B;2.0f+3.0f*i,i,0.0f]
```

Likewise, but using `dcomplex` constants

```fm-exec
E = [B;2.0+3.0*i,i,0.0]
```

Finally, in FreeMat, you can construct matrices with strings
as contents, but you have to make sure that if the matrix has
more than one row, that all the strings have the same length.

```fm-exec
F = ['hello';'there']
```
"#,
}

fm_doc::register_doc! {
    name: "persistent",
    aliases: [],
    section: "variables",
    summary: "Persistent Variables",
    body: r#"
## Usage
Persistent variables are variables whose value persists between
calls to a function or script.  The general syntax for its
use is

```text
   persistent variable1 variable2 ... variableN
```
The `persistent` statement must occur before the variable
is the tagged as persistent.  Per the MATLAB API documentation
an empty variable is created when the `persistent` statement
is called.

## Example
Here is an example of a function that counts how many
times it has been called.

```fm-file:count_calls.m
function count_calls
  persistent ccount
  if isempty(ccount); ccount = 0; end;
  ccount = ccount + 1;
  printf('Function has been called %d times\n',ccount);
```

```text
     count_calls.m
```

We now call the function several times:

```fm-exec
for i=1:10; count_calls; end
```
"#,
}

fm_doc::register_doc! {
    name: "struct",
    aliases: [],
    section: "variables",
    summary: "Structure Array Constructor",
    body: r#"
## Usage
Creates an array of structures from a set of field, value pairs.
The syntax is

```text
   y = struct(n_1,v_1,n_2,v_2,...)
```
where `n_i` are the names of the fields in the structure array, and
`v_i` are the values.  The values `v_i` must either all be
scalars, or be cell-arrays of all the same dimensions.  In the latter
case, the
output structure array will have dimensions dictated by this common
size.  Scalar entries for the `v_i` are replicated to fill out
their dimensions. An error is raised if the inputs are not properly matched (i.e., are
not pairs of field names and values), or if the size of any two non-scalar
values cell-arrays are different.

Another use of the `struct` function is to convert a class into a
structure.  This allows you to access the members of the class, directly
but removes the class information from the object.

## Example
This example creates a 3-element structure array with three fields, `foo`
`bar` and `key`, where the contents of `foo` and `bar` are provided
explicitly as cell arrays of the same size, and the contents of `bar`
are replicated from a scalar.

```fm-exec
y = struct('foo',{1,3,4},'bar',{'cheese','cola','beer'},'key',508)
y(1)
y(2)
y(3)
```

An alternate way to create a structure array is to initialize the last
element of each field of the structure

```fm-exec
Test(2,3).Type = 'Beer';
Test(2,3).Ounces = 12;
Test(2,3).Container = 'Can';
Test(2,3)
Test(1,1)
```
"#,
}
