[package]
name = "fm-builtins"
description = "FreeMat-rs builtin functions ported from libCore"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
fm-core = { version = "0.0.0", path = "../fm-core" }
fm-interp = { version = "0.0.0", path = "../fm-interp" }
fm-linalg = { version = "0.0.0", path = "../fm-linalg" }
rand.workspace = true
rand_distr.workspace = true

[lints]
workspace = true
